import { useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {
  ArrowRight, BadgeDollarSign, BriefcaseBusiness, CalendarClock, Check,
  CircleAlert, ExternalLink, FileCheck2, HeartPulse, Home, Landmark,
  PlaneTakeoff, RefreshCw, Route, ShieldCheck, Smartphone, WalletCards,
} from 'lucide-react';
import SEOHead from '../SEOHead';
import { AffiliateDisclosure } from '../design/AffiliateDisclosure';
import { EditorialHero } from '../design/EditorialHero';
import { FaqSplitSection } from '../design/FaqSplitSection';
import { PageSectionNav } from '../design/PageSectionNav';
import { RelatedGuidesSection } from '../design/RelatedGuidesSection';
import { SectionHeading } from '../design/SectionHeading';
import { SourceMethodSection } from '../design/SourceMethodSection';
import { SAILY_GENERIC, TRIP_GENERIC, withPlacementSubId } from '../../lib/affiliates';

const BOI_LTR = 'https://ltr.boi.go.th/';
const BOI_ISSUANCE = 'https://ltr.boi.go.th/page/visa-issuance-info.html';
const BOI_BROCHURE = 'https://ltr.boi.go.th/documents/BOI-brochure%202025-LTR.pdf';
const BOI_APPLICATION = 'https://visa.boi.go.th/';
const BOI_DOCUMENTS = 'https://ltr.boi.go.th/page/required-documents.html';
const LONDON_LTR = 'https://london.thaiembassy.org/en/page/long-term-resident-visa';
const LONDON_FEES = 'https://london.thaiembassy.org/en/publicservice/81755-visa-fees?cate=5d6636c215e39c3bd0006c8d';

const sectionNav = [
  { href: '#route' as const, label: 'Eligibility', icon: Route },
  { href: '#evidence' as const, label: 'Evidence', icon: FileCheck2 },
  { href: '#five-plus-five' as const, label: '5 + 5 years', icon: CalendarClock },
  { href: '#benefits' as const, label: 'Benefits', icon: ShieldCheck },
  { href: '#apply' as const, label: 'Apply', icon: PlaneTakeoff },
  { href: '#questions' as const, label: 'Questions', icon: CircleAlert },
];

type LtrRouteKey = 'wealth' | 'pension' | 'remote' | 'skilled';

const ltrRoutes: Array<{ key: LtrRouteKey; short: string; label: string; threshold: string; title: string; intro: string; proof: string[]; note: string }> = [
  {
    key: 'wealth', short: 'LTR-W', label: 'Wealthy Global Citizen', threshold: 'USD 1m assets + USD 500k Thai investment',
    title: 'Global assets and an existing investment in Thailand.',
    intro: 'Under the 2025 BOI criteria, this route no longer has a separate income threshold. You must still show at least USD 1 million in personal assets and already hold at least USD 500,000 in qualifying Thai investments before applying.',
    proof: ['At least USD 1 million in personal worldwide assets', 'At least USD 500,000 in Thai bonds, business or property', 'Qualifying investment already held in your own name', 'Health cover, Thai social security or USD 100,000 deposit'],
    note: 'Buying one property does not qualify you by itself. The full asset, Thai-investment and health-cover route must remain satisfied during the programme.',
  },
  {
    key: 'pension', short: 'LTR-P', label: 'Wealthy Pensioner', threshold: 'Age 50+ · USD 80k passive, or USD 40k + 250k',
    title: 'Only passive or unearned income meets the pension test.',
    intro: 'You must be at least 50. The main route uses at least USD 80,000 in annual passive income. From USD 40,000 to below USD 80,000, BOI requires an additional qualifying Thai investment of at least USD 250,000.',
    proof: ['Age 50 or older', 'Pension, rent, realised capital gain, dividend or interest', 'USD 250,000 Thai investment for the lower-income option', 'Health cover, Thai social security or USD 100,000 deposit'],
    note: 'Salary and active employment income do not count as passive income for LTR-P. Compare the separate retirement-visa routes if these thresholds do not fit.',
  },
  {
    key: 'remote', short: 'LTR-T', label: 'Work-from-Thailand Professional', threshold: 'USD 80k, or USD 40k + extra qualification',
    title: 'Your overseas employer must qualify as well as you.',
    intro: 'The employer must be a listed company, or a private company operating for at least three years with combined revenue of USD 50 million over the last three years. Certain wholly owned subsidiaries can rely on a qualifying parent.',
    proof: ['Average income of USD 80,000 over the previous two years', 'Or USD 40,000 plus a qualifying master’s degree, IP or Series A funding', 'Employment contract with a qualifying overseas company', 'Health cover, Thai social security or USD 100,000 deposit'],
    note: 'BOI does not issue a Thai work permit for LTR-T: this route is for remote work for an overseas employer, not employment by a Thai entity.',
  },
  {
    key: 'skilled', short: 'LTR-H', label: 'Highly Skilled Professional', threshold: 'Target industry + USD 80k, or USD 40k + STEM master’s',
    title: 'A BOI target industry or recognised expertise is the gateway.',
    intro: 'You work for a qualifying organisation in a target industry or prove specified expertise. The usual income route is USD 80,000 averaged over two years, or USD 40,000 with a science-and-technology master’s degree or higher; Thai government work has a stated exception.',
    proof: ['Contract or recognised expertise in a BOI target industry', 'Income history or a documented exception', 'A relevant STEM master’s degree for the lower-income route', 'Health cover, Thai social security or USD 100,000 deposit'],
    note: 'BOI names the 17% personal-income-tax rate specifically for Highly Skilled Professionals. Obtain individual Thai tax advice before relying on it.',
  },
];

const quickFacts = [
  { icon: CalendarClock, label: 'Real structure', value: '5 + 5 years', text: 'An initial stay of up to five years, followed by reassessment for the second period.' },
  { icon: WalletCards, label: 'Issue in Thailand', value: '50,000 THB', text: 'Per person at TIESC; BOI does not charge for qualification endorsement.' },
  { icon: BadgeDollarSign, label: 'London listing', value: '£1,500', text: 'The embassy’s live fee page lists this for ten-year multiple-entry LTR issuance.' },
  { icon: HeartPulse, label: 'Health route', value: 'USD 50,000', text: 'Or qualifying Thai social security, or a maintained USD 100,000 deposit.' },
];

const faqs = [
  { question: 'What is Thailand’s LTR Visa?', answer: 'The Long-Term Resident Visa is a BOI programme for four groups: Wealthy Global Citizens, Wealthy Pensioners, Work-from-Thailand Professionals and Highly Skilled Professionals. Although described as a ten-year visa, the stay structure is up to five years followed by reassessment for up to five more.' },
  { question: 'How much does a Thailand LTR Visa cost?', answer: 'BOI lists 50,000 THB per person when the visa is issued at TIESC in Thailand and no fee for qualification endorsement. The Royal Thai Embassy London fee page lists £1,500 for LTR issuance. Check the live fee at the point of application because embassy fees can vary by currency and location.' },
  { question: 'How long does a Thailand LTR application take?', answer: 'BOI’s programme material states 20 working days for qualification review once the required file is complete. Requests for more evidence extend the real timeline. After endorsement, you have 60 days to complete visa issuance.' },
  { question: 'Does every LTR holder pay 17% income tax?', answer: 'No. BOI names the 17% personal-income-tax rate specifically for Highly Skilled Professionals. Category, tax residence, source of income and current Thai law still matter, so this page cannot replace individual tax advice.' },
  { question: 'Does an LTR-T remote worker receive a digital work permit?', answer: 'Not for the overseas remote work that defines LTR-T. BOI says Work-from-Thailand Professionals work for foreign employers and do not receive a Thai work permit for that activity. Thai employment requires the applicable work-authorisation route.' },
  { question: 'Can buying a house qualify you for LTR?', answer: 'Not by itself. Thai property can form part of the USD 500,000 investment for LTR-W, but that route also requires USD 1 million in personal assets and the common health-cover route. Property may also count toward the USD 250,000 investment in the lower-income LTR-P option.' },
  { question: 'What is the difference between LTR and Thailand Privilege?', answer: 'LTR is a strict financial or professional qualification programme with BOI benefits. Thailand Privilege is a paid membership programme with its own residence and service tiers. They are different legal and evidence routes, not simply cheap and expensive versions of the same visa.' },
  { question: 'Can family members join an LTR holder?', answer: 'The 2025 BOI update broadened dependent eligibility beyond the older spouse-and-children wording. Because older BOI web copy can still conflict with newer programme material, check the current dependent checklist in the BOI portal before budgeting or assuming who qualifies.' },
];

export default function ThailandLtrVisaGuideEn() {
  const [route, setRoute] = useState<LtrRouteKey>('remote');
  const selected = ltrRoutes.find((item) => item.key === route) ?? ltrRoutes[0];
  const hotelHref = withPlacementSubId(TRIP_GENERIC, 'en-ltr-visa', 'first-month');
  const esimHref = withPlacementSubId(SAILY_GENERIC, 'en-ltr-visa', 'arrival');
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((faq) => ({ '@type': 'Question', name: faq.question, acceptedAnswer: { '@type': 'Answer', text: faq.answer } })) };
  const webPageSchema = { '@context': 'https://schema.org', '@type': 'WebPage', name: 'Thailand LTR Visa guide for UK applicants', description: 'Compare LTR-W, LTR-P, LTR-T and LTR-H using current BOI criteria, 5+5-year structure and issuance process.', url: 'https://go2-thailand.com/visa/ltr-visa/', inLanguage: 'en-GB', dateModified: '2026-07-27' };
  const breadcrumbSchema = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://go2-thailand.com/' },
    { '@type': 'ListItem', position: 2, name: 'Thailand visas', item: 'https://go2-thailand.com/visa/' },
    { '@type': 'ListItem', position: 3, name: 'Thailand LTR Visa', item: 'https://go2-thailand.com/visa/ltr-visa/' },
  ] };

  return <>
    <SEOHead title="Thailand LTR Visa: requirements, 5+5 years and cost" description="Thailand LTR Visa guide: compare LTR-W, LTR-P, LTR-T and LTR-H, current BOI thresholds, 5+5-year structure, cost and UK application process." ogImage="https://go2-thailand.com/images/redesign/thailand-ltr-visa-hero.webp">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(webPageSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
    </SEOHead>
    <div className="bg-canvas text-charcoal">
      <EditorialHero image="/images/redesign/thailand-ltr-visa-hero.webp" imageAlt="International professionals planning long-term residence from a Bangkok home" breadcrumbs={[{ label: 'Thailand', href: '/' }, { label: 'Visas', href: '/visa/' }, { label: 'LTR Visa' }]} eyebrow="LTR-W · LTR-P · LTR-T · LTR-H" title={<>Thailand LTR Visa.<br /><span className="text-saffron">Do you really qualify?</span></>} subtitle="Ten years begins with four demanding evidence routes." description="Assets, passive income, a qualifying overseas employer or expertise in a target industry: your route decides what BOI examines. Compare the thresholds before building the file." actions={[{ label: 'Compare the four routes', href: '#route', kind: 'primary' }, { label: 'Open the official BOI check', href: BOI_LTR, kind: 'secondary', newTab: true }]} minHeightClassName="min-h-[760px] lg:min-h-[720px]" titleClassName="max-w-[900px] text-[3.2rem] leading-[0.88] !text-white sm:text-[4.55rem] lg:text-[5.05rem]" subtitleClassName="max-w-[650px] !text-white" descriptionClassName="mt-4 max-w-[590px] text-sm leading-7 !text-white opacity-72" imageClassName="object-cover object-[73%_center] lg:object-center" gradientClassName="bg-[linear-gradient(180deg,rgba(4,42,34,0.18)_0%,rgba(4,42,34,0.6)_46%,rgba(4,42,34,0.99)_100%)] lg:bg-[linear-gradient(90deg,rgba(4,42,34,0.99)_0%,rgba(4,42,34,0.96)_44%,rgba(4,42,34,0.17)_70%,rgba(4,42,34,0.02)_100%)]" contentClassName="max-w-[920px] [&_nav]:!text-white/60 [&_nav_span]:!text-white/75" sideCard={<div className="absolute bottom-8 right-[max(2rem,calc((100vw-1280px)/2))] z-10 hidden w-[315px] rounded-2xl border border-white/22 bg-jade/82 p-5 text-white shadow-editorial-card backdrop-blur-lg xl:block"><p className="text-[9px] font-extrabold uppercase tracking-[0.15em] text-saffron-light">The real structure</p><strong className="mt-3 block font-display text-3xl font-semibold">5 years + review + 5 years</strong><p className="mt-3 text-[10px] font-semibold leading-5 text-white/58">Assets, investment, employment and health cover must continue to satisfy the programme.</p></div>} />
      <PageSectionNav items={sectionNav} />

      <section className="section-divider-bottom py-14 lg:py-20"><div className="container-custom"><SectionHeading eyebrow="Separate qualification, issuance and stay" title="A ten-year label contains three different decisions." description="BOI endorsement is free. Only after qualification do you choose the place of visa issuance and begin the first permitted-stay period." /><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{quickFacts.map((fact) => { const Icon = fact.icon; return <article key={fact.label} className="rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl border border-saffron/30 bg-canvas text-jade"><Icon size={20} /></span><span className="text-[9px] font-extrabold uppercase tracking-[0.13em] text-saffron-dark">{fact.label}</span></div><h2 className="mt-5 font-display text-[1.65rem] font-semibold leading-tight text-jade">{fact.value}</h2><p className="mt-3 text-xs font-medium leading-5 text-charcoal/62">{fact.text}</p></article>; })}</div><div className="mt-5 flex flex-col gap-4 rounded-2xl border border-saffron/25 bg-tonal p-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><RefreshCw size={22} className="mt-1 shrink-0 text-saffron-dark" /><div><strong className="font-display text-2xl font-semibold text-jade">The 2025 update makes many older LTR guides unreliable.</strong><p className="mt-2 text-xs font-medium leading-6 text-charcoal/64">We use BOI’s updated asset, employer and dependent criteria and flag where older official web wording still differs.</p></div></div><a href={BOI_BROCHURE} target="_blank" rel="noopener noreferrer" className="btn-jade shrink-0">Read the 2025 update <ExternalLink size={15} /></a></div></div></section>

      <section id="route" className="section-divider-bottom scroll-mt-24 bg-tonal py-16 lg:py-24"><div className="container-custom"><SectionHeading eyebrow="Four groups, four hard thresholds" title="Choose by provability, not by job title." description="Select the closest route. The combination of income, assets, Thai investment, employer and sector determines whether collecting the full file is realistic." /><div className="mt-10 overflow-hidden rounded-[30px] border border-jade/10 bg-white shadow-editorial-lift"><div className="grid lg:grid-cols-[0.72fr_1.28fr]"><div className="bg-jade p-6 text-white sm:p-9"><p className="eyebrow !text-saffron-light">Compare LTR routes</p><div className="mt-6 grid gap-2">{ltrRoutes.map((item) => { const active = route === item.key; return <button key={item.key} type="button" aria-pressed={active} onClick={() => setRoute(item.key)} className={`flex min-h-[74px] items-center justify-between rounded-xl border px-4 py-3 text-left transition ${active ? 'border-saffron/60 bg-white text-jade' : 'border-white/12 bg-white/[0.05] text-white hover:bg-white/10'}`}><span><strong className="block text-sm">{item.label}</strong><span className={`mt-1 block text-[9px] leading-4 ${active ? 'text-jade/55' : 'text-white/45'}`}>{item.short} · {item.threshold}</span></span><ArrowRight size={16} className={active ? 'text-saffron' : 'text-white/40'} /></button>; })}</div><p className="mt-6 border-t border-white/12 pt-5 text-[10px] font-medium leading-5 text-white/55">This is a route check, not BOI approval, tax advice or financial advice. BOI applies its current exchange-rate method to USD thresholds.</p></div><div className="p-7 sm:p-10 lg:p-12" aria-live="polite"><p className="text-[9px] font-extrabold uppercase tracking-[0.15em] text-saffron-dark">{selected.short} · {selected.threshold}</p><h2 className="mt-3 max-w-3xl font-display text-[2.6rem] font-semibold leading-[0.94] tracking-[-0.035em] text-jade sm:text-[3.35rem]">{selected.title}</h2><p className="mt-5 max-w-3xl text-sm font-medium leading-7 text-charcoal/66">{selected.intro}</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{selected.proof.map((item, index) => <div key={item} className="flex items-start gap-3 rounded-xl border border-jade/10 bg-mist/45 p-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-jade font-display text-sm font-semibold text-white">{index + 1}</span><p className="text-[11px] font-extrabold leading-5 text-jade">{item}</p></div>)}</div><p className="mt-6 rounded-2xl border border-saffron/25 bg-canvas p-5 text-xs font-extrabold leading-6 text-jade">{selected.note}</p><a href={BOI_LTR} target="_blank" rel="noopener noreferrer" className="btn-jade mt-6">Start the official check <ExternalLink size={15} /></a></div></div></div></div></section>

      <section id="evidence" className="section-divider-bottom scroll-mt-24 py-16 lg:py-24"><div className="container-custom"><SectionHeading eyebrow="Four evidence streams, one duty to maintain them" title="The file does not end when the visa is issued." description="BOI requires the decisive conditions to remain true. The five-year review therefore returns to the route on which you qualified." /><div className="mt-10 overflow-hidden rounded-[30px] border border-jade/10 bg-white shadow-editorial-lift"><div className="grid lg:grid-cols-[1.12fr_0.88fr]"><div className="relative min-h-[390px] lg:min-h-[610px]"><Image src="/images/redesign/thailand-ltr-visa-routes.webp" alt="Four LTR evidence routes for wealth, pension income, remote work and specialist expertise" fill sizes="(max-width:1024px) 100vw,56vw" className="object-cover" /></div><div className="bg-jade p-7 text-white sm:p-10 lg:p-12"><p className="eyebrow !text-saffron-light">Maintain the evidence</p><h2 className="font-display text-[3.05rem] font-semibold leading-[0.9] tracking-[-0.035em]">One change can affect qualification.</h2><div className="mt-7 grid gap-3">{[
        ['Investment', 'A sale or reduced holding can take LTR-W or LTR-P below its threshold.'], ['Employer', 'A new employer must still satisfy the relevant LTR-T or LTR-H route.'], ['Health route', 'Insurance, social security or the qualifying deposit must remain demonstrable.'], ['Purpose', 'A change in work or residence purpose can trigger reporting or requalification issues.'],
      ].map(([label, text]) => <div key={label} className="rounded-xl border border-white/14 bg-white/[0.06] p-4"><div className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-saffron text-jade"><Check size={14} /></span><strong className="text-sm">{label}</strong></div><p className="mt-2 pl-10 text-[10px] font-medium leading-5 text-white/56">{text}</p></div>)}</div><a href={BOI_DOCUMENTS} target="_blank" rel="noopener noreferrer" className="btn-cream mt-7">Open current document lists <ExternalLink size={15} /></a></div></div></div></div></section>

      <section id="five-plus-five" className="section-divider-bottom scroll-mt-24 bg-mist py-16 lg:py-24"><div className="container-custom grid gap-10 lg:grid-cols-[0.7fr_1.3fr] lg:items-center"><SectionHeading eyebrow="Ten years is not a blank cheque" title="Two stay periods with a qualification review between them." description="The programme is designed for ten years, but the first permission to stay is no more than five years and can be shorter when the passport expires earlier." /><div className="rounded-[30px] bg-jade p-7 text-white shadow-editorial-lift sm:p-10"><div className="grid gap-4 sm:grid-cols-[1fr_auto_1fr]"><article className="rounded-2xl border border-white/14 bg-white/[0.06] p-6"><span className="text-[9px] font-extrabold uppercase tracking-[0.13em] text-saffron-light">First period</span><strong className="mt-4 block font-display text-4xl">Up to 5 years</strong><p className="mt-3 text-xs leading-6 text-white/58">Or until an earlier passport expiry.</p></article><div className="grid place-items-center"><span className="grid h-12 w-12 place-items-center rounded-full bg-saffron text-jade"><RefreshCw size={19} /></span></div><article className="rounded-2xl border border-white/14 bg-white/[0.06] p-6"><span className="text-[9px] font-extrabold uppercase tracking-[0.13em] text-saffron-light">After reassessment</span><strong className="mt-4 block font-display text-4xl">Up to 5 more</strong><p className="mt-3 text-xs leading-6 text-white/58">Only when the route conditions still qualify.</p></article></div><p className="mt-5 rounded-2xl border border-saffron/30 bg-saffron/10 p-5 text-xs font-extrabold leading-6">Keep source evidence throughout the programme and plan the review well before the first period ends.</p></div></div></section>

      <section id="benefits" className="section-divider-bottom scroll-mt-24 py-16 lg:py-24"><div className="container-custom"><SectionHeading eyebrow="Benefits with boundaries" title="Not every benefit applies identically to every route." description="BOI combines immigration, airport, reporting, work and tax facilities. Their application remains category- and fact-specific." /><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[
        { icon: CalendarClock, title: 'Annual reporting', text: 'LTR replaces ordinary 90-day reporting with annual reporting after a continuous year.' },
        { icon: PlaneTakeoff, title: 'Multiple entry', text: 'Multiple re-entry and fast-track at designated international airports.' },
        { icon: BriefcaseBusiness, title: 'Work route', text: 'Digital work permit for applicable Thai work, not LTR-T overseas remote work.' },
        { icon: Landmark, title: 'Tax treatment', text: 'BOI names 17% specifically for LTR-H; obtain advice on residence and income source.' },
      ].map((item) => { const Icon = item.icon; return <article key={item.title} className="rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card"><span className="grid h-12 w-12 place-items-center rounded-xl bg-jade text-white"><Icon size={20} /></span><h2 className="mt-5 font-display text-2xl font-semibold text-jade">{item.title}</h2><p className="mt-3 text-xs font-medium leading-6 text-charcoal/62">{item.text}</p></article>; })}</div><p className="mt-5 rounded-2xl border border-saffron/25 bg-tonal p-6 text-xs font-extrabold leading-6 text-jade">A visa guide cannot provide personal tax advice. Check current Thai law, tax residence, any treaty and the income source with a qualified adviser.</p></div></section>

      <section id="apply" className="section-divider-bottom scroll-mt-24 bg-tonal py-16 lg:py-24"><div className="container-custom"><SectionHeading eyebrow="BOI first, visa issuance second" title="Four stages and a firm 60-day window after endorsement." description="BOI assesses qualification. TIESC or the relevant Thai embassy then issues the actual visa at the locally applicable fee." /><div className="relative mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div className="pointer-events-none absolute left-[7%] right-[7%] top-8 hidden border-t-2 border-dotted border-saffron/55 xl:block" />{[
        { icon: Route, label: '01', title: 'Choose one route', text: 'Test every threshold and select the evidence route that fully matches.' },
        { icon: FileCheck2, label: '02', title: 'Request endorsement', text: 'Apply directly to BOI; there is no BOI qualification fee.' },
        { icon: CalendarClock, label: '03', title: 'Complete review', text: 'BOI states 20 working days from a complete document file.' },
        { icon: PlaneTakeoff, label: '04', title: 'Issue within 60 days', text: 'Use TIESC or the embassy/e-Visa channel and pay the local issuance fee.' },
      ].map((step) => { const Icon = step.icon; return <article key={step.title} className="relative rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card"><span className="relative z-10 grid h-12 w-12 place-items-center rounded-full border-4 border-tonal bg-jade text-white"><Icon size={19} /></span><p className="mt-5 text-[9px] font-extrabold uppercase tracking-[0.13em] text-saffron-dark">Step {step.label}</p><h2 className="mt-2 font-display text-2xl font-semibold leading-tight text-jade">{step.title}</h2><p className="mt-3 text-xs font-medium leading-5 text-charcoal/62">{step.text}</p></article>; })}</div><div className="mt-5 grid gap-4 lg:grid-cols-2"><a href={BOI_APPLICATION} target="_blank" rel="noopener noreferrer" className="flex items-center justify-between gap-4 rounded-2xl bg-jade p-6 text-white"><span><strong className="block text-sm">Apply directly to BOI</strong><span className="mt-1 block text-[10px] text-white/52">No endorsement fee</span></span><ExternalLink size={18} className="text-saffron-light" /></a><a href={LONDON_LTR} target="_blank" rel="noopener noreferrer" className="flex items-center justify-between gap-4 rounded-2xl border border-jade/12 bg-white p-6 text-jade"><span><strong className="block text-sm">London issuance route</strong><span className="mt-1 block text-[10px] text-charcoal/52">Use the BOI endorsement within 60 days</span></span><ExternalLink size={18} className="text-saffron-dark" /></a></div></div></section>

      <section className="section-divider-bottom py-16 lg:py-24"><div className="container-custom"><div className="overflow-hidden rounded-[30px] bg-jade text-white shadow-editorial-lift"><div className="grid lg:grid-cols-[0.82fr_1.18fr]"><div className="p-8 sm:p-11"><p className="eyebrow !text-saffron-light">After qualification, before a long lease</p><h2 className="font-display text-[3.05rem] font-semibold leading-[0.9] tracking-[-0.035em]">Test Bangkok as somewhere to live and work.</h2><p className="mt-5 text-sm font-medium leading-7 text-white/60">Use a flexible first month to test neighbourhood, commute, healthcare and daily routine before making a long commitment.</p><Link href="/best-hotels/bangkok/" className="btn-cream mt-7">Compare Bangkok areas <ArrowRight size={15} /></Link></div><div className="grid gap-3 bg-white/[0.055] p-7 sm:grid-cols-2 sm:p-10"><a href={hotelHref} target="_blank" rel="noopener noreferrer nofollow sponsored" className="rounded-2xl border border-white/14 bg-white/[0.07] p-5"><Home size={20} className="text-saffron-light" /><strong className="mt-4 block text-sm">Check current stays</strong><span className="mt-1 block text-[10px] text-white/50">Flexible first month via Trip.com</span></a><a href={esimHref} target="_blank" rel="noopener noreferrer nofollow sponsored" className="rounded-2xl border border-white/14 bg-white/[0.07] p-5"><Smartphone size={20} className="text-saffron-light" /><strong className="mt-4 block text-sm">Stay connected on arrival</strong><span className="mt-1 block text-[10px] text-white/50">Compare current eSIM options via Saily</span></a><AffiliateDisclosure className="sm:col-span-2 !border-white/12 !bg-white/[0.04] !text-white/55">Trip.com and Saily are affiliate links for practical arrival planning. They do not influence BOI qualification or visa issuance.</AffiliateDisclosure></div></div></div></div></section>

      <FaqSplitSection id="questions" eyebrow="Questions measured in UK search" title="Thailand LTR Visa questions, answered carefully" description="Answers combine the recurring UK People Also Ask themes with BOI’s current criteria and visibly flag old-versus-new official wording." items={faqs} />
      <RelatedGuidesSection eyebrow="Compare long-stay routes" title="Choose by qualification, not by the longest headline" guides={[
        { title: 'Thailand retirement visas', description: 'Compare Non-O, O-A and O-X if the LTR-P thresholds do not fit.', href: '/visa/retirement-visa/', image: '/images/redesign/thailand-retirement-visa-hero.webp', imageAlt: 'Planning a retirement route for Thailand' },
        { title: 'Destination Thailand Visa', description: 'Explore the five-year workcation route for remote work and soft power.', href: '/visa/digital-nomad-visa/', image: '/images/redesign/thailand-dtv-hero.webp', imageAlt: 'Remote working from Thailand' },
        { title: 'Thailand Privilege', description: 'Compare a paid membership route with strict BOI qualification.', href: '/visa/thailand-elite-visa/', image: '/images/redesign/thailand-privilege-hero.webp', imageAlt: 'Premium long-stay planning in Thailand' },
      ]} />
      <SourceMethodSection eyebrow="Sources & research" title="BOI criteria outweigh old agency articles." description="English DataForSEO research included four keyword clusters, ten live UK SERPs, 87 organic results, 50 verbatim People Also Ask questions, and exact ranking and backlink checks. Criteria, 2025 changes, 5+5-year structure, issuance and fees were then checked with BOI and the Royal Thai Embassy London." sources={[
        { title: 'LTR Visa Thailand · criteria and benefits', creator: 'Thailand Board of Investment', url: BOI_LTR, note: 'Primary source for the four routes, current income and investment thresholds, health route and programme benefits.' },
        { title: 'LTR 2025 criteria update', creator: 'Thailand Board of Investment · 2025 brochure', url: BOI_BROCHURE, note: 'Primary source for the updated LTR-W, employer and dependent criteria, 20 working days and 5+5-year structure.' },
        { title: 'LTR Visa issuance information', creator: 'Thailand Board of Investment', url: BOI_ISSUANCE, note: 'Primary source for the 60-day endorsement window, 50,000 THB TIESC issuance, reassessment and work-permit boundaries.' },
        { title: 'Visa fees', creator: 'Royal Thai Embassy London', url: LONDON_FEES, note: 'UK source currently listing £1,500 for a ten-year multiple-entry LTR visa; applicants should verify the live fee when applying.' },
      ]} />
    </div>
  </>;
}
