import Link from 'next/link';
import { ArrowRight, Check, ExternalLink, Gauge, Map, ShieldCheck } from 'lucide-react';
import SEOHead from '../SEOHead';
import { AffiliateDisclosure } from '../design/AffiliateDisclosure';
import { EditorialHero } from '../design/EditorialHero';
import { SectionHeading } from '../design/SectionHeading';
import { SourceMethodSection } from '../design/SourceMethodSection';
import { KLOOK_GENERIC, withPlacementSubId } from '../../lib/affiliates';

type Key = 'things'|'directory'|'index'|'budget'|'best-time'|'transport'|'nomad'|'guide'|'first-time'|'itinerary'|'weather'|'scooter';
type Config = { path:string; title:string; eyebrow:string; description:string; checks:string[]; links:Array<[string,string]>; sourceKeys:string[]; affiliate?:boolean };
const S = {
  immigration:{title:'Thailand Digital Arrival Card',creator:'Thailand Immigration Bureau',url:'https://tdac.immigration.go.th/manual/en/',note:'Official arrival-card workflow; confirm the current requirements before travel.'},
  visa:{title:'Thai e-Visa official portal',creator:'Ministry of Foreign Affairs, Thailand',url:'https://www.thaievisa.go.th/',note:'Official visa application starting point; rules depend on the individual traveller.'},
  weather:{title:'Thailand forecasts and warnings',creator:'Thai Meteorological Department',url:'https://www.tmd.go.th/en/',note:'Official daily, seasonal, warning and marine-weather products.'},
  health:{title:'Thailand traveler view',creator:'US Centers for Disease Control and Prevention',url:'https://wwwnc.cdc.gov/travel/destinations/traveler/none/thailand',note:'Current destination-health context; individual advice belongs with a clinician.'},
  rail:{title:'SRT D-Ticket',creator:'State Railway of Thailand',url:'https://www.dticket.railway.co.th/DTicketPublicWeb/home/Home',note:'Official rail availability and booking path; verify the actual service and conditions.'},
  tat:{title:'Thailand destination information',creator:'Tourism Authority of Thailand',url:'https://www.tourismthailand.org/',note:'Official destination orientation, not proof of live operator details or availability.'},
};
const C:Record<Key,Config>={
  things:{path:'things-to-do-in-thailand',title:'Things to Do in Thailand',eyebrow:'Choose by trip fit, not ranking',description:'A premium decision map for choosing Thailand experiences by route, conditions and responsible operator checks.',checks:['Start with regions already on your route','Match activity to weather and physical demands','Verify the named operator and actual inclusions','Keep a non-bookable fallback'],links:[['/activities/','Browse activity types'],['/best-places-to-visit-thailand/','Choose destinations'],['/is-thailand-safe/','Check safety context']],sourceKeys:['tat','weather'],affiliate:true},
  directory:{path:'travel-guides',title:'Thailand Travel Guides',eyebrow:'One clear owner per decision',description:'Find the strongest guide for planning, transport, weather, connectivity, culture and health without duplicate or stale advice.',checks:['Choose the decision, not the longest article','Prefer a dedicated route owner','Open the current authority for changing rules','Return to destination planning after the check'],links:[['/thailand-travel-guide/','Start planning'],['/thailand-index/','Open decision index'],['/travel-guides/thailand-weather/','Check weather']],sourceKeys:['tat','immigration','weather','health']},
  index:{path:'thailand-index',title:'Thailand Planning Index',eyebrow:'The shortest path to the right owner',description:'A decision-first index for Thailand routes, timing, budget, transport and longer stays.',checks:['Destination role before hotel','Season and coast before beach','Route chain before tickets','Live total before budget claim'],links:[['/thailand-index/best-time/','Best-time method'],['/thailand-index/budget/','Budget method'],['/thailand-index/transport/','Transport method']],sourceKeys:['tat','weather','rail']},
  budget:{path:'thailand-index/budget',title:'Thailand Trip Budget',eyebrow:'Build a live total',description:'Price the trip from current accommodation, transport and activity totals instead of frozen daily-budget bands.',checks:['Final accommodation total and taxes','Every long-distance leg and last mile','Activity inclusions and exclusions','Food, local travel and contingency'],links:[['/where-to-stay/','Choose where to stay'],['/transport/','Plan transport'],['/activities/','Compare activities']],sourceKeys:['tat']},
  'best-time':{path:'thailand-index/best-time',title:'Best Time to Visit Thailand',eyebrow:'Best depends on place and purpose',description:'Choose timing by coast, region, activity and tolerance, then check the actual forecast and warnings.',checks:['Select the exact coast or region','Separate climate pattern from forecast','Check marine conditions for boat days','Keep a weather-flexible alternative'],links:[['/travel-guides/thailand-weather/','Weather method'],['/best-places-to-visit-thailand/','Compare places'],['/thailand-itinerary/','Shape the route']],sourceKeys:['weather','tat']},
  transport:{path:'thailand-index/transport',title:'Thailand Transport Planner',eyebrow:'Plan the whole chain',description:'Compare route shape and connection risk before checking live schedules, operators and totals.',checks:['Exact terminal, pier or airport','Transfer and luggage conditions','Current operator and timetable','Arrival-time last-mile plan'],links:[['/transport/','Transport hub'],['/thailand-itinerary/','Route planner'],['/travel-insurance/','Insurance context']],sourceKeys:['rail','tat']},
  nomad:{path:'thailand-index/digital-nomad',title:'Thailand for Digital Nomads',eyebrow:'Legal status before lifestyle',description:'Plan a longer stay around current immigration, tax, work and insurance advice—not a café ranking or old visa summary.',checks:['Official status for your passport and work','Qualified tax advice for your facts','Internet backup and secure access','Accommodation and insurance totals'],links:[['/visa/','Visa guides'],['/travel-guides/sim-card-thailand/','Connectivity'],['/travel-insurance/','Insurance']],sourceKeys:['visa','immigration','health']},
  guide:{path:'thailand-travel-guide',title:'Thailand Travel Guide',eyebrow:'Build the trip in the right order',description:'A source-bound starting point for choosing places, timing, route shape and live booking checks.',checks:['Give every destination a purpose','Match route to season and coast','Limit expensive or fragile connections','Verify changing rules at the authority'],links:[['/best-places-to-visit-thailand/','Choose places'],['/thailand-itinerary/','Build itinerary'],['/travel-guides/','Open practical guides']],sourceKeys:['tat','immigration','weather','health']},
  'first-time':{path:'thailand-for-first-timers',title:'Thailand for First-Time Visitors',eyebrow:'Sequence the first decisions',description:'A first-trip framework without stale visa rules, exchange rates, fixed prices or blanket safety claims.',checks:['Passport-specific entry check','First and final night logistics','Payment and connectivity backup','Health and insurance advice for your trip'],links:[['/thailand-travel-guide/','Travel guide'],['/thailand-itinerary/','First itinerary'],['/travel-guides/sim-card-thailand/','Connectivity']],sourceKeys:['immigration','visa','health','weather']},
  itinerary:{path:'thailand-itinerary',title:'Thailand Itinerary Planner',eyebrow:'Fewer transfers, stronger trip',description:'Build a route from destination roles and connection friction, then verify every live leg.',checks:['Arrival and departure airports','Realistic transfer days','Weather-sensitive stops','One flexible recovery block'],links:[['/best-places-to-visit-thailand/','Choose destinations'],['/thailand-index/transport/','Plan connections'],['/where-to-stay/','Choose bases']],sourceKeys:['tat','weather','rail']},
  weather:{path:'travel-guides/thailand-weather',title:'Thailand Weather by Month',eyebrow:'Climate pattern is not a forecast',description:'Use regional patterns for timing, then check official daily, warning and marine products close to travel.',checks:['Exact province and coast','Daily forecast near departure','Warnings and marine conditions','Flexible indoor or inland fallback'],links:[['/thailand-index/best-time/','Best-time decisions'],['/thailand-itinerary/','Weather-aware route'],['/best-places-to-visit-thailand/','Compare regions']],sourceKeys:['weather','tat']},
  scooter:{path:'travel-guides/scooter-rental-thailand',title:'Scooter Rental in Thailand',eyebrow:'Licence, skill and cover first',description:'A risk-first scooter decision guide without cached rental prices, legal shortcuts or insurance guarantees.',checks:['Licence valid for the vehicle and location','Helmet and vehicle condition','Insurance exclusions in writing','Safer transport fallback'],links:[['/transport/','Transport alternatives'],['/travel-insurance/','Insurance context'],['/is-thailand-safe/','Safety planning']],sourceKeys:['tat','health']},
};

export function StaticTravelGuideOwnerEn({ owner }: { owner: Key }) {
  const c=C[owner], canonical=`https://go2-thailand.com/${c.path}/`;
  const schema={ '@context':'https://schema.org','@type':'Article',headline:c.title,description:c.description,url:canonical,inLanguage:'en-GB',dateModified:'2026-08-01',author:{'@type':'Organization',name:'Go2Thailand.com'},publisher:{'@type':'Organization',name:'Go2Thailand.com'} };
  return <div className="overflow-hidden bg-canvas text-charcoal" data-premium-template="static-travel-guide-owner-en" data-static-owner={owner}>
    <SEOHead title={c.title} description={c.description}><meta property="og:type" content="article"/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></SEOHead>
    <EditorialHero image="/images/redesign/how-long-thailand-trip-planner-hero-v2.webp" imageAlt="Thailand journey planning across cities, countryside and coast" breadcrumbs={[{label:'Thailand',href:'/'},{label:'Travel guides',href:'/travel-guides/'},{label:c.title}]} eyebrow={c.eyebrow} title={<>{c.title}</>} subtitle="Decision-first · source-bound · live-detail aware" description={c.description} actions={[{label:'Use the framework',href:'#framework',kind:'primary'},{label:'Verify sources',href:'#sources',kind:'secondary'}]} minHeightClassName="min-h-[760px] lg:min-h-[690px]" titleClassName="max-w-[850px] text-[4rem] leading-[.86] sm:text-[5.1rem] lg:text-[5.9rem]" contentTone="light" gradientClassName="bg-[linear-gradient(180deg,rgba(5,39,32,.12)_0%,rgba(5,39,32,.88)_62%,rgba(5,39,32,.98)_100%)] lg:bg-[linear-gradient(90deg,rgba(5,39,32,.98)_0%,rgba(5,39,32,.9)_45%,rgba(5,39,32,.15)_78%)]"/>
    <section id="framework" className="section-divider-bottom scroll-mt-24 py-14 lg:py-20"><div className="container-custom grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><SectionHeading eyebrow="Decision framework" title="Resolve four things before relying on an offer." description="Static articles are useful for orientation. Changing rules, schedules, prices, access, weather and provider terms must come from the responsible live source."/><div className="grid gap-4 sm:grid-cols-2">{c.checks.map((x,i)=><article key={x} className={`${i===0?'bg-jade text-white':'border border-jade/10 bg-white text-jade'} rounded-2xl p-7 shadow-editorial-card`}><Gauge className={i===0?'text-saffron-light':'text-jade'}/><span className={`mt-7 block text-[10px] font-black uppercase tracking-[.16em] ${i===0?'text-saffron-light':'text-saffron-dark'}`}>Check {i+1}</span><h2 className="mt-3 font-display text-[1.75rem] font-semibold leading-none">{x}</h2></article>)}</div></div></section>
    <section className="section-divider-bottom bg-tonal py-14 lg:py-20"><div className="container-custom grid gap-9 lg:grid-cols-[.7fr_1.3fr]"><SectionHeading eyebrow="Natural next steps" title="Continue with the strongest route owner." description="These links support the next planning decision; they are not inserted merely to increase link count."/><div className="grid gap-3 sm:grid-cols-3">{c.links.map(([href,label])=><Link key={href} href={href} className="rounded-xl border border-jade/10 bg-white p-6 shadow-editorial-card"><Map className="text-jade"/><strong className="mt-5 block font-display text-xl text-jade">{label}</strong><span className="mt-4 inline-flex items-center gap-2 text-xs font-extrabold text-jade">Open owner <ArrowRight size={13} className="text-saffron-dark"/></span></Link>)}</div></div></section>
    {c.affiliate?<section className="section-divider-bottom bg-jade py-14 text-white"><div className="container-custom grid gap-8 lg:grid-cols-[.72fr_1.28fr]"><div><p className="eyebrow !text-saffron-light">Only after the route fits</p><h2 className="font-display text-[3rem] font-semibold leading-[.92]">Check the actual experience.</h2><p className="mt-5 text-sm leading-7 text-white/68">A partner listing is a booking tool, not proof that an activity is best, suitable or available.</p></div><div><a href={withPlacementSubId(KLOOK_GENERIC,`en-${c.path}`,'static-guide')} target="_blank" rel="noopener noreferrer nofollow sponsored" className="block rounded-2xl bg-white p-7 text-jade"><ShieldCheck/><strong className="mt-5 block font-display text-2xl">Compare current activities</strong><span className="mt-5 inline-flex items-center gap-2 text-xs font-extrabold text-saffron-dark">Check Klook <ExternalLink size={13}/></span></a><AffiliateDisclosure className="mt-3 !text-white/60">Sponsored partner link. Verify the named operator, inclusions, total and cancellation terms.</AffiliateDisclosure></div></div></section>:null}
    <div id="sources"><SourceMethodSection eyebrow="Sources & method" title="Current facts stay with the responsible source." description="Reviewed 1 August 2026. No cached price, timetable, exchange rate, visa entitlement, forecast or safety guarantee is presented as current." method="The legacy English page was replaced at render time with a route-specific decision framework. The Dutch owner remains unchanged." sources={c.sourceKeys.map(k=>S[k as keyof typeof S])}/></div>
    <footer className="py-9"><div className="container-custom flex flex-wrap justify-between gap-4 text-[10px] font-medium text-charcoal/52"><span className="inline-flex items-center gap-2"><Check size={13} className="text-jade"/> Route owner reviewed 1 August 2026</span><span>Live details remain an authority or provider check</span></div></footer>
  </div>;
}
