export interface DutchDishProfile {
  lead: string;
  flavour: string;
  texture: string;
  orderTip: string;
  goodFor: string;
  watch: string;
  pairing: string;
  scores: {
    fris: number;
    hartig: number;
    pittig: number;
    romig: number;
  };
}

export const dutchDishProfiles: Record<string, DutchDishProfile> = {
  'pad-krapow': {
    lead: 'Een snel wokgerecht waarin knoflook, chili en Thaise basilicum de toon zetten. Het wordt vaak met rijst geserveerd; vlees, tofu en de hoeveelheid saus verschillen per keuken.',
    flavour: 'Kruidig, hartig en direct. De basilicum geeft een peperige geur die anders is dan Italiaanse basilicum.',
    texture: 'Losgebakken vulling, zachte rijst en eventueel een krokant randje aan een gebakken ei.',
    orderTip: 'Vraag welke proteïne wordt gebruikt en zeg vooraf hoeveel chili je wilt. “Mai phet” helpt, maar is geen garantie voor nul chili.',
    goodFor: 'Een snelle, hartige maaltijd met veel wokaroma.',
    watch: 'Oestersaus, vissaus en bouillon kunnen dierlijke ingrediënten of allergenen bevatten.',
    pairing: 'Bestel er rijst en eventueel een gebakken ei bij; proef vóór je extra chili toevoegt.',
    scores: { fris: 1, hartig: 5, pittig: 4, romig: 1 },
  },
  'som-tam': {
    lead: 'Som tam is een salade van fijngesneden groene papaja die in een vijzel wordt gemengd. De balans tussen zuur, zout, zoet en chili wordt per bestelling aangepast.',
    flavour: 'Friszuur en pittig, met zoet en hartig op de achtergrond.',
    texture: 'Knapperige papaja, zachte tomaat en vaak pinda of kousenband voor extra beet.',
    orderTip: 'Noem het aantal chilipepers en vraag welke variant je krijgt. Som tam Thai en varianten met gefermenteerde vis of krab zijn niet hetzelfde.',
    goodFor: 'Wie van frisse, pittige gerechten en veel textuur houdt.',
    watch: 'Vissaus, gedroogde garnaal, pinda, gefermenteerde vis en krab kunnen voorkomen.',
    pairing: 'Eet hem zoals lokaal gebruikelijk naast kleefrijst en een milder gerecht, niet alleen als westerse bijsalade.',
    scores: { fris: 5, hartig: 3, pittig: 4, romig: 1 },
  },
  'tom-yum-goong': {
    lead: 'Een aromatische garnalensoep waarin citroengras, galanga en makrut-limoenblad samenkomen. Er bestaan heldere en romigere uitvoeringen, dus de kom op tafel kan flink verschillen.',
    flavour: 'Uitgesproken zuur en pittig, met een kruidige citrusgeur en hartige bouillon.',
    texture: 'Lichte of romige bouillon met stevige garnalen en aromaten die niet altijd bedoeld zijn om op te eten.',
    orderTip: 'Vraag naar nam sai voor een heldere versie of controleer of de keuken een romige variant serveert. Spreek ook de gewenste scherpte af.',
    goodFor: 'Wie een krachtige, geurige soep zoekt en zuur lekker vindt.',
    watch: 'Schaaldieren, vissaus, melkproducten of verdampte melk kunnen aanwezig zijn, afhankelijk van de versie.',
    pairing: 'Deel de soep en bestel rijst; die maakt een scherpe of zoute kom beter doseerbaar.',
    scores: { fris: 5, hartig: 4, pittig: 4, romig: 2 },
  },
  'pad-thai': {
    lead: 'Pad Thai is een wokgerecht met rijstnoedels, een zoetzure saus en knapperige garnituren. Tofu, ei, taugé en een proteïne komen vaak voor, maar er bestaat geen universele restaurantversie.',
    flavour: 'Zoetzuur en hartig, vaak met tamarinde als zure basis en limoen aan tafel.',
    texture: 'Zachte, veerkrachtige noedels met taugé en pinda voor contrast.',
    orderTip: 'Vraag naar de proteïne en saus als je vegetarisch eet of allergieën hebt. Voeg limoen, chili en suiker pas toe nadat je hebt geproefd.',
    goodFor: 'Een toegankelijke eerste kennismaking met Thaise noedelgerechten.',
    watch: 'Pinda, ei, soja, vissaus, schaaldieren en gedroogde garnaal kunnen in gerecht of saus zitten.',
    pairing: 'Eet het direct uit de wok; pad Thai verliest snel zijn beste textuur wanneer het lang staat.',
    scores: { fris: 3, hartig: 4, pittig: 1, romig: 1 },
  },
  'green-curry': {
    lead: 'Groene curry combineert een groene currypasta met kokosmelk, groenten en een gekozen proteïne. De kleur zegt weinig over de exacte scherpte: die hangt af van pasta, chili en keuken.',
    flavour: 'Kruidig, aromatisch en romig, met zoete basilicumachtige en citrusachtige tonen.',
    texture: 'Een dunne, geurende kokoscurry met zachte groenten en vlees, vis of tofu.',
    orderTip: 'Vraag welke currypasta en bouillon worden gebruikt. Een groentecurry is niet automatisch vegetarisch.',
    goodFor: 'Wie romigheid wil zonder een vlak of zwaar smaakprofiel.',
    watch: 'Garnalenpasta, vissaus, kokos en een niet-zichtbare vleesbouillon kunnen voorkomen.',
    pairing: 'Bestel gestoomde rijst apart en schep telkens een beetje curry over de rijst.',
    scores: { fris: 2, hartig: 4, pittig: 4, romig: 5 },
  },
  'mango-sticky-rice': {
    lead: 'Rijpe mango, kleefrijst en gekruide kokosmelk vormen samen een eenvoudig dessert met veel contrast. De mango is seizoensgevoelig en de rijst hoort kleverig, niet papperig, te zijn.',
    flavour: 'Zoet en kokosachtig, met een klein zout accent dat het dessert in balans brengt.',
    texture: 'Sappige mango naast warme of lauwwarme kleefrijst en romige kokossaus.',
    orderTip: 'Vraag of het vers wordt samengesteld en controleer bij allergieën welke topping wordt gebruikt.',
    goodFor: 'Wie een fruitig dessert wil dat vullender is dan alleen vers fruit.',
    watch: 'Kokos, sesam, mungboon of andere krokante toppings kunnen per verkoper verschillen.',
    pairing: 'Deel één portie na een maaltijd; kleefrijst maakt dit dessert behoorlijk vullend.',
    scores: { fris: 3, hartig: 1, pittig: 0, romig: 4 },
  },
  'massaman-curry': {
    lead: 'Massaman is een langzaam opgebouwde curry met kokosmelk, warme specerijen en vaak aardappel, pinda en vlees. De saus is doorgaans milder dan bij veel groene of zuidelijke curries.',
    flavour: 'Rijk, mild-pittig en licht zoetzuur, met specerijen die aan stoofgerechten doen denken.',
    texture: 'Dikke saus, zachte aardappel en langzaam gegaarde proteïne.',
    orderTip: 'Controleer welke proteïne, noten en currypasta worden gebruikt; vegetarische versies vragen meer dan alleen vlees weglaten.',
    goodFor: 'Wie een milde, volle curry zoekt en van warme specerijen houdt.',
    watch: 'Pinda, kokos, vissaus, garnalenpasta en vleesbouillon kunnen voorkomen.',
    pairing: 'Combineer met gestoomde rijst en een fris of zuur bijgerecht voor contrast.',
    scores: { fris: 2, hartig: 4, pittig: 2, romig: 5 },
  },
  'larb': {
    lead: 'Larb is een kruidige salade van fijngehakt vlees of een alternatief, op smaak gebracht met limoen, chili, kruiden en vaak geroosterd rijstpoeder. De Isaan-versie is fris en droog, niet romig.',
    flavour: 'Zuur, kruidig, hartig en pittig met een geroosterd accent.',
    texture: 'Los gehakt, verse kruiden en een licht korrelige beet van geroosterde rijst.',
    orderTip: 'Vraag welke proteïne wordt gebruikt en of het volledig gaar is. Spreek het aantal chilipepers af.',
    goodFor: 'Wie een fris, eiwitrijk deelgerecht zonder kokossaus zoekt.',
    watch: 'Vissaus, geroosterd rijstpoeder, orgaanvlees of rauwere bereidingen kunnen per variant voorkomen.',
    pairing: 'Eet met kleefrijst, rauwe groenten en andere Isaan-gerechten om de scherpte te verdelen.',
    scores: { fris: 4, hartig: 4, pittig: 4, romig: 0 },
  },
  'pad-see-ew': {
    lead: 'Brede rijstnoedels worden op hoge hitte gewokt met donkere sojasaus, ei en Chinese broccoli. Het gerecht draait meer om rook, zout en zoet dan om chili.',
    flavour: 'Hartig en licht zoet, met geroosterde woktonen.',
    texture: 'Zachte brede noedels, knapperige groentestelen en soms gekaramelliseerde randjes.',
    orderTip: 'Kies je proteïne en vraag bij vegetarisch eten naar vissaus, oestersaus en de wok waarin wordt gebakken.',
    goodFor: 'Wie een mild noedelgerecht met veel wokaroma wil.',
    watch: 'Soja, ei, gluten in sommige sauzen en oestersaus kunnen voorkomen.',
    pairing: 'Proef eerst; chili-azijn aan tafel geeft zuur en pit zonder het hele gerecht te veranderen.',
    scores: { fris: 1, hartig: 5, pittig: 1, romig: 0 },
  },
  'thai-fried-rice': {
    lead: 'Thaise gebakken rijst is een snelle wokmaaltijd met losse rijst, ei, knoflook en een gekozen vulling. De smaak is meestal subtieler dan bij sterk gesausde noedelgerechten.',
    flavour: 'Hartig en mild, vaak opgefrist met limoen, komkommer en vissaus met chili.',
    texture: 'Losse rijstkorrels met zachte ei- en groentestukjes.',
    orderTip: 'Noem de gewenste vulling en vraag wat in de saus of bouillon zit wanneer je vegetarisch of allergisch eet.',
    goodFor: 'Een rustige, herkenbare maaltijd of tegenhanger voor pittige deelgerechten.',
    watch: 'Ei, vissaus, soja, schaaldieren en gedeelde wokoppervlakken kunnen relevant zijn.',
    pairing: 'Gebruik de limoen en prik nam pla voorzichtig; beide kunnen de balans snel veranderen.',
    scores: { fris: 2, hartig: 4, pittig: 1, romig: 0 },
  },
  'khao-man-gai': {
    lead: 'Khao man gai combineert zacht gepocheerde kip met geurige rijst, saus en een heldere bouillon. Het lijkt eenvoudig, maar de rijst en gembersaus bepalen het karakter.',
    flavour: 'Mild en hartig, met pittige, zoute of zure accenten uit de saus.',
    texture: 'Malse kip, zachte maar losse rijst en frisse komkommer.',
    orderTip: 'Vraag naar gekookte of gefrituurde kip en doseer de saus zelf als je zout of chili wilt beperken.',
    goodFor: 'Wie een milde, complete rijstmaaltijd zoekt.',
    watch: 'Soja, kippenbouillon en gedeelde snijplanken zijn relevant voor allergieën of vegetarische wensen.',
    pairing: 'Eet de bouillon ernaast en gebruik de saus in kleine beetjes.',
    scores: { fris: 2, hartig: 4, pittig: 1, romig: 1 },
  },
  'boat-noodles': {
    lead: 'Boat noodles zijn kleine, intens smakende noedelkommen met een donkere bouillon en vlees. Traditionele recepten kunnen bloed gebruiken voor kleur en binding; moderne versies verschillen.',
    flavour: 'Diep hartig, kruidig en soms zoet-pittig.',
    texture: 'Noedels, vlees, kruiden en een geconcentreerde bouillon in een compacte kom.',
    orderTip: 'Kies noedelsoort en proteïne en vraag expliciet naar bloed of orgaanvlees als je dat niet wilt.',
    goodFor: 'Wie meerdere kleine kommen en krachtige bouillon wil proberen.',
    watch: 'Bloed, orgaanvlees, soja, vissaus, pinda en gedeelde kookpotten kunnen voorkomen.',
    pairing: 'Begin met één kom voordat je meerdere varianten bestelt; de smaak is geconcentreerd.',
    scores: { fris: 1, hartig: 5, pittig: 3, romig: 1 },
  },
  'khao-soi': {
    lead: 'Khao soi is een Noord-Thaise noedelsoep met een kokoscurry, zachte eiernoedels en een krokante noedeltopping. Limoen, ingelegde groenten en sjalot brengen de rijke kom in balans.',
    flavour: 'Romig, kruidig en hartig, met zuur en frisheid uit de garnituren.',
    texture: 'Zachte noedels en vlees of tofu onder een krokante bovenlaag.',
    orderTip: 'Vraag welke proteïne, bouillon en currypasta worden gebruikt. Voeg ingelegde groente en limoen stap voor stap toe.',
    goodFor: 'Wie een vullende noedelsoep met veel textuur zoekt.',
    watch: 'Gluten, ei, kokos, vissaus, garnalenpasta en vleesbouillon kunnen voorkomen.',
    pairing: 'Khao soi is meestal een volledige maaltijd; bestel lichte bijgerechten in plaats van nog een zware curry.',
    scores: { fris: 2, hartig: 4, pittig: 3, romig: 5 },
  },
  'sai-ua': {
    lead: 'Sai ua is een Noord-Thaise worst waarin varkensvlees wordt gemengd met kruiden en specerijen. Dunne plakjes laten de geur van citroengras en makrut-limoenblad goed uitkomen.',
    flavour: 'Kruidig, hartig en vaak pittig met duidelijke citrusaroma’s.',
    texture: 'Stevige, sappige worst met fijngehakte kruiden.',
    orderTip: 'Vraag of de worst warm en door en door verhit is en welke kruiden of vulmiddelen zijn gebruikt.',
    goodFor: 'Wie een geurige snack of deelgerecht met vlees zoekt.',
    watch: 'Varkensvlees, gluten of soja in bindmiddelen en veel chili kunnen voorkomen.',
    pairing: 'Combineer met kleefrijst, rauwe groenten of nam prik noom.',
    scores: { fris: 2, hartig: 5, pittig: 4, romig: 0 },
  },
  'nam-prik-ong': {
    lead: 'Deze Noord-Thaise dip combineert tomaat en varkensgehakt met chili en aromaten. Hij komt meestal met groenten en soms krokante varkenshuid op tafel.',
    flavour: 'Hartig, tomatig en mild tot pittig.',
    texture: 'Een grove, warme dip naast knapperige of geblancheerde groenten.',
    orderTip: 'Vraag wat bij de set inbegrepen is en of er varkensvlees, bouillon of garnalenpasta in zit.',
    goodFor: 'Wie graag deelt en verschillende groenten met één dip proeft.',
    watch: 'Varkensvlees, garnalenpasta, vissaus en gedeeld servies kunnen relevant zijn.',
    pairing: 'Neem kleine hoeveelheden dip per hap; de groente hoort deel van het gerecht te zijn.',
    scores: { fris: 2, hartig: 4, pittig: 3, romig: 1 },
  },
  'gaeng-hang-lay': {
    lead: 'Gaeng hang lay is een Noord-Thaise varkenscurry die langzaam wordt gestoofd met specerijen, knoflook en vaak gember of tamarinde. Kokosmelk is doorgaans niet de hoofdrolspeler.',
    flavour: 'Warm gekruid, hartig en licht zoetzuur.',
    texture: 'Zacht gestoofd varkensvlees in een dikke, glanzende saus.',
    orderTip: 'Vraag welk stuk varkensvlees wordt gebruikt en hoe pittig de huisversie is.',
    goodFor: 'Wie stoofvlees en specerijen verkiest boven een romige kokoscurry.',
    watch: 'Varkensvlees, vissaus en veel vet kunnen deel van het recept zijn.',
    pairing: 'Eet met rijst en een groente- of kruidengerecht voor fris contrast.',
    scores: { fris: 2, hartig: 5, pittig: 2, romig: 1 },
  },
  'mee-hokkien': {
    lead: 'Mee Hokkien in Zuid-Thailand en Phuket verwijst naar gele noedels met Chinese invloeden. Ze kunnen droog gewokt of met meer saus worden geserveerd, vaak met zeevruchten.',
    flavour: 'Hartig en geroosterd, met zoete of peperige accenten per keuken.',
    texture: 'Stevige gele noedels met zachte zeevruchten en knapperige groenten.',
    orderTip: 'Vraag of de versie droog of nat is en welke zeevruchten, bouillon en sauzen erin gaan.',
    goodFor: 'Wie lokale Phuket-smaken en Chinese kookinvloeden wil vergelijken.',
    watch: 'Gluten, ei, soja, weekdieren, schaaldieren en oestersaus kunnen voorkomen.',
    pairing: 'Proef eerst voordat je chili, azijn of suiker uit het kruidenrek toevoegt.',
    scores: { fris: 1, hartig: 5, pittig: 1, romig: 1 },
  },
  'oh-aew': {
    lead: 'Oh aew is een verkoelend Phuket-dessert met een zachte gelei, schaafijs en siroop. Verkopers kunnen fruit, bonen of andere toppings toevoegen.',
    flavour: 'Lichtzoet en verfrissend, waarbij siroop en topping de intensiteit bepalen.',
    texture: 'Trillende gelei, smeltend ijs en eventueel extra beet van toppings.',
    orderTip: 'Vraag welke toppings en siroop worden gebruikt als je allergieën hebt of minder zoet wilt.',
    goodFor: 'Een lichte, koude pauze tijdens een warme wandeling door Phuket Old Town.',
    watch: 'Kleurstoffen, siroop, bonen, zaden of gedeelde lepels kunnen per kraam verschillen.',
    pairing: 'Eet het meteen; smeltend ijs verandert smaak en textuur snel.',
    scores: { fris: 5, hartig: 0, pittig: 0, romig: 1 },
  },
  'nam-prik-goong-siap': {
    lead: 'Een Zuid-Thaise chilidip met gedroogde garnaal, chili en knoflook. De dip wordt meestal in kleine hoeveelheden gegeten met groenten en rijst.',
    flavour: 'Zout, pittig en umamirijk met een duidelijke smaak van gedroogde garnaal.',
    texture: 'Grove dip met krokante of stevige stukjes garnaal.',
    orderTip: 'Vraag hoe pittig en zout de huisversie is en welke groenten erbij komen.',
    goodFor: 'Wie krachtige smaken graag over meerdere happen doseert.',
    watch: 'Schaaldieren, vissaus en garnalenpasta zijn voor allergieën een belangrijk aandachtspunt.',
    pairing: 'Gebruik de rauwe of geblancheerde groenten om de intensiteit te balanceren.',
    scores: { fris: 2, hartig: 5, pittig: 5, romig: 0 },
  },
  'moo-hong': {
    lead: 'Moo hong is een langzaam gestoofd varkensgerecht uit de Phuket- en Peranakan-eetcultuur. Sojasaus, suiker en specerijen bouwen een donkere, rijke saus op.',
    flavour: 'Zoet-hartig, peperig en warm gekruid.',
    texture: 'Zeer zacht varkensbuikvlees in een kleverige stoofsaus.',
    orderTip: 'Vraag welk stuk vlees wordt gebruikt en bestel rijst om de geconcentreerde saus te verdelen.',
    goodFor: 'Wie van rijk stoofvlees en zachte texturen houdt.',
    watch: 'Varkensvlees, soja, gluten en een hoog vetgehalte kunnen relevant zijn.',
    pairing: 'Combineer met rijst en een frisser groentegerecht.',
    scores: { fris: 1, hartig: 5, pittig: 1, romig: 2 },
  },
  'kanom-jeen-nam-ya': {
    lead: 'Zachte gefermenteerde rijstnoedels worden geserveerd met een kruidige vissaus of viscurry en een tafel vol groenten. De saus bepaalt of de kom mild, romig of scherp uitvalt.',
    flavour: 'Kruidig, hartig en vaak pittig, met frisse groente ernaast.',
    texture: 'Fijne noedels, dikke saus en veel knapperige of ingelegde toppings.',
    orderTip: 'Wijs de gewenste saus aan en vraag naar vis, kokos, garnalenpasta en pittigheid.',
    goodFor: 'Wie graag zelf een kom samenstelt en regionale sauzen vergelijkt.',
    watch: 'Vis, schaaldieren, kokos en gefermenteerde ingrediënten kunnen voorkomen.',
    pairing: 'Voeg groenten in rondes toe zodat je de saus eerst kunt beoordelen.',
    scores: { fris: 3, hartig: 5, pittig: 4, romig: 3 },
  },
  'hoy-tod': {
    lead: 'Hoy tod is een krokant gebakken beslaggerecht met mosselen of oesters, ei en taugé. Sommige versies zijn dun en knapperig, andere zachter en omeletachtig.',
    flavour: 'Hartig en geroosterd, met zoet-pittige chilisaus als contrast.',
    texture: 'Krokante randen, zacht beslag, sappige schelpdieren en knapperige taugé.',
    orderTip: 'Vraag of mosselen of oesters worden gebruikt en of de plaat ook voor andere allergenen dient.',
    goodFor: 'Wie streetfood met uitgesproken baktextuur zoekt.',
    watch: 'Weekdieren, ei, gluten, soja en kruiscontact op de bakplaat zijn belangrijk.',
    pairing: 'Eet direct uit de pan; de krokante laag wordt snel zacht.',
    scores: { fris: 1, hartig: 5, pittig: 1, romig: 1 },
  },
  'pla-pao': {
    lead: 'Pla pao is een hele vis die met een zoutkorst wordt gegrild, vaak met citroengras in de buik. Je haalt het zachte vlees zelf van de graat en combineert het met saus en groenten.',
    flavour: 'Mild en rokerig, met pittige, zure saus aan tafel.',
    texture: 'Sappig visvlees onder een droge zoutkorst; de korst eet je doorgaans niet.',
    orderTip: 'Vraag welke vis wordt gebruikt, of hij vers is gegrild en welke saus erbij hoort.',
    goodFor: 'Twee of meer eters die een vis willen delen.',
    watch: 'Visgraten, vissaus, schaaldieren in saus en gedeelde grilloppervlakken vragen aandacht.',
    pairing: 'Bestel rijst en groente; verwijder de huid met zoutkorst voordat je het vlees verdeelt.',
    scores: { fris: 2, hartig: 4, pittig: 2, romig: 0 },
  },
  'yam-woon-sen': {
    lead: 'Yam woon sen is een lauwwarme of koele salade van glasnoedels met een zure, pittige dressing. Garnalen, varkensgehakt, selderij en tomaat komen vaak voor, maar de mix varieert.',
    flavour: 'Friszuur, zout en pittig.',
    texture: 'Veerkrachtige glasnoedels met zachte proteïne en knapperige groenten.',
    orderTip: 'Vraag naar alle proteïnen in de schaal en geef het gewenste chiliniveau vooraf door.',
    goodFor: 'Wie een lichter noedelgerecht met veel zuur en kruiden wil.',
    watch: 'Schaaldieren, varkensvlees, vissaus en pinda kunnen voorkomen.',
    pairing: 'Deel met rijst en een milder gerecht als de dressing scherp uitvalt.',
    scores: { fris: 5, hartig: 3, pittig: 4, romig: 0 },
  },
  'khao-pad-sapparot': {
    lead: 'Khao pad sapparot is gebakken rijst met ananas en vaak garnalen of kip. De presentatie in een ananas komt voor, maar zegt niets over de kwaliteit van de wokbereiding.',
    flavour: 'Zoet-hartig met fruitig zuur en milde specerijen.',
    texture: 'Losse rijst, sappige ananas en zachte proteïne; soms met noten voor beet.',
    orderTip: 'Vraag naar proteïne, noten en saus en kies een vers gewokte portie.',
    goodFor: 'Wie een mild rijstgerecht met zoet fruitcontrast wil.',
    watch: 'Schaaldieren, ei, noten, soja en vissaus kunnen voorkomen.',
    pairing: 'Voeg limoen of chili pas na het proeven toe; ananas brengt al zoet en zuur.',
    scores: { fris: 3, hartig: 3, pittig: 1, romig: 0 },
  },
  'roti-sai-mai': {
    lead: 'Roti sai mai is een Ayutthaya-specialiteit van flinterdunne roti met gekleurde suikerdraden. Je rolt zelf een kleine hoeveelheid vulling in het velletje.',
    flavour: 'Duidelijk zoet, met een licht geroosterde smaak van de roti.',
    texture: 'Zachte, dunne pannenkoekjes rond luchtige, vezelige suiker.',
    orderTip: 'Koop een hoeveelheid die je dezelfde dag kunt eten en vraag naar kleur- en smaakstoffen bij gevoeligheden.',
    goodFor: 'Wie een lokale zoete snack wil delen tijdens een bezoek aan Ayutthaya.',
    watch: 'Gluten, kleurstoffen en gedeelde werkoppervlakken kunnen voorkomen.',
    pairing: 'Gebruik weinig suikerdraden per rol; zo blijft de verhouding met de roti prettig.',
    scores: { fris: 0, hartig: 0, pittig: 0, romig: 1 },
  },
  'tom-yum-noodles': {
    lead: 'Tom yum-noedels brengen het zure en pittige smaakprofiel van tom yum naar een noedelkom. Bouillon, droge versie, noedelsoort en toppings verschillen per kraam.',
    flavour: 'Zuur, pittig en hartig met pinda of limoen als mogelijke accenten.',
    texture: 'Noedels en verschillende toppings in een lichte bouillon of bijna droge saus.',
    orderTip: 'Kies noedels en toppings en vraag of pinda, visballen of orgaanvlees worden toegevoegd.',
    goodFor: 'Wie tom yum wil proberen als snelle, vullende eenkomsmaaltijd.',
    watch: 'Pinda, vis, schaaldieren, soja en meerdere soorten vlees kunnen voorkomen.',
    pairing: 'Proef de bouillon vóór je het volledige kruidenrek gebruikt.',
    scores: { fris: 4, hartig: 4, pittig: 4, romig: 1 },
  },
  'khao-mok-gai': {
    lead: 'Khao mok gai is een Zuid-Thaise moslimrijstschotel met gekruide kip en geelgekleurde rijst. Een frisse groene saus en komkommer zorgen voor contrast.',
    flavour: 'Warm gekruid en hartig, meestal niet extreem pittig.',
    texture: 'Losse gekruide rijst met malse kip en frisse garnituur.',
    orderTip: 'Vraag welke kipdelen en sauzen worden geserveerd en doseer de groene saus zelf.',
    goodFor: 'Wie aromatische rijst en milde specerijen verkiest boven een scherpe curry.',
    watch: 'Kippenbouillon, zuivel in sommige marinades en kruidenmixen kunnen relevant zijn.',
    pairing: 'Eet met komkommer en saus in kleine beetjes om de rijst centraal te houden.',
    scores: { fris: 2, hartig: 4, pittig: 2, romig: 1 },
  },
  'goong-pad-makham': {
    lead: 'Garnalen worden kort gebakken in een saus van tamarinde en palmsuiker. Een goede versie houdt de saus glanzend en de garnalen stevig.',
    flavour: 'Zoetzuur en hartig, met tamarinde als herkenbaar accent.',
    texture: 'Stevige garnalen met een kleverige saus en soms krokante sjalot.',
    orderTip: 'Vraag of de garnalen gepeld zijn en welke vis- of oestersaus wordt gebruikt.',
    goodFor: 'Wie zeevruchten en een toegankelijke zoetzure saus wil.',
    watch: 'Schaaldieren, vissaus, oestersaus en veel suiker kunnen voorkomen.',
    pairing: 'Bestel rijst om de saus te verdelen en combineer met een minder zoet groentegerecht.',
    scores: { fris: 4, hartig: 3, pittig: 1, romig: 0 },
  },
  'tom-som-pla': {
    lead: 'Tom som pla is een zure vissoep uit Zuid-Thailand. Tamarinde en aromaten geven de bouillon frisheid; kurkuma kan kleur en een aardse toon toevoegen.',
    flavour: 'Zuur, hartig en kruidig, soms met duidelijke chiliwarmte.',
    texture: 'Lichte bouillon met stukken vis en zachte aromaten.',
    orderTip: 'Vraag welke vis wordt gebruikt, hoe scherp de soep is en of er graten in de portie zitten.',
    goodFor: 'Wie een lichte, zure soep verkiest boven kokosrijke curry.',
    watch: 'Visgraten, vissaus, garnalenpasta en chili kunnen voorkomen.',
    pairing: 'Eet met rijst en schep voorzichtig rond eventuele graten.',
    scores: { fris: 5, hartig: 4, pittig: 3, romig: 0 },
  },
  'gai-tod-hat-yai': {
    lead: 'Hat Yai fried chicken is gekruide gefrituurde kip, vaak afgewerkt met krokante sjalot. Kleefrijst en chilisaus maken er een praktische Zuid-Thaise maaltijd van.',
    flavour: 'Hartig, kruidig en geroosterd, met zoet-pittige saus ernaast.',
    texture: 'Krokante buitenkant, sappige kip en knisperende sjalot.',
    orderTip: 'Kies een vers gebakken stuk en vraag naar bot, marinademiddelen en gebruikte frituurolie.',
    goodFor: 'Wie een draagbare snack of eenvoudige maaltijd zoekt.',
    watch: 'Gluten, soja, gedeelde frituurolie en kip met bot kunnen voorkomen.',
    pairing: 'Eet met kleefrijst en komkommer; gebruik saus als accent.',
    scores: { fris: 1, hartig: 5, pittig: 2, romig: 0 },
  },
  'khao-yam': {
    lead: 'Khao yam is een Zuid-Thaise rijstsalade met fijngesneden kruiden, groenten, kokos en een donkere dressing. Je mengt de onderdelen pas vlak voor het eten.',
    flavour: 'Fris, kruidig, hartig en soms licht zoet of pittig.',
    texture: 'Losse rijst met veel knapperige, vezelige en geroosterde toppings.',
    orderTip: 'Vraag wat in de dressing zit; budu of een andere vissausachtige basis kan bepalend zijn.',
    goodFor: 'Wie veel kruiden, groenten en texturen in één kom wil.',
    watch: 'Vis, schaaldieren, kokos, pinda en gedroogde ingrediënten kunnen voorkomen.',
    pairing: 'Meng eerst een deel van de dressing; toevoegen kan altijd, terugdraaien niet.',
    scores: { fris: 5, hartig: 4, pittig: 2, romig: 0 },
  },
  'nam-ngiao': {
    lead: 'Nam ngiao is een Noord-Thaise noedelsoep met tomaat, varkensvlees en een donkere, kruidige bouillon. Sommige traditionele versies bevatten bloedblokjes of bloed als ingrediënt.',
    flavour: 'Hartig, tomatig, zuur en mild tot pittig.',
    texture: 'Zachte rijstnoedels met vlees, tomaat en knapperige garnituren.',
    orderTip: 'Vraag expliciet naar bloed, orgaanvlees en het gekozen varkensdeel als je die ingrediënten wilt vermijden.',
    goodFor: 'Wie regionale Noord-Thaise noedelsoepen verder wil verkennen.',
    watch: 'Varkensvlees, bloed, vissaus, bouillon en gedeelde potten kunnen voorkomen.',
    pairing: 'Voeg ingelegde groente, limoen of chili stap voor stap toe.',
    scores: { fris: 3, hartig: 5, pittig: 3, romig: 1 },
  },
  'laab-kua': {
    lead: 'Laab kua is de gebakken Noord-Thaise tegenhanger van frissere Isaan-larb. Gedroogde specerijen en kruiden geven het gehakt een donker, warm karakter.',
    flavour: 'Hartig, kruidig en pittig, met minder nadruk op limoen.',
    texture: 'Drooggebakken gehakt met fijne kruiden en geroosterde specerijen.',
    orderTip: 'Vraag naar de proteïne, garing en pittigheid; de kruidenmix is vaak huisgebonden.',
    goodFor: 'Wie een intense, droge vleessalade met specerijen wil.',
    watch: 'Orgaanvlees, bloed, vissaus en sterke chili kunnen per recept voorkomen.',
    pairing: 'Combineer met kleefrijst, rauwe groenten en een mildere Noord-Thaise dip.',
    scores: { fris: 1, hartig: 5, pittig: 4, romig: 0 },
  },
  'tam-khanun': {
    lead: 'Tam khanun is een Noord-Thaise bereiding van jonge jackfruit die wordt gestampt en gebakken met kruiden. Varkensvlees of kaantjes kunnen onderdeel van de huisversie zijn.',
    flavour: 'Hartig, kruidig en aards, met milde tot stevige chiliwarmte.',
    texture: 'Vezelige jackfruit met een grove, bijna saladeachtige structuur.',
    orderTip: 'Vraag of vlees, kaantjes, garnalenpasta of vissaus wordt gebruikt.',
    goodFor: 'Wie jackfruit buiten de bekende zoete of vegan bereidingen wil proeven.',
    watch: 'De aanwezigheid van jackfruit maakt het gerecht niet automatisch vegetarisch.',
    pairing: 'Eet als onderdeel van een gedeelde Noord-Thaise maaltijd met rijst en groenten.',
    scores: { fris: 1, hartig: 4, pittig: 4, romig: 0 },
  },
  'khao-kan-jin': {
    lead: 'Khao kan jin is een Noord-Thaise rijstbereiding met varkensbloed, gestoomd in een bananenblad en vaak afgewerkt met gefrituurde knoflook. Het is een uitgesproken lokale keuze.',
    flavour: 'Hartig en mild gekruid, met geroosterde knoflook als sterk accent.',
    texture: 'Compacte, zachte rijst met krokante garnituren.',
    orderTip: 'Bestel alleen wanneer je bewust varkensbloed wilt proberen en vraag welke toppings erbij horen.',
    goodFor: 'Nieuwsgierige eters die een minder bekend Noord-Thais gerecht zoeken.',
    watch: 'Varkensbloed, varkensvlees, knoflookolie en gedeelde bereiding zijn kernpunten.',
    pairing: 'Combineer met verse groenten, chili en een ander gerecht voor afwisseling.',
    scores: { fris: 1, hartig: 5, pittig: 2, romig: 1 },
  },
  'roti-canai': {
    lead: 'In Zuid-Thailand vind je roti als gelaagd platbrood bij curry, maar ook als zoete snack. De naam op het menu zegt daarom niet altijd welke uitvoering je krijgt.',
    flavour: 'Boterig en geroosterd; hartig met curry of zoet met gecondenseerde melk en suiker.',
    texture: 'Krokante, bladerige buitenlagen met een zacht en elastisch midden.',
    orderTip: 'Vraag of de roti hartig of zoet wordt geserveerd en welke vetstof, curry of topping wordt gebruikt.',
    goodFor: 'Wie Zuid-Thaise en Maleisische culinaire invloeden wil proeven.',
    watch: 'Gluten, ei, melk, ghee en gedeelde bakplaten kunnen voorkomen.',
    pairing: 'Hartige roti werkt als brood bij curry; een zoete versie is een apart dessert.',
    scores: { fris: 0, hartig: 3, pittig: 1, romig: 3 },
  },
  'bua-loy': {
    lead: 'Bua loy bestaat uit kleine rijstmeelballetjes in warme kokosmelk. Kleuren en smaken komen vaak uit pandan, pompoen of andere ingrediënten, maar verschillen per recept.',
    flavour: 'Zoet, kokosachtig en soms licht zout.',
    texture: 'Zachte, taaie balletjes in een warme romige vloeistof.',
    orderTip: 'Vraag of er ei, kleurstoffen of extra toppings in de kom zitten.',
    goodFor: 'Wie een warm, zacht dessert verkiest boven ijs of fruit.',
    watch: 'Kokos, ei, sesam of kleurstoffen kunnen voorkomen.',
    pairing: 'Neem een kleine portie; de combinatie van rijstmeel en kokos vult snel.',
    scores: { fris: 0, hartig: 1, pittig: 0, romig: 5 },
  },
  'sukhothai-noodles': {
    lead: 'Sukhothai-noedels combineren rijstnoedels, varkensvlees, pinda en een zoetzuur gekruide bouillon of droge saus. De kom wordt vaak afgewerkt met limoen en groenten.',
    flavour: 'Zoetzuur, hartig en mild tot pittig.',
    texture: 'Zachte noedels met gehakt of plakjes vlees, pinda en knapperige groente.',
    orderTip: 'Kies droog of met bouillon en vraag naar pinda, varkensvlees en het chiliniveau.',
    goodFor: 'Wie een regionale noedelkom wil die frisheid en zoet combineert.',
    watch: 'Pinda, varkensvlees, vissaus, soja en gedeelde kookpotten kunnen voorkomen.',
    pairing: 'Proef vóór je suiker, chili of azijn toevoegt; de kom is vaak al uitgebalanceerd.',
    scores: { fris: 4, hartig: 4, pittig: 2, romig: 0 },
  },
  'kaeng-liang': {
    lead: 'Kaeng liang is een peperige groentesoep met veel verschillende groenten en kruiden. Garnalen of garnalenpasta geven veel versies hun hartige basis.',
    flavour: 'Peperig, kruidig en hartig zonder de romigheid van kokosmelk.',
    texture: 'Lichte bouillon met verschillende zachte en stevige groenten.',
    orderTip: 'Vraag welke groenten, bouillon en garnalenproducten in de pot zitten.',
    goodFor: 'Wie een groenterijke, niet-romige soep zoekt.',
    watch: 'Garnaal, garnalenpasta, vissaus en gedeelde bouillon maken de soep vaak niet vegetarisch.',
    pairing: 'Eet met rijst en een milder hoofdgerecht.',
    scores: { fris: 3, hartig: 4, pittig: 3, romig: 0 },
  },
  'moo-palo': {
    lead: 'Moo palo is varkensvlees met ei in een donkere, geurige vijfkruidenbouillon. De smaak komt uit langzaam stoven, niet uit veel chili.',
    flavour: 'Zoet-hartig en warm gekruid met soja en steranijsachtige tonen.',
    texture: 'Zacht varkensvlees, stevig ei en een dunne maar rijke bouillon.',
    orderTip: 'Vraag welk stuk varkensvlees wordt gebruikt en bestel rijst om de bouillon te doseren.',
    goodFor: 'Wie een mild stoofgerecht met Chinese invloeden wil.',
    watch: 'Varkensvlees, ei, soja en gluten kunnen voorkomen.',
    pairing: 'Combineer met rijst en een fris groentegerecht.',
    scores: { fris: 1, hartig: 5, pittig: 0, romig: 1 },
  },
  'nam-prik-noom': {
    lead: 'Nam prik noom is een Noord-Thaise dip van geroosterde groene chili, sjalot en knoflook. Hij wordt met groenten, kleefrijst en soms krokante varkenshuid gegeten.',
    flavour: 'Rokerig, pittig en hartig.',
    texture: 'Grove, zachte dip naast knapperige groenten.',
    orderTip: 'Vraag hoe pittig de dip is en welke bijgerechten in de set zitten.',
    goodFor: 'Wie geroosterde chili wil proeven in kleine, controleerbare happen.',
    watch: 'Vissaus, garnalenpasta, varkenshuid en gedeelde vijzels kunnen voorkomen.',
    pairing: 'Gebruik groente en kleefrijst om elke hap zelf op te bouwen.',
    scores: { fris: 2, hartig: 4, pittig: 4, romig: 0 },
  },
  'nam-prik-kapi': {
    lead: 'Nam prik kapi is een krachtige dip van garnalenpasta, chili, knoflook en limoen. Hij wordt niet als losse sauslepel gegeten, maar in kleine hoeveelheden met rijst, groente en vaak vis.',
    flavour: 'Zeer hartig, zout, zuur en pittig.',
    texture: 'Dunne tot grove dip met verse of geblancheerde begeleiders.',
    orderTip: 'Vraag welke vis, groenten en omelet- of vleesbijgerechten bij de set horen.',
    goodFor: 'Wie fermentatie en uitgesproken umami wil verkennen.',
    watch: 'Schaaldieren en vis zijn essentieel; kruiscontact is waarschijnlijk.',
    pairing: 'Begin met een klein stipje dip per hap en bouw langzaam op.',
    scores: { fris: 4, hartig: 5, pittig: 5, romig: 0 },
  },
  'gaeng-tai-pla': {
    lead: 'Gaeng tai pla is een zeer intense Zuid-Thaise curry op basis van gefermenteerde visingewanden, vis, chili en aromaten. Dit is geen milde instapcurry.',
    flavour: 'Zeer pittig, zout, hartig en kruidig.',
    texture: 'Dunne tot middeldikke curry met vis en groenten.',
    orderTip: 'Vraag naar de scherpte en ingrediënten en bestel alleen als je bewust gefermenteerde visingewanden wilt proberen.',
    goodFor: 'Ervaren eters die krachtige Zuid-Thaise smaken zoeken.',
    watch: 'Vis, visingewanden, garnalenpasta en zeer veel chili zijn centrale aandachtspunten.',
    pairing: 'Eet met veel rijst, groenten en een mild gerecht; deel één kom.',
    scores: { fris: 2, hartig: 5, pittig: 5, romig: 1 },
  },
  'goong-pad-sator': {
    lead: 'Goong pad sator wokt garnalen met satorbonen, chili en vaak garnalenpasta. De bonen hebben een uitgesproken geur en een stevige, licht bittere beet.',
    flavour: 'Hartig, pittig en aromatisch met een herkenbare satorsmaak.',
    texture: 'Stevige garnalen en knapperige bonen in een geconcentreerde saus.',
    orderTip: 'Vraag naar garnalenpasta, pittigheid en of de satorbonen volledig of gehalveerd worden geserveerd.',
    goodFor: 'Wie uitgesproken Zuid-Thaise ingrediënten wil proberen.',
    watch: 'Schaaldieren, garnalenpasta, vissaus en sterke geur zijn inherent aan veel versies.',
    pairing: 'Bestel rijst en een mildere soep of groente om de intensiteit te verdelen.',
    scores: { fris: 1, hartig: 5, pittig: 4, romig: 0 },
  },
  'lod-chong': {
    lead: 'Lod chong is een koud dessert met groene pandanachtige rijstmeelnoedeltjes, kokosmelk, siroop en ijs. De verhoudingen bepalen of het licht of zeer zoet smaakt.',
    flavour: 'Zoet, kokosachtig en geurig.',
    texture: 'Zachte, gladde noedeltjes in koude romige kokosmelk.',
    orderTip: 'Vraag om minder siroop als je niet te zoet wilt en controleer extra toppings bij allergieën.',
    goodFor: 'Een verkoelend dessert na pittig eten of tijdens een warme marktronde.',
    watch: 'Kokos, kleurstoffen, brood, bonen of andere toppings kunnen per verkoper verschillen.',
    pairing: 'Eet direct voordat het ijs de kokosmelk sterk verdunt.',
    scores: { fris: 4, hartig: 0, pittig: 0, romig: 4 },
  },
};

export const ingredientTranslations: Record<string, string> = {
  'banana leaves': 'bananenblad',
  'banana flour jelly': 'zachte gelei',
  'bean sprouts': 'taugé',
  beef: 'rundvlees',
  basil: 'basilicum',
  'bay leaves': 'laurierblad',
  cardamom: 'kardemom',
  'cashew nuts': 'cashewnoten',
  chicken: 'kip',
  chili: 'chili',
  'chinese chives': 'Chinese bieslook',
  'chinese five spice': 'vijfkruidenpoeder',
  'chinese kale': 'Chinese boerenkool',
  'chinese broccoli': 'Chinese broccoli',
  cinnamon: 'kaneel',
  cilantro: 'koriander',
  coriander: 'koriander',
  'coriander root': 'korianderwortel',
  'coarse salt': 'grof zout',
  coconut: 'kokos',
  'coconut milk': 'kokosmelk',
  'curry paste': 'currypasta',
  'curry for dipping': 'curry om te dippen',
  'curry powder': 'kerriepoeder',
  cucumber: 'komkommer',
  'dark soy sauce': 'donkere sojasaus',
  'dried shrimp': 'gedroogde garnaal',
  'dried spices': 'gedroogde specerijen',
  'dried chili': 'gedroogde chili',
  egg: 'ei',
  'egg noodles': 'eiernoedels',
  eggs: 'eieren',
  'fermented rice noodles': 'gefermenteerde rijstnoedels',
  'fermented soybeans': 'gefermenteerde sojabonen',
  fish: 'vis',
  'fish balls': 'visballen',
  'fish organs': 'visingewanden',
  'fish sauce': 'vissaus',
  flour: 'bloem',
  'food coloring': 'kleurstof',
  garlic: 'knoflook',
  galangal: 'galanga',
  ghee: 'ghee',
  ginger: 'gember',
  'glass noodles': 'glasnoedels',
  'green chili': 'groene chili',
  'green beans': 'sperziebonen',
  'green curry paste': 'groene currypasta',
  'green papaya': 'groene papaja',
  'ground peanuts': 'gemalen pinda',
  'ground pork': 'varkensgehakt',
  herbs: 'kruiden',
  ice: 'ijs',
  'jasmine rice': 'jasmijnrijst',
  'kaffir lime leaves': 'makrut-limoenblad',
  lemongrass: 'citroengras',
  'lime juice': 'limoensap',
  'lime leaves': 'limoenblad',
  lime: 'limoen',
  mango: 'mango',
  'massaman paste': 'massamancurrypasta',
  'minced pork': 'varkensgehakt',
  'minced pork or beef': 'varkens- of rundergehakt',
  mint: 'munt',
  'mixed vegetables': 'gemengde groenten',
  'morning glory': 'waterspinazie',
  'mussels or oysters': 'mosselen of oesters',
  mushrooms: 'paddenstoelen',
  onion: 'ui',
  'palm sugar': 'palmsuiker',
  pandan: 'pandan',
  'pandan juice': 'pandansap',
  peanuts: 'pinda',
  'pickled mustard': 'ingelegde mosterdgroente',
  pineapple: 'ananas',
  pork: 'varkensvlees',
  'pork belly': 'varkensbuik',
  'pork blood': 'varkensbloed',
  'pork or beef': 'varkens- of rundvlees',
  'pork ribs': 'varkensrib',
  'pork or chicken': 'varkensvlees of kip',
  potatoes: 'aardappelen',
  prawns: 'garnalen',
  rice: 'rijst',
  'rice flour': 'rijstmeel',
  'rice noodles': 'rijstnoedels',
  raisins: 'rozijnen',
  salt: 'zout',
  'seafood dipping sauce': 'dipsaus voor zeevruchten',
  shallots: 'sjalot',
  'shaved ice': 'schaafijs',
  shrimp: 'garnaal',
  'shrimp paste': 'garnalenpasta',
  'soy sauce': 'sojasaus',
  'soybean paste': 'sojabonenpasta',
  squid: 'inktvis',
  'sticky rice': 'kleefrijst',
  'stink beans': 'satorbonen',
  sugar: 'suiker',
  syrup: 'siroop',
  tamarind: 'tamarinde',
  'tamarind paste': 'tamarindepasta',
  'thai basil': 'Thaise basilicum',
  'thai eggplant': 'Thaise aubergine',
  tofu: 'tofu',
  'toasted rice': 'geroosterd rijstpoeder',
  tomato: 'tomaat',
  tomatoes: 'tomaat',
  turmeric: 'kurkuma',
  'whole fish': 'hele vis',
  'wide rice noodles': 'brede rijstnoedels',
  'yellow noodles': 'gele noedels',
  'young jackfruit': 'jonge jackfruit',
  vegetables: 'groenten',
  water: 'water',
  'white pepper': 'witte peper',
};
