import Image from 'next/image';
import Link from 'next/link';
import {
  ArrowRight,
  BedDouble,
  Bike,
  BookOpen,
  BusFront,
  CalendarDays,
  Check,
  Clock3,
  Compass,
  ExternalLink,
  Footprints,
  Landmark,
  Map,
  Route,
  ShieldCheck,
  TrainFront,
  Utensils,
  Waves,
} from 'lucide-react';
import { StoryDottedRoute } from '../visuals/StoryDottedRoute';

interface AyutthayaDestinationOverviewProps { activitiesHref: string; hotelsHref: string; transportHref: string; }
const AFFILIATE_REL = 'noopener noreferrer nofollow sponsored';

const decisions = [
  { icon: Clock3, title: 'A focused day trip', label: 'Best for a first layer', copy: 'Choose one central ruin cluster, one outer temple and one food stop. An early start matters more than adding a sixth exposed ruin.' },
  { icon: BedDouble, title: 'Stay one night', label: 'Best for atmosphere', copy: 'Sleep locally when early light, a museum, a river-facing evening and a slower second cluster matter more than returning to Bangkok quickly.' },
  { icon: TrainFront, title: 'Travel independently', label: 'Best for flexibility', copy: 'Arrive by current train or road option, then arrange the historical-island circuit locally. Confirm the latest timetable before departure.' },
  { icon: BusFront, title: 'Join an organised route', label: 'Best for simplicity', copy: 'A tour solves Bangkok transfer and local movement. Compare group size, temple sequence, included stops and time at each site.' },
] as const;

const clusters = [
  { title: 'Royal core', tag: 'Central island', copy: 'Wat Phra Si Sanphet and the palace area explain royal Ayutthaya better together than as isolated ruins.', image: '/images/cities/ayutthaya/attractions/Scenic ruins of Wat Phra Si Sanphet in Ayutthaya.webp', href: '/city/ayutthaya/attractions/' },
  { title: 'Mahathat & Ratchaburana', tag: 'Walkable pair', copy: 'Use these neighbouring sites to read sacred architecture and the famous Buddha-head setting without another vehicle transfer.', image: '/images/cities/ayutthaya/attractions/Wat Mahathat temple, Thailand.webp', href: '/city/ayutthaya/attractions/' },
  { title: 'Chaiwatthanaram & river', tag: 'Outer-island light', copy: 'Reserve time for the river setting and late-day atmosphere. It deserves more than a rushed final stop before the return journey.', image: '/images/cities/ayutthaya/attractions/at Chaiwatthanaram tempel bij nacht, Ayutthaya.webp', href: '/city/ayutthaya/attractions/' },
  { title: 'Living temples & contrast', tag: 'Beyond the ruins', copy: 'Wat Yai Chai Mongkhon and selected museums or communities stop the day becoming one repetitive sequence of brick remains.', image: '/images/cities/ayutthaya/attractions/Wat Yai Chai Mongkhon of Ayuthaya.webp', href: '/city/ayutthaya/attractions/' },
] as const;

const route = [
  { phase: 'Morning', title: 'Central historical island', path: 'Wat Mahathat → Wat Ratchaburana → royal core', note: 'Begin before heat and crowds build. Walk or cycle only within a cluster that fits your comfort and the weather.' },
  { phase: 'Midday', title: 'Museum or food reset', path: 'Indoor context → boat noodles or roti sai mai', note: 'A shaded pause gives the ruins meaning and prevents the afternoon from becoming visual fatigue.' },
  { phase: 'Late day', title: 'One outer temple', path: 'Wat Chaiwatthanaram or Wat Yai Chai Mongkhon', note: 'Choose one direction and finish it well. Build the return train, car or hotel plan before sunset.' },
] as const;

const movement = [
  { icon: Footprints, title: 'Walking', copy: 'Good inside individual central clusters, not for the complete historical area and outer temples.' },
  { icon: Bike, title: 'Bicycle', copy: 'Useful on the island in manageable weather. Traffic, heat and exposed roads make it a poor automatic choice for everyone.' },
  { icon: Route, title: 'Tuk-tuk or local driver', copy: 'Efficient for linking outer sites. Agree on the route, waiting arrangement and finish point before leaving.' },
  { icon: Waves, title: 'Boat perspective', copy: 'A river circuit adds landscape and trade context, but it complements rather than replaces the main ruin route.' },
] as const;

const practical = [
  { icon: Landmark, title: 'Ruins and active temples differ', copy: 'Some sites are archaeological remains; others are living religious spaces. Follow the stricter local instruction whenever it appears.' },
  { icon: ShieldCheck, title: 'Dress for respect', copy: 'Cover shoulders and knees for temple visits and carry a light layer. Do not climb, sit on or lean against sacred structures.' },
  { icon: BookOpen, title: 'Add context before saturation', copy: 'A museum or carefully chosen guide can explain court, trade and destruction better than another unsupported photo stop.' },
  { icon: CalendarDays, title: 'Plan shade and live access', copy: 'Ruins are exposed and access can change. Verify current opening information and keep a shaded midday alternative.' },
] as const;

export function AyutthayaDestinationOverview({ activitiesHref, hotelsHref, transportHref }: AyutthayaDestinationOverviewProps) {
  return <>
    <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="grid gap-8 lg:grid-cols-[0.7fr_1.55fr] lg:items-end lg:gap-14"><div><p className="eyebrow">Choose the depth</p><h2 className="font-display text-[3.05rem] font-semibold leading-[0.9] tracking-[-0.04em] text-jade sm:text-[3.7rem]">Day trip or one night?</h2><p className="mt-5 max-w-md text-sm leading-7 text-charcoal/62">Ayutthaya is close enough to Bangkok for a day trip, but the ancient capital becomes richer when you have time for early light, historical context and a river evening.</p></div><div className="grid gap-3 sm:grid-cols-2">{decisions.map(({icon:Icon,title,label,copy})=><article key={title} className="rounded-xl border border-jade/10 bg-white p-5 shadow-[0_5px_18px_rgba(18,63,54,0.035)]"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-lg border border-saffron/25 bg-saffron/[0.06] text-jade"><Icon size={21} strokeWidth={1.55}/></span><div><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-saffron-dark">{label}</p><h3 className="mt-1 font-display text-2xl font-semibold text-jade">{title}</h3></div></div><p className="mt-4 text-xs leading-6 text-charcoal/60">{copy}</p></article>)}</div></div><div className="mt-6 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-jade/10 bg-white px-5 py-4"><p className="text-xs leading-5 text-charcoal/56"><strong className="text-jade">Want the transfer handled?</strong> Compare current group size, temple route and return format before choosing a tour.</p><a href={activitiesHref} target="_blank" rel={AFFILIATE_REL} className="inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Check current Ayutthaya tours on Klook <ExternalLink size={14}/></a></div></div></section>

    <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="mb-7 flex items-end justify-between gap-5"><div><p className="eyebrow">Four heritage clusters</p><h2 className="font-display text-[2.9rem] font-semibold leading-none tracking-[-0.04em] text-jade sm:text-[3.4rem]">Fewer stops. More historical shape.</h2></div><Link href="/city/ayutthaya/attractions/" className="hidden items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark sm:flex">All Ayutthaya attractions <ArrowRight size={15}/></Link></div><div className="scrollbar-hide flex snap-x gap-4 overflow-x-auto pb-2 sm:grid sm:grid-cols-2 sm:overflow-visible lg:grid-cols-4">{clusters.map(item=><Link key={item.title} href={item.href} className="group min-w-[80vw] snap-start overflow-hidden rounded-xl border border-jade/10 bg-white shadow-[0_5px_18px_rgba(18,63,54,0.04)] transition hover:-translate-y-1 hover:shadow-xl sm:min-w-0"><div className="relative aspect-[4/2.9] overflow-hidden"><Image src={item.image} alt={item.title} fill sizes="(min-width:1024px) 25vw, 80vw" className="object-cover transition duration-500 group-hover:scale-[1.035]"/><span className="absolute left-3 top-3 rounded-md bg-jade/88 px-2.5 py-1 text-[8px] font-bold uppercase tracking-[0.17em] text-white backdrop-blur">{item.tag}</span></div><div className="p-4"><h3 className="font-display text-[1.35rem] font-semibold leading-tight text-jade">{item.title}</h3><p className="mt-2 text-[11px] leading-5 text-charcoal/58">{item.copy}</p><span className="mt-4 flex items-center justify-between border-t border-jade/8 pt-3 text-[10px] font-bold text-jade">Open the guide <ArrowRight size={14}/></span></div></Link>)}</div></div></section>

    <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="relative overflow-hidden rounded-2xl bg-jade-dark text-white shadow-editorial-lift"><Image src="/images/redesign/ayutthaya-river-heritage.webp" alt="Ayutthaya temples beside the river" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-jade-dark via-jade-dark/86 to-jade-dark/12"/><div className="relative grid min-h-[390px] items-center gap-8 px-7 py-10 sm:px-10 lg:grid-cols-[0.72fr_1.2fr] lg:px-14"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-saffron-light">Read the river city</p><h2 className="mt-3 max-w-md font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] sm:text-[3.7rem]">The ruins were part of a connected capital.</h2><p className="mt-5 max-w-md text-sm leading-7 text-white/70">Rivers shaped trade, defence, court life and movement. Use one deliberate outer-island crossing to understand the landscape instead of treating every wat as an isolated monument.</p></div><div className="relative hidden min-h-[250px] lg:block"><StoryDottedRoute className="absolute left-0 top-14 h-40 w-72 opacity-90"/><div className="absolute right-0 top-0 grid w-[390px] grid-cols-2 gap-3">{['Central island','Royal precinct','River crossing','Outer temple'].map((label,index)=><div key={label} className="rounded-xl border border-white/15 bg-white/[0.09] p-4 backdrop-blur-sm"><span className="text-[9px] font-bold uppercase tracking-[0.18em] text-saffron-light">Layer {index+1}</span><strong className="mt-1.5 block font-display text-lg font-semibold">{label}</strong></div>)}</div></div></div></div></div></section>

    <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom grid gap-10 lg:grid-cols-[0.62fr_1.6fr] lg:gap-14"><div><p className="eyebrow">One strong day</p><h2 className="font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] text-jade sm:text-[3.55rem]">Three phases, not ten rushed temples.</h2><p className="mt-5 text-sm leading-7 text-charcoal/62">A full day is enough for a meaningful first visit when every phase has a role. Stay overnight if you want another cluster, not simply more of the same.</p></div><div className="relative grid gap-4 lg:grid-cols-3"><div className="pointer-events-none absolute left-8 right-8 top-8 hidden border-t border-dashed border-saffron/55 lg:block"/>{route.map((item,index)=><article key={item.phase} className="relative rounded-xl border border-jade/10 bg-white p-5 shadow-[0_5px_18px_rgba(18,63,54,0.035)]"><span className="grid h-8 w-8 place-items-center rounded-full border border-saffron/45 bg-[#fcfaf6] text-[10px] font-extrabold text-saffron-dark">{index+1}</span><p className="mt-5 text-[9px] font-bold uppercase tracking-[0.18em] text-saffron-dark">{item.phase}</p><h3 className="mt-1 font-display text-2xl font-semibold text-jade">{item.title}</h3><p className="mt-4 text-xs font-bold leading-5 text-jade">{item.path}</p><p className="mt-3 text-[11px] leading-5 text-charcoal/56">{item.note}</p></article>)}</div></div></section>

    <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom grid gap-5 lg:grid-cols-2"><article className="overflow-hidden rounded-2xl border border-jade/10 bg-white shadow-[0_6px_22px_rgba(18,63,54,0.045)]"><div className="relative aspect-[16/8.5]"><Image src="/images/redesign/ayutthaya-food-specialties.webp" alt="Ayutthaya food specialities" fill sizes="50vw" className="object-cover"/></div><div className="p-6 sm:p-8"><p className="eyebrow">Food breaks the ruin rhythm</p><h2 className="font-display text-[2.75rem] font-semibold leading-[0.95] tracking-[-0.035em] text-jade">Taste a former trading capital.</h2><p className="mt-4 text-sm leading-7 text-charcoal/62">Boat noodles, roti sai mai and river prawns give the day regional texture. Choose a shaded food stop deliberately instead of eating only when temple fatigue wins.</p><Link href="/city/ayutthaya/food/" className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">See the Ayutthaya food guide <ArrowRight size={15}/></Link></div></article><article className="overflow-hidden rounded-2xl border border-jade/10 bg-white shadow-[0_6px_22px_rgba(18,63,54,0.045)]"><div className="relative aspect-[16/8.5]"><Image src="/images/redesign/experience-ayutthaya.webp" alt="Cycling through Ayutthaya at sunset" fill sizes="50vw" className="object-cover"/></div><div className="p-6 sm:p-8"><p className="eyebrow">Stay for the quiet edges</p><h2 className="font-display text-[2.75rem] font-semibold leading-[0.95] tracking-[-0.035em] text-jade">One night changes the light and pace.</h2><p className="mt-4 text-sm leading-7 text-charcoal/62">An overnight removes the Bangkok deadline and makes room for early ruins, a museum or a slower river evening. Check the exact hotel position against your route.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/where-to-stay/ayutthaya/" className="inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Compare areas <ArrowRight size={15}/></Link><a href={hotelsHref} target="_blank" rel={AFFILIATE_REL} className="inline-flex items-center gap-2 text-xs font-bold text-saffron-dark hover:text-jade">Check current hotel prices on Trip.com <ExternalLink size={14}/></a></div></div></article></div></section>

    <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom grid items-center gap-9 lg:grid-cols-[0.9fr_1.1fr] lg:gap-14"><div className="relative aspect-[4/3] overflow-hidden rounded-2xl border border-jade/10 shadow-editorial-lift"><Image src="/images/cities/ayutthaya/ayutthaya-historical-park.webp" alt="Map-like view of Ayutthaya Historical Park" fill sizes="48vw" className="object-cover"/></div><div><p className="eyebrow">Move by cluster</p><h2 className="font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] text-jade sm:text-[3.6rem]">The historical island is compact. The full story is not.</h2><p className="mt-5 text-sm leading-7 text-charcoal/62">Walk or cycle only where sites sit close together, then use a vehicle or boat for outer temples. The best mode changes with heat, traffic and your return deadline.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{movement.map(({icon:Icon,title,copy})=><article key={title} className="rounded-xl border border-jade/10 bg-white p-4"><Icon size={19} className="text-jade" strokeWidth={1.55}/><h3 className="mt-3 font-display text-xl font-semibold text-jade">{title}</h3><p className="mt-2 text-[10px] leading-5 text-charcoal/55">{copy}</p></article>)}</div><a href={transportHref} target="_blank" rel={AFFILIATE_REL} className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Check current Bangkok–Ayutthaya transport on 12Go <ExternalLink size={14}/></a></div></div></section>

    <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="grid gap-8 lg:grid-cols-[0.72fr_1.5fr] lg:gap-14"><div><p className="eyebrow">Before the first wat</p><h2 className="font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] text-jade sm:text-[3.55rem]">Respect keeps the route meaningful.</h2><p className="mt-5 text-sm leading-7 text-charcoal/62">Ayutthaya combines protected ruins, active worship and exposed outdoor sites. Treat every instruction as part of the destination.</p></div><div className="grid gap-3 sm:grid-cols-2">{practical.map(({icon:Icon,title,copy})=><article key={title} className="rounded-xl border border-jade/10 bg-white p-5 shadow-[0_5px_18px_rgba(18,63,54,0.035)]"><span className="grid h-10 w-10 place-items-center rounded-lg border border-jade/10 bg-jade/[0.025] text-jade"><Icon size={20} strokeWidth={1.55}/></span><h3 className="mt-4 font-display text-2xl font-semibold text-jade">{title}</h3><p className="mt-2 text-[11px] leading-5 text-charcoal/57">{copy}</p></article>)}</div></div><div className="mt-9 rounded-2xl border border-jade/10 bg-white px-6 py-7 sm:px-8"><div className="grid gap-6 lg:grid-cols-[0.72fr_1.4fr] lg:items-center"><div><p className="eyebrow">Pack for an exposed heritage day</p><h3 className="font-display text-[2.35rem] font-semibold leading-[0.95] text-jade">Shade, respect and a return plan.</h3></div><ul className="grid gap-3 text-xs leading-5 text-charcoal/60 sm:grid-cols-2">{['Cover shoulders and knees for temple access.','Carry water and plan a shaded midday stop.','Save the station, hotel or pickup point before touring.','Confirm live site and transport information that morning.'].map(item=><li key={item} className="flex gap-2.5"><Check size={15} className="mt-0.5 shrink-0 text-saffron-dark"/>{item}</li>)}</ul></div></div></div></section>

    <section className="section-divider-bottom bg-jade-dark py-12 text-white lg:py-16"><div className="container-custom grid gap-9 lg:grid-cols-[0.68fr_1.5fr] lg:items-center lg:gap-14"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-saffron-light">Continue planning</p><h2 className="mt-3 font-display text-[3rem] font-semibold leading-[0.93] tracking-[-0.04em]">Build the rest of your Ayutthaya trip.</h2><p className="mt-4 text-sm leading-7 text-white/64">Use the specialist guides for the temple inventory, food, stay and Bangkok connection.</p></div><div className="grid gap-3 sm:grid-cols-2">{[
      {icon:Compass,title:'Ayutthaya attractions',copy:'Temple clusters, museums and meaningful contrasts.',href:'/city/ayutthaya/attractions/'},
      {icon:Utensils,title:'Food in Ayutthaya',copy:'Boat noodles, roti sai mai and river-focused meals.',href:'/city/ayutthaya/food/'},
      {icon:BedDouble,title:'Where to stay',copy:'Choose a practical overnight base for your route.',href:'/where-to-stay/ayutthaya/'},
      {icon:Map,title:'Bangkok travel guide',copy:'Connect the ancient capital to a smarter Bangkok plan.',href:'/city/bangkok/'},
    ].map(({icon:Icon,title,copy,href})=><Link key={title} href={href} className="group rounded-xl border border-white/12 bg-white/[0.07] p-5 transition hover:-translate-y-0.5 hover:border-saffron/45 hover:bg-white/[0.11]"><Icon size={20} className="text-saffron-light" strokeWidth={1.55}/><h3 className="mt-4 flex items-center justify-between font-display text-xl font-semibold">{title}<ArrowRight size={15} className="text-saffron-light"/></h3><p className="mt-2 text-[10px] leading-5 text-white/55">{copy}</p></Link>)}</div></div></section>

    <section className="section-divider-bottom bg-[#fcfaf6] py-9"><div className="container-custom flex flex-col gap-5 text-[10px] leading-5 text-charcoal/52 lg:flex-row lg:items-start lg:justify-between"><div className="max-w-3xl"><p className="font-bold uppercase tracking-[0.18em] text-jade">Editorial method</p><p className="mt-2">UNESCO’s Historic City listing anchors the heritage entity. Current English SERPs and independent route sources inform day-trip and overnight decisions; live transport, access and venue details must still be verified close to travel.</p></div><div className="flex flex-wrap gap-x-4 gap-y-2 font-bold text-jade"><a href="https://whc.unesco.org/en/list/576/" target="_blank" rel="noopener noreferrer nofollow" className="hover:text-saffron-dark">UNESCO World Heritage Centre</a><Link href="/editorial-policy/" className="hover:text-saffron-dark">Editorial policy</Link></div></div></section>
  </>;
}
