import Image from 'next/image';
import Link from 'next/link';
import {
  ArrowRight,
  BedDouble,
  BusFront,
  CalendarDays,
  Check,
  ExternalLink,
  Footprints,
  MapPin,
  Mountain,
  Route,
  ShieldCheck,
  Soup,
  Sparkles,
} from 'lucide-react';
import { StoryDottedRoute } from '../visuals/StoryDottedRoute';

interface ChiangRaiDestinationOverviewProps {
  activitiesHref: string;
  hotelsHref: string;
  transportHref: string;
}

const AFFILIATE_REL = 'noopener noreferrer nofollow sponsored';

const tripShapes = [
  { title: 'Focused day trip', label: 'Only if time is tight', copy: 'Choose one coherent art-temple circuit and accept that the city evening and northern province remain outside the trip.', icon: Sparkles },
  { title: 'Two nights', label: 'Best first balance', copy: 'Enough for the main city-area circuit, one relaxed evening and either a second cultural cluster or a selective outer route.', icon: BedDouble },
  { title: 'Three nights', label: 'Add provincial depth', copy: 'Use the third full day for Doi Tung, Mae Salong or Golden Triangle context instead of squeezing the north into temple day.', icon: Mountain },
  { title: 'Slow northern base', label: 'Four nights or more', copy: 'Works when food, coffee landscapes and mountain roads matter as much as the headline art sites. Keep live air quality in the plan.', icon: Route },
] as const;

const experiences = [
  { title: 'Read the White Temple slowly', tag: 'Contemporary vision', copy: 'Wat Rong Khun is a living contemporary project, not an ancient white relic. Give the imagery and wider complex more than a drive-by photo.', image: '/images/cities/chiang-rai/attractions/Chiang rai White Temple (Wat Rong Khun).webp', href: '/city/chiang-rai/attractions/' },
  { title: 'Pair blue with local history', tag: 'North-city cluster', copy: 'Wat Rong Suea Ten can share a route with Wat Phra Kaew or the Kok River, creating contrast between modern visual language and older city history.', image: '/images/cities/chiang-rai/attractions/Chiang rai Blue Temple (Wat Rong Suea Ten).webp', href: '/city/chiang-rai/attractions/' },
  { title: 'Treat Baan Dam as art', tag: 'Museum, not temple', copy: 'The Black House is an art and museum estate. Its dark material vocabulary belongs in a different mental category from a worship site.', image: '/images/cities/chiang-rai/attractions/Black House (Baan Dam Museum).webp', href: '/city/chiang-rai/attractions/' },
  { title: 'Give the city an evening', tag: 'Food & centre', copy: 'The clock tower, market area and Northern dishes keep Chiang Rai from becoming only a series of roadside attraction stops.', image: '/images/cities/chiang-rai/attractions/chiang rai Night Bazaar.webp', href: '/city/chiang-rai/food/' },
] as const;

const itinerary = [
  { day: 'Day 1', title: 'City & colour', route: 'Wat Phra Kaew → Blue Temple → centre evening', note: 'Start with city history before the largest visual landmarks. Keep dinner and the evening walk near your base.' },
  { day: 'Day 2', title: 'Southern art route', route: 'White Temple → one nearby stop → unhurried return', note: 'Build the day around Wat Rong Khun rather than combining every attraction north and south of town.' },
  { day: 'Day 3', title: 'Choose one north', route: 'Doi Tung, Mae Salong or Golden Triangle route', note: 'These are different full-day stories. Select mountain gardens, tea landscapes or border history—not all three by default.' },
] as const;

const movement = [
  { icon: Footprints, title: 'Walking', copy: 'Useful around the clock tower, night bazaar and parts of the old centre. Headline attractions sit beyond one walking district.' },
  { icon: MapPin, title: 'Taxi & ride-hailing', copy: 'Good for city-area gaps when availability suits. Confirm the pickup and return rather than assuming a car will wait outside every site.' },
  { icon: BusFront, title: 'Driver or organised route', copy: 'The clearest option for a multi-stop temple circuit or long provincial day, especially when you want context and a reliable return.' },
  { icon: Route, title: 'Car or scooter', copy: 'Only with the correct licence, insurance and experience. Mountain weather, distance and unfamiliar roads raise the decision threshold.' },
] as const;

const practical = [
  { icon: ShieldCheck, title: 'Verify current site rules', copy: 'Opening access, ceremonies, dress instructions and photography rules can change. Follow the instructions at each active worship site.' },
  { icon: Mountain, title: 'Check air quality live', copy: 'Smoke and haze can affect northern trips seasonally. Use current measurements and official advice, not a fixed calendar promise.' },
  { icon: Soup, title: 'Keep a Northern dinner', copy: 'A city evening creates room for khao soi, sai ua and local market snacks instead of another meal built around a long roadside transfer.' },
  { icon: CalendarDays, title: 'Separate the province day', copy: 'Doi Tung, Mae Salong and Golden Triangle routes need real road time. One well-chosen geography produces the stronger day.' },
] as const;

export function ChiangRaiDestinationOverview({ activitiesHref, hotelsHref, transportHref }: ChiangRaiDestinationOverviewProps) {
  return (
    <>
      <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="mb-8 grid gap-5 lg:grid-cols-[0.72fr_1.28fr] lg:items-end lg:gap-14"><div><p className="eyebrow">Choose the depth</p><h2 className="font-display text-[3.05rem] font-semibold leading-[0.9] tracking-[-0.04em] text-jade sm:text-[3.7rem]">A day trip sees landmarks. Two nights reveal a city.</h2></div><p className="max-w-2xl text-sm leading-7 text-charcoal/62">Chiang Rai city is a practical base inside a much larger province. Decide whether you want one art-temple circuit, a city stay with evenings, or a northern landscape route before you start collecting pins.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{tripShapes.map(({icon:Icon,title,label,copy})=><article key={title} className="rounded-xl border border-jade/10 bg-white p-5 shadow-[0_5px_18px_rgba(18,63,54,0.04)]"><span className="grid h-10 w-10 place-items-center rounded-lg border border-saffron/25 bg-saffron/[0.05] text-saffron-dark"><Icon size={20} strokeWidth={1.55}/></span><p className="mt-5 text-[9px] font-bold uppercase tracking-[0.18em] text-saffron-dark">{label}</p><h3 className="mt-1 font-display text-2xl font-semibold text-jade">{title}</h3><p className="mt-3 text-[11px] leading-5 text-charcoal/58">{copy}</p></article>)}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-jade/10 bg-white px-5 py-4"><p className="text-xs leading-5 text-charcoal/56"><strong className="text-jade">Staying overnight?</strong> The clock-tower or night-bazaar side makes a first evening easy; the Kok River creates a quieter resort rhythm.</p><a href={hotelsHref} target="_blank" rel={AFFILIATE_REL} className="inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Check current hotel prices on Trip.com <ExternalLink size={14}/></a></div></div></section>

      <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="mb-7 flex items-end justify-between gap-5"><div><p className="eyebrow">Four different layers</p><h2 className="font-display text-[2.9rem] font-semibold leading-none tracking-[-0.04em] text-jade sm:text-[3.4rem]">Not every dramatic building is the same story.</h2></div><Link href="/city/chiang-rai/attractions/" className="hidden items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark sm:flex">All Chiang Rai attractions <ArrowRight size={15}/></Link></div><div className="scrollbar-hide flex snap-x gap-4 overflow-x-auto pb-2 sm:grid sm:grid-cols-2 sm:overflow-visible lg:grid-cols-4">{experiences.map(item=><Link key={item.title} href={item.href} className="group min-w-[80vw] snap-start overflow-hidden rounded-xl border border-jade/10 bg-white shadow-[0_5px_18px_rgba(18,63,54,0.04)] transition hover:-translate-y-1 hover:shadow-xl sm:min-w-0"><div className="relative aspect-[4/2.9] overflow-hidden"><Image src={item.image} alt={item.title} fill sizes="(min-width:1024px) 25vw, 80vw" className="object-cover transition duration-500 group-hover:scale-[1.035]"/><span className="absolute left-3 top-3 rounded-md bg-jade/88 px-2.5 py-1 text-[8px] font-bold uppercase tracking-[0.17em] text-white backdrop-blur">{item.tag}</span></div><div className="p-4"><h3 className="font-display text-[1.35rem] font-semibold leading-tight text-jade">{item.title}</h3><p className="mt-2 text-[11px] leading-5 text-charcoal/58">{item.copy}</p><span className="mt-4 flex items-center justify-between border-t border-jade/8 pt-3 text-[10px] font-bold text-jade">Open the guide <ArrowRight size={14}/></span></div></Link>)}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-jade/10 bg-white px-5 py-4"><p className="text-xs leading-5 text-charcoal/56"><strong className="text-jade">Comparing tours?</strong> Check the actual route, time at each site, group size and return—not the number of stops alone.</p><a href={activitiesHref} target="_blank" rel={AFFILIATE_REL} className="inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Check current options on Klook <ExternalLink size={14}/></a></div></div></section>

      <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="relative overflow-hidden rounded-2xl bg-jade-dark text-white shadow-editorial-lift"><Image src="/images/redesign/chiang-rai-mountain-route.webp" alt="Mountain landscape in Chiang Rai province" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-jade-dark via-jade-dark/84 to-jade-dark/12"/><div className="relative grid min-h-[405px] items-center gap-8 px-7 py-10 sm:px-10 lg:grid-cols-[0.74fr_1.2fr] lg:px-14"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-saffron-light">The one-north rule</p><h2 className="mt-3 max-w-md font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] sm:text-[3.7rem]">Choose one northern story. Follow it properly.</h2><p className="mt-5 max-w-md text-sm leading-7 text-white/70">Doi Tung, Mae Salong and the Golden Triangle are not interchangeable photo stops. Pick the route whose gardens, tea landscape or border history you actually want to understand.</p></div><div className="relative hidden min-h-[250px] lg:block"><StoryDottedRoute className="absolute left-0 top-14 h-40 w-72 opacity-90"/><div className="absolute right-0 top-0 grid w-[390px] gap-3">{[{tag:'Mountain & gardens',title:'Doi Tung'},{tag:'Tea landscape',title:'Mae Salong'},{tag:'River & border history',title:'Golden Triangle'}].map((item,index)=><div key={item.title} className="rounded-xl border border-white/15 bg-white/[0.09] p-4 backdrop-blur-sm"><span className="text-[9px] font-bold uppercase tracking-[0.18em] text-saffron-light">Route {index+1} · {item.tag}</span><strong className="mt-1.5 block font-display text-xl font-semibold">{item.title}</strong></div>)}</div></div></div></div></div></section>

      <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom grid gap-10 lg:grid-cols-[0.55fr_1.8fr] lg:gap-14"><div><p className="eyebrow">A realistic first visit</p><h2 className="font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] text-jade sm:text-[3.55rem]">Three days, three different scales.</h2><p className="mt-5 text-sm leading-7 text-charcoal/62">Two nights covers the city and main art circuit. Add a third full day when a mountain or border route is part of the reason you came.</p></div><div className="relative grid gap-4 sm:grid-cols-3"><div className="pointer-events-none absolute left-8 right-8 top-8 hidden border-t border-dashed border-saffron/55 sm:block"/>{itinerary.map((item,index)=><article key={item.day} className="relative rounded-xl border border-jade/10 bg-white p-5 shadow-[0_5px_18px_rgba(18,63,54,0.035)]"><span className="grid h-8 w-8 place-items-center rounded-full border border-saffron/45 bg-[#fcfaf6] text-[10px] font-extrabold text-saffron-dark">{index+1}</span><p className="mt-5 text-[9px] font-bold uppercase tracking-[0.18em] text-saffron-dark">{item.day}</p><h3 className="mt-1 font-display text-2xl font-semibold text-jade">{item.title}</h3><p className="mt-4 text-xs font-bold leading-5 text-jade">{item.route}</p><p className="mt-3 text-[11px] leading-5 text-charcoal/56">{item.note}</p></article>)}</div></div></section>

      <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom grid gap-5 lg:grid-cols-2"><article className="overflow-hidden rounded-2xl border border-jade/10 bg-white shadow-[0_6px_22px_rgba(18,63,54,0.045)]"><div className="relative aspect-[16/8.5]"><Image src="/images/redesign/chiang-rai-food-coffee.webp" alt="Northern Thai food and coffee in Chiang Rai" fill sizes="50vw" className="object-cover"/></div><div className="p-6 sm:p-8"><p className="eyebrow">Keep the city grounded</p><h2 className="font-display text-[2.75rem] font-semibold leading-[0.95] tracking-[-0.035em] text-jade">Northern food belongs inside the itinerary.</h2><p className="mt-4 text-sm leading-7 text-charcoal/62">Khao soi, sai ua, nam ngiao and the province’s coffee context give the evening a stronger purpose than shopping alone. Use the food owner for neighbourhood and dish choices.</p><Link href="/city/chiang-rai/food/" className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Plan where to eat in Chiang Rai <ArrowRight size={15}/></Link></div></article><article className="overflow-hidden rounded-2xl border border-jade/10 bg-white shadow-[0_6px_22px_rgba(18,63,54,0.045)]"><div className="relative aspect-[16/8.5]"><Image src="/images/cities/chiang-rai/attractions/Doi Tung Royal Villa.webp" alt="Doi Tung mountain gardens in Chiang Rai province" fill sizes="50vw" className="object-cover"/></div><div className="p-6 sm:p-8"><p className="eyebrow">Plan for the north</p><h2 className="font-display text-[2.75rem] font-semibold leading-[0.95] tracking-[-0.035em] text-jade">Cool mornings and clear views are not guaranteed.</h2><p className="mt-4 text-sm leading-7 text-charcoal/62">Season, altitude and live air quality affect a mountain day differently from a city temple route. Check current measurements and keep an alternative for poor visibility.</p><Link href="/city/chiang-rai/weather/" className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark"><CalendarDays size={15}/> Compare Chiang Rai by season <ArrowRight size={15}/></Link></div></article></div></section>

      <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom grid items-center gap-9 lg:grid-cols-[0.9fr_1.1fr] lg:gap-14"><div className="relative aspect-[4/3] overflow-hidden rounded-2xl border border-jade/10 shadow-editorial-lift"><Image src="/images/cities/chiang-rai/attractions/Mae Fah Luang Art and Culture Park.webp" alt="Cultural landscape in Chiang Rai" fill sizes="48vw" className="object-cover"/></div><div><p className="eyebrow">Compact centre, dispersed province</p><h2 className="font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] text-jade sm:text-[3.6rem]">Walk the evening. Drive the itinerary.</h2><p className="mt-5 text-sm leading-7 text-charcoal/62">Central Chiang Rai is manageable, but Wat Rong Khun, Baan Dam and the northern routes sit in different directions. Grouping geography matters more than the raw kilometre count.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{movement.map(({icon:Icon,title,copy})=><article key={title} className="rounded-xl border border-jade/10 bg-white p-4"><Icon size={19} className="text-jade" strokeWidth={1.55}/><h3 className="mt-3 font-display text-xl font-semibold text-jade">{title}</h3><p className="mt-2 text-[10px] leading-5 text-charcoal/55">{copy}</p></article>)}</div><a href={transportHref} target="_blank" rel={AFFILIATE_REL} className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Check current intercity transport on 12Go <ExternalLink size={14}/></a></div></div></section>

      <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="grid gap-8 lg:grid-cols-[0.72fr_1.5fr] lg:gap-14"><div><p className="eyebrow">Before you go</p><h2 className="font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] text-jade sm:text-[3.55rem]">Respect the sites. Edit the road day.</h2><p className="mt-5 text-sm leading-7 text-charcoal/62">The strongest Chiang Rai trip distinguishes active worship, contemporary art, museum context and provincial history.</p></div><div className="grid gap-3 sm:grid-cols-2">{practical.map(({icon:Icon,title,copy})=><article key={title} className="rounded-xl border border-jade/10 bg-white p-5 shadow-[0_5px_18px_rgba(18,63,54,0.035)]"><span className="grid h-10 w-10 place-items-center rounded-lg border border-jade/10 bg-jade/[0.025] text-jade"><Icon size={20} strokeWidth={1.55}/></span><h3 className="mt-4 font-display text-2xl font-semibold text-jade">{title}</h3><p className="mt-2 text-[11px] leading-5 text-charcoal/57">{copy}</p></article>)}</div></div><div className="mt-9 rounded-2xl border border-jade/10 bg-white px-6 py-7 sm:px-8"><div className="grid gap-6 lg:grid-cols-[0.72fr_1.4fr] lg:items-center"><div><p className="eyebrow">Useful arrival reset</p><h3 className="font-display text-[2.35rem] font-semibold leading-[0.95] text-jade">Keep the first Chiang Rai evening local.</h3></div><ul className="grid gap-3 text-xs leading-5 text-charcoal/60 sm:grid-cols-2">{['Save the exact hotel pin and arrival transfer.','Choose tomorrow’s north or south cluster.','Check live air quality and mountain visibility.','Plan one nearby Northern dinner and an easy return.'].map(item=><li key={item} className="flex gap-2.5"><Check size={15} className="mt-0.5 shrink-0 text-saffron-dark"/>{item}</li>)}</ul></div></div></div></section>

      <section className="section-divider-bottom bg-jade-dark py-12 text-white lg:py-16"><div className="container-custom grid gap-9 lg:grid-cols-[0.68fr_1.5fr] lg:items-center lg:gap-14"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-saffron-light">Continue planning</p><h2 className="mt-3 font-display text-[3rem] font-semibold leading-[0.93] tracking-[-0.04em]">Build the rest of your Chiang Rai trip.</h2><p className="mt-5 text-sm leading-7 text-white/65">Move into specialist owners for deeper site, stay and season decisions without repeating one generic temple list.</p></div><div className="grid gap-3 sm:grid-cols-3">{[{title:'Things to do',copy:'Art sites, temples and selected province routes.',href:'/city/chiang-rai/attractions/'},{title:'Where to stay',copy:'Compare the centre, river and quieter bases.',href:'/best-hotels/chiang-rai/'},{title:'Best time',copy:'Plan around temperature, rain and live air quality.',href:'/city/chiang-rai/weather/'}].map(item=><Link key={item.title} href={item.href} className="group rounded-xl border border-white/12 bg-white/[0.07] p-5 backdrop-blur-sm transition hover:-translate-y-1 hover:bg-white/[0.11]"><h3 className="font-display text-2xl font-semibold">{item.title}</h3><p className="mt-2 min-h-10 text-[10px] leading-5 text-white/57">{item.copy}</p><span className="mt-5 flex items-center justify-between text-[10px] font-bold text-saffron-light">Open guide <ArrowRight size={14} className="transition group-hover:translate-x-1"/></span></Link>)}</div></div></section>
    </>
  );
}
