import Image from 'next/image';
import Link from 'next/link';
import {
  ArrowRight,
  BedDouble,
  BookOpen,
  BusFront,
  CalendarDays,
  Check,
  ExternalLink,
  Footprints,
  MapPin,
  Route,
  ShieldCheck,
  Soup,
  TrainFront,
  Waves,
} from 'lucide-react';
import { StoryDottedRoute } from '../visuals/StoryDottedRoute';

interface KanchanaburiDestinationOverviewProps { activitiesHref: string; hotelsHref: string; transportHref: string; }
const AFFILIATE_REL = 'noopener noreferrer nofollow sponsored';

const tripShapes = [
  { icon: TrainFront, title: 'Focused day trip', label: 'History cluster only', copy: 'A long Bangkok day can introduce the bridge, cemetery and one museum. It should not pretend to cover the province as well.' },
  { icon: BedDouble, title: 'One night in town', label: 'Better historical pace', copy: 'Adds an evening and removes the same-day return deadline, giving the memorial layer the time and tone it deserves.' },
  { icon: Waves, title: 'Two or three nights', label: 'Best first balance', copy: 'Combine a respectful town history day with a separate Erawan, railway or upriver day—without making them compete.' },
  { icon: Route, title: 'Split town and river', label: 'Deeper province stay', copy: 'Start near the history sites, then move upriver when Sai Yok, a raft lodge or the western railway corridor is the real second chapter.' },
] as const;

const experiences = [
  { title: 'Build a remembrance sequence', tag: 'Town history', copy: 'Use a museum and cemetery to establish the human history before treating the bridge as a standalone photo landmark.', image: '/images/redesign/kanchanaburi-history-route-v2.webp', href: '/city/kanchanaburi/attractions/' },
  { title: 'Follow the surviving railway', tag: 'Western corridor', copy: 'A railway segment and the Wampo viaduct reveal geography, but the journey needs historical context beyond scenery.', image: '/images/redesign/kanchanaburi-wampo-railway.webp', href: '/city/kanchanaburi/attractions/' },
  { title: 'Give Erawan its own day', tag: 'Nature route', copy: 'The waterfall trail, heat, changing conditions and journey from town deserve a real block—not a rushed afternoon after memorial sites.', image: '/images/redesign/kanchanaburi-erawan-waterfall.webp', href: '/city/kanchanaburi/attractions/' },
  { title: 'Recognise the province scale', tag: 'Far-west extension', copy: 'Sangkhlaburi and the Mon Bridge belong to a separate far-west stay. They are not a casual addition to a short Kanchanaburi town visit.', image: '/images/redesign/kanchanaburi-mon-bridge.webp', href: '/city/kanchanaburi/attractions/' },
] as const;

const itinerary = [
  { day: 'Day 1', title: 'History with context', route: 'Railway centre or museum → cemetery → bridge', note: 'Start with interpretation and remembrance. Keep the bridge as part of the story rather than the entire story.' },
  { day: 'Day 2', title: 'Choose water or rail', route: 'Erawan day OR western railway corridor', note: 'Pick one geography. Combining both can reduce a nature walk and a historical route to transfer time.' },
  { day: 'Day 3', title: 'Slow the river down', route: 'Upriver stay → nearby landscape → unhurried return', note: 'Use a third day for river atmosphere or Sai Yok, not as permission to stack every remaining province stop.' },
] as const;

const movement = [
  { icon: Footprints, title: 'Walking', copy: 'Useful within individual town pockets, but the bridge, cemetery and hotel zones do not form one seamless pedestrian centre.' },
  { icon: MapPin, title: 'Short local rides', copy: 'Useful for town gaps when availability suits. Confirm the return plan and do not assume app coverage far upriver.' },
  { icon: TrainFront, title: 'Railway segments', copy: 'Part of the experience and the historical geography, but not a flexible hop-on network for every attraction.' },
  { icon: BusFront, title: 'Bus, driver or tour', copy: 'Better for Bangkok transfers and selected westbound days. Compare the complete route and actual time at each stop.' },
] as const;

const practical = [
  { icon: BookOpen, title: 'Lead with evidence', copy: 'Use established museum, memorial and cemetery sources. Popular film language should not replace the documented human history.' },
  { icon: ShieldCheck, title: 'Behave as a visitor', copy: 'Cemeteries and memorial sites require quiet, respectful conduct. Avoid staged poses that turn remembrance into a backdrop.' },
  { icon: Waves, title: 'Check Erawan conditions', copy: 'Trail access, water flow, swimming rules and park instructions vary. Use current park information close to the visit.' },
  { icon: CalendarDays, title: 'Plan the return first', copy: 'Town, Erawan, Sai Yok and far-west stays have different transport realities. Confirm the final connection before adding a stop.' },
] as const;

export function KanchanaburiDestinationOverview({ activitiesHref, hotelsHref, transportHref }: KanchanaburiDestinationOverviewProps) {
  return <>
    <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="mb-8 grid gap-5 lg:grid-cols-[0.72fr_1.28fr] lg:items-end lg:gap-14"><div><p className="eyebrow">Choose the right scale</p><h2 className="font-display text-[3.05rem] font-semibold leading-[0.9] tracking-[-0.04em] text-jade sm:text-[3.7rem]">History in town. Nature and river life farther west.</h2></div><p className="max-w-2xl text-sm leading-7 text-charcoal/62">Kanchanaburi is both a provincial city and the gateway to a long western corridor. A strong trip separates the memorial cluster, Erawan, surviving railway and upriver landscapes instead of selling them as one easy day.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{tripShapes.map(({icon:Icon,title,label,copy})=><article key={title} className="rounded-xl border border-jade/10 bg-white p-5 shadow-[0_5px_18px_rgba(18,63,54,0.04)]"><span className="grid h-10 w-10 place-items-center rounded-lg border border-saffron/25 bg-saffron/[0.05] text-saffron-dark"><Icon size={20} strokeWidth={1.55}/></span><p className="mt-5 text-[9px] font-bold uppercase tracking-[0.18em] text-saffron-dark">{label}</p><h3 className="mt-1 font-display text-2xl font-semibold text-jade">{title}</h3><p className="mt-3 text-[11px] leading-5 text-charcoal/58">{copy}</p></article>)}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-jade/10 bg-white px-5 py-4"><p className="text-xs leading-5 text-charcoal/56"><strong className="text-jade">Town or upriver?</strong> Stay near town for history access; move west for river atmosphere. A scenic lodge is not automatically convenient for the memorial cluster.</p><a href={hotelsHref} target="_blank" rel={AFFILIATE_REL} className="inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Check current hotel prices on Trip.com <ExternalLink size={14}/></a></div></div></section>

    <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="mb-7 flex items-end justify-between gap-5"><div><p className="eyebrow">Four different geographies</p><h2 className="font-display text-[2.9rem] font-semibold leading-none tracking-[-0.04em] text-jade sm:text-[3.4rem]">Do not flatten the province into a checklist.</h2></div><Link href="/city/kanchanaburi/attractions/" className="hidden items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark sm:flex">All Kanchanaburi attractions <ArrowRight size={15}/></Link></div><div className="scrollbar-hide flex snap-x gap-4 overflow-x-auto pb-2 sm:grid sm:grid-cols-2 sm:overflow-visible lg:grid-cols-4">{experiences.map(item=><Link key={item.title} href={item.href} className="group min-w-[80vw] snap-start overflow-hidden rounded-xl border border-jade/10 bg-white shadow-[0_5px_18px_rgba(18,63,54,0.04)] transition hover:-translate-y-1 hover:shadow-xl sm:min-w-0"><div className="relative aspect-[4/2.9] overflow-hidden"><Image src={item.image} alt={item.title} fill sizes="(min-width:1024px) 25vw, 80vw" className="object-cover transition duration-500 group-hover:scale-[1.035]"/><span className="absolute left-3 top-3 rounded-md bg-jade/88 px-2.5 py-1 text-[8px] font-bold uppercase tracking-[0.17em] text-white backdrop-blur">{item.tag}</span></div><div className="p-4"><h3 className="font-display text-[1.35rem] font-semibold leading-tight text-jade">{item.title}</h3><p className="mt-2 text-[11px] leading-5 text-charcoal/58">{item.copy}</p><span className="mt-4 flex items-center justify-between border-t border-jade/8 pt-3 text-[10px] font-bold text-jade">Open the guide <ArrowRight size={14}/></span></div></Link>)}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-jade/10 bg-white px-5 py-4"><p className="text-xs leading-5 text-charcoal/56"><strong className="text-jade">Comparing organised days?</strong> Check the museum depth, railway segment, Erawan time and Bangkok return—not the stop count.</p><a href={activitiesHref} target="_blank" rel={AFFILIATE_REL} className="inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Check current options on Klook <ExternalLink size={14}/></a></div></div></section>

    <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="relative overflow-hidden rounded-2xl bg-jade-dark text-white shadow-editorial-lift"><Image src="/images/redesign/kanchanaburi-history-route-v2.webp" alt="River Kwai railway bridge and landscape in Kanchanaburi" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-jade-dark via-jade-dark/84 to-jade-dark/10"/><div className="relative grid min-h-[405px] items-center gap-8 px-7 py-10 sm:px-10 lg:grid-cols-[0.74fr_1.2fr] lg:px-14"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-saffron-light">The context-first route</p><h2 className="mt-3 max-w-md font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] sm:text-[3.7rem]">Understand before you photograph.</h2><p className="mt-5 max-w-md text-sm leading-7 text-white/70">Begin with documented history and individual lives, continue through remembrance, then see the bridge and surviving railway landscape. The order changes what the landmark means.</p></div><div className="relative hidden min-h-[250px] lg:block"><StoryDottedRoute className="absolute left-0 top-14 h-40 w-72 opacity-90"/><div className="absolute right-0 top-0 grid w-[390px] grid-cols-2 gap-3">{['Museum context','War cemetery','Bridge landscape','Railway corridor'].map((label,index)=><div key={label} className="rounded-xl border border-white/15 bg-white/[0.09] p-4 backdrop-blur-sm"><span className="text-[9px] font-bold uppercase tracking-[0.18em] text-saffron-light">Step {index+1}</span><strong className="mt-1.5 block font-display text-lg font-semibold">{label}</strong></div>)}</div></div></div></div></div></section>

    <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom grid gap-10 lg:grid-cols-[0.55fr_1.8fr] lg:gap-14"><div><p className="eyebrow">A realistic first visit</p><h2 className="font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] text-jade sm:text-[3.55rem]">Three days, without emotional or road fatigue.</h2><p className="mt-5 text-sm leading-7 text-charcoal/62">Two full days can work. A third creates room for an upriver stay or slower railway route without making remembrance and recreation compete.</p></div><div className="relative grid gap-4 sm:grid-cols-3"><div className="pointer-events-none absolute left-8 right-8 top-8 hidden border-t border-dashed border-saffron/55 sm:block"/>{itinerary.map((item,index)=><article key={item.day} className="relative rounded-xl border border-jade/10 bg-white p-5 shadow-[0_5px_18px_rgba(18,63,54,0.035)]"><span className="grid h-8 w-8 place-items-center rounded-full border border-saffron/45 bg-[#fcfaf6] text-[10px] font-extrabold text-saffron-dark">{index+1}</span><p className="mt-5 text-[9px] font-bold uppercase tracking-[0.18em] text-saffron-dark">{item.day}</p><h3 className="mt-1 font-display text-2xl font-semibold text-jade">{item.title}</h3><p className="mt-4 text-xs font-bold leading-5 text-jade">{item.route}</p><p className="mt-3 text-[11px] leading-5 text-charcoal/56">{item.note}</p></article>)}</div></div></section>

    <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom grid gap-5 lg:grid-cols-2"><article className="overflow-hidden rounded-2xl border border-jade/10 bg-white shadow-[0_6px_22px_rgba(18,63,54,0.045)]"><div className="relative aspect-[16/8.5]"><Image src="/images/redesign/kanchanaburi-upriver-stay-v2.webp" alt="Quiet upriver lodge in Kanchanaburi province" fill sizes="50vw" className="object-cover"/></div><div className="p-6 sm:p-8"><p className="eyebrow">Change the pace, not only the postcode</p><h2 className="font-display text-[2.75rem] font-semibold leading-[0.95] tracking-[-0.035em] text-jade">An upriver night is a different trip.</h2><p className="mt-4 text-sm leading-7 text-charcoal/62">Floating and riverside stays exchange town convenience for landscape and quiet. Verify the transfer, meal setup and route back before choosing the photo.</p><a href={hotelsHref} target="_blank" rel={AFFILIATE_REL} className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Check current river-stay prices on Trip.com <ExternalLink size={14}/></a></div></article><article className="overflow-hidden rounded-2xl border border-jade/10 bg-white shadow-[0_6px_22px_rgba(18,63,54,0.045)]"><div className="relative aspect-[16/8.5]"><Image src="/images/redesign/kanchanaburi-riverside-food.webp" alt="Riverside food in Kanchanaburi" fill sizes="50vw" className="object-cover"/></div><div className="p-6 sm:p-8"><p className="eyebrow">Keep one evening in town</p><h2 className="font-display text-[2.75rem] font-semibold leading-[0.95] tracking-[-0.035em] text-jade">Dinner should not become another road mission.</h2><p className="mt-4 text-sm leading-7 text-charcoal/62">Town nights suit local restaurants and a low-key river evening; remote lodges often work around their own dining setup. Plan food with the stay geography.</p><Link href="/city/kanchanaburi/food/" className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark"><Soup size={15}/> Plan where to eat in Kanchanaburi <ArrowRight size={15}/></Link></div></article></div></section>

    <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom grid items-center gap-9 lg:grid-cols-[0.9fr_1.1fr] lg:gap-14"><div className="relative aspect-[4/3] overflow-hidden rounded-2xl border border-jade/10 shadow-editorial-lift"><Image src="/images/redesign/kanchanaburi-wampo-railway.webp" alt="Train on the Wampo viaduct in Kanchanaburi" fill sizes="48vw" className="object-cover"/></div><div><p className="eyebrow">Distance follows the river west</p><h2 className="font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] text-jade sm:text-[3.6rem]">Plan the corridor, not isolated pins.</h2><p className="mt-5 text-sm leading-7 text-charcoal/62">The city, Erawan, Sai Yok and far-west province do not share one convenient transport grid. Your return connection belongs in the plan before the attraction list.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{movement.map(({icon:Icon,title,copy})=><article key={title} className="rounded-xl border border-jade/10 bg-white p-4"><Icon size={19} className="text-jade" strokeWidth={1.55}/><h3 className="mt-3 font-display text-xl font-semibold text-jade">{title}</h3><p className="mt-2 text-[10px] leading-5 text-charcoal/55">{copy}</p></article>)}</div><a href={transportHref} target="_blank" rel={AFFILIATE_REL} className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Check current Bangkok–Kanchanaburi transport on 12Go <ExternalLink size={14}/></a></div></div></section>

    <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="grid gap-8 lg:grid-cols-[0.72fr_1.5fr] lg:gap-14"><div><p className="eyebrow">Before you go</p><h2 className="font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] text-jade sm:text-[3.55rem]">Travel with context and a credible return.</h2><p className="mt-5 text-sm leading-7 text-charcoal/62">Kanchanaburi asks for two kinds of care: respect at remembrance sites and realistic planning across a large western province.</p></div><div className="grid gap-3 sm:grid-cols-2">{practical.map(({icon:Icon,title,copy})=><article key={title} className="rounded-xl border border-jade/10 bg-white p-5 shadow-[0_5px_18px_rgba(18,63,54,0.035)]"><span className="grid h-10 w-10 place-items-center rounded-lg border border-jade/10 bg-jade/[0.025] text-jade"><Icon size={20} strokeWidth={1.55}/></span><h3 className="mt-4 font-display text-2xl font-semibold text-jade">{title}</h3><p className="mt-2 text-[11px] leading-5 text-charcoal/57">{copy}</p></article>)}</div></div><div className="mt-9 rounded-2xl border border-jade/10 bg-white px-6 py-7 sm:px-8"><div className="grid gap-6 lg:grid-cols-[0.72fr_1.4fr] lg:items-center"><div><p className="eyebrow">Useful arrival reset</p><h3 className="font-display text-[2.35rem] font-semibold leading-[0.95] text-jade">Keep the first Kanchanaburi evening simple.</h3></div><ul className="grid gap-3 text-xs leading-5 text-charcoal/60 sm:grid-cols-2">{['Save the exact hotel pin and town transport plan.','Choose tomorrow’s history or nature geography.','Check current park or railway conditions.','Confirm the next-day return before moving upriver.'].map(item=><li key={item} className="flex gap-2.5"><Check size={15} className="mt-0.5 shrink-0 text-saffron-dark"/>{item}</li>)}</ul></div></div></div></section>

    <section className="section-divider-bottom bg-jade-dark py-12 text-white lg:py-16"><div className="container-custom grid gap-9 lg:grid-cols-[0.68fr_1.5fr] lg:items-center lg:gap-14"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-saffron-light">Continue planning</p><h2 className="mt-3 font-display text-[3rem] font-semibold leading-[0.93] tracking-[-0.04em]">Build the rest of your Kanchanaburi trip.</h2><p className="mt-5 text-sm leading-7 text-white/65">Use specialist owners for detailed history, Erawan logistics and stay choices without turning the broad page into an unverified timetable.</p></div><div className="grid gap-3 sm:grid-cols-3">{[{title:'Things to do',copy:'History sites, nature days and western routes.',href:'/city/kanchanaburi/attractions/'},{title:'Where to stay',copy:'Compare town, bridge side and upriver lodges.',href:'/best-hotels/kanchanaburi/'},{title:'Best time',copy:'Plan heat, rain, water flow and outdoor days.',href:'/city/kanchanaburi/best-time-to-visit/'}].map(item=><Link key={item.title} href={item.href} className="group rounded-xl border border-white/12 bg-white/[0.07] p-5 backdrop-blur-sm transition hover:-translate-y-1 hover:bg-white/[0.11]"><h3 className="font-display text-2xl font-semibold">{item.title}</h3><p className="mt-2 min-h-10 text-[10px] leading-5 text-white/57">{item.copy}</p><span className="mt-5 flex items-center justify-between text-[10px] font-bold text-saffron-light">Open guide <ArrowRight size={14} className="transition group-hover:translate-x-1"/></span></Link>)}</div></div></section>
  </>;
}
