import Image from 'next/image';
import Link from 'next/link';
import {
  ArrowRight,
  BusFront,
  CalendarDays,
  Check,
  ExternalLink,
  Footprints,
  MapPin,
  Route,
  ShieldCheck,
  Soup,
  Sun,
  Waves,
} from 'lucide-react';
import { StoryDottedRoute } from '../visuals/StoryDottedRoute';

interface KohSamuiDestinationOverviewProps {
  activitiesHref: string;
  hotelsHref: string;
  transportHref: string;
}

const AFFILIATE_REL = 'noopener noreferrer nofollow sponsored';

const zones = [
  { title: 'Chaweng', label: 'Energy & convenience', copy: 'The easiest first base for a long beach, dense dining and evening choice. Stay here when walkable convenience matters more than quiet.', image: '/images/redesign/koh-samui-stay-chaweng.webp' },
  { title: 'Lamai', label: 'A calmer all-rounder', copy: 'A useful middle ground: enough restaurants and beach life for an easy stay, but generally less intense than central Chaweng.', image: '/images/redesign/koh-samui-stay-lamai.webp' },
  { title: 'Bophut', label: 'Food & evening strolls', copy: 'Fisherman’s Village gives the north coast a polished evening rhythm. The exact hotel pin still matters because the wider Bophut area is spread out.', image: '/images/redesign/koh-samui-fishermans-village.webp' },
  { title: 'Choeng Mon', label: 'Compact & comfortable', copy: 'A smaller northeast beach zone that suits couples and families seeking resort comfort without Chaweng’s scale.', image: '/images/redesign/koh-samui-stay-choeng-mon.webp' },
  { title: 'Mae Nam', label: 'Slow north coast', copy: 'Choose Mae Nam for a quieter, longer-stay rhythm. Dining is more dispersed, so check what is genuinely walkable from the hotel.', image: '/images/redesign/koh-samui-stay-maenam.webp' },
  { title: 'Taling Ngam', label: 'Remote sunsets', copy: 'The west and southwest reward travellers who want privacy and resort time. Every dinner, tour pickup and island crossing needs more planning.', image: '/images/redesign/koh-samui-stay-taling-ngam.webp' },
] as const;

const experiences = [
  { title: 'Choose one proper beach day', tag: 'Island coast', copy: 'Give the beach you selected enough time to become part of the trip. Samui works better as a stay than as a rapid coastline checklist.', image: '/images/redesign/koh-samui-attractions-hero.webp', href: '/city/koh-samui/attractions/' },
  { title: 'Pair the northeast temples', tag: 'Culture cluster', copy: 'Big Buddha and Wat Plai Laem belong in one compact route, with appropriate dress and enough time to look beyond a quick photo.', image: '/images/redesign/koh-samui-temple-lake.webp', href: '/city/koh-samui/attractions/' },
  { title: 'Spend an evening in Bophut', tag: 'Food & atmosphere', copy: 'Fisherman’s Village works as an evening cluster for dining and a waterfront walk, especially when your north-coast base keeps the transfer short.', image: '/images/redesign/koh-samui-fishermans-village.webp', href: '/city/koh-samui/food/' },
  { title: 'Make Ang Thong the boat day', tag: 'Marine park', copy: 'For many first trips, one well-chosen Ang Thong day adds more range than stacking several minor excursions. Compare boat format and conditions.', image: '/images/redesign/koh-samui-ang-thong.webp', href: '/city/koh-samui/attractions/' },
] as const;

const itinerary = [
  { day: 'Day 1', title: 'Land in your own zone', route: 'Arrival → chosen beach → nearby dinner', note: 'Do not spend arrival day crossing the island. Learn what is actually walkable around your hotel first.' },
  { day: 'Day 2', title: 'Beach & local evening', route: 'Slow beach morning → one nearby stop → local sunset', note: 'Keep the day inside one coast zone and let the first full day feel like an island stay.' },
  { day: 'Day 3', title: 'A focused island loop', route: 'Temple pair → interior stop → Lamai or Bophut', note: 'Choose two or three connected anchors. The ring road makes a loop possible, not automatically relaxing.' },
  { day: 'Day 4', title: 'One serious sea day', route: 'Ang Thong or another researched boat route', note: 'Check live conditions, pickup geography, boat type and cancellation terms before treating the route as fixed.' },
  { day: 'Day 5', title: 'Leave room to return', route: 'Favourite beach → spa or food → easy final night', note: 'Use the final day for the part of Samui you genuinely liked instead of adding another distant landmark.' },
] as const;

const transport = [
  { icon: Footprints, title: 'Walking', copy: 'Useful within parts of Chaweng, Lamai and Fisherman’s Village. It is not an island-wide solution.' },
  { icon: BusFront, title: 'Songthaew', copy: 'Shared pickup trucks can cover parts of the ring road, but routes, hours and fares are not a fixed metro system.' },
  { icon: MapPin, title: 'Taxi & ride-hailing', copy: 'Practical for short stays. Confirm pickup, fare and the return plan before heading to a remote coast.' },
  { icon: Route, title: 'Scooter or car', copy: 'Only with the correct licence, insurance and experience. A scooter is optional, not a requirement for a good trip.' },
] as const;

const practical = [
  { icon: Waves, title: 'The Gulf has its own season', copy: 'Do not copy Phuket’s weather calendar onto Samui. Use monthly guidance and live forecasts for beach and boat decisions.' },
  { icon: ShieldCheck, title: 'Treat the road seriously', copy: 'Short map distances can still involve fast traffic, rain and unfamiliar junctions. Choose safe transport before convenience.' },
  { icon: Soup, title: 'Plan food by coast', copy: 'A famous restaurant is not worth two long transfers. Build evenings around Chaweng, Lamai or Bophut according to your base.' },
  { icon: Sun, title: 'Keep one flexible day', copy: 'Sea conditions, rain and energy can change the plan. A spare beach or spa block is useful structure, not wasted time.' },
] as const;

export function KohSamuiDestinationOverview({ activitiesHref, hotelsHref, transportHref }: KohSamuiDestinationOverviewProps) {
  return (
    <>
      <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16">
        <div className="container-custom">
          <div className="mb-8 grid gap-5 lg:grid-cols-[0.72fr_1.28fr] lg:items-end lg:gap-14">
            <div><p className="eyebrow">Choose your coast</p><h2 className="font-display text-[3.05rem] font-semibold leading-[0.9] tracking-[-0.04em] text-jade sm:text-[3.7rem]">Your beach zone shapes every day.</h2></div>
            <p className="max-w-2xl text-sm leading-7 text-charcoal/62">Koh Samui is not one walkable resort town. Chaweng, Lamai, Bophut and the quieter coasts each create a different trip, so choose the morning and evening rhythm first—and only then the hotel.</p>
          </div>
          <div className="scrollbar-hide flex snap-x gap-4 overflow-x-auto pb-2 sm:grid sm:grid-cols-2 sm:overflow-visible lg:grid-cols-3">
            {zones.map(zone => <article key={zone.title} className="min-w-[80vw] snap-start overflow-hidden rounded-xl border border-jade/10 bg-white shadow-[0_5px_18px_rgba(18,63,54,0.04)] sm:min-w-0"><div className="relative aspect-[16/7.2]"><Image src={zone.image} alt={`${zone.title}, Koh Samui`} fill sizes="(min-width:1024px) 33vw, 80vw" className="object-cover" /></div><div className="p-5"><p className="text-[9px] font-bold uppercase tracking-[0.18em] text-saffron-dark">{zone.label}</p><h3 className="mt-1 font-display text-2xl font-semibold text-jade">{zone.title}</h3><p className="mt-3 text-[11px] leading-5 text-charcoal/58">{zone.copy}</p></div></article>)}
          </div>
          <div className="mt-6 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-jade/10 bg-white px-5 py-4"><p className="text-xs leading-5 text-charcoal/56"><strong className="text-jade">Check the exact pin.</strong> A hotel sold as “Bophut” or “Lamai” may sit well beyond the walkable centre you imagined.</p><a href={hotelsHref} target="_blank" rel={AFFILIATE_REL} className="inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Check current hotel prices on Trip.com <ExternalLink size={14} /></a></div>
        </div>
      </section>

      <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="mb-7 flex items-end justify-between gap-5"><div><p className="eyebrow">Four island rhythms</p><h2 className="font-display text-[2.9rem] font-semibold leading-none tracking-[-0.04em] text-jade sm:text-[3.4rem]">More than pool time, without overplanning.</h2></div><Link href="/city/koh-samui/attractions/" className="hidden items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark sm:flex">All Koh Samui attractions <ArrowRight size={15} /></Link></div><div className="scrollbar-hide flex snap-x gap-4 overflow-x-auto pb-2 sm:grid sm:grid-cols-2 sm:overflow-visible lg:grid-cols-4">{experiences.map(item=><Link key={item.title} href={item.href} className="group min-w-[80vw] snap-start overflow-hidden rounded-xl border border-jade/10 bg-white shadow-[0_5px_18px_rgba(18,63,54,0.04)] transition hover:-translate-y-1 hover:shadow-xl sm:min-w-0"><div className="relative aspect-[4/2.9] overflow-hidden"><Image src={item.image} alt={item.title} fill sizes="(min-width:1024px) 25vw, 80vw" className="object-cover transition duration-500 group-hover:scale-[1.035]"/><span className="absolute left-3 top-3 rounded-md bg-jade/88 px-2.5 py-1 text-[8px] font-bold uppercase tracking-[0.17em] text-white backdrop-blur">{item.tag}</span></div><div className="p-4"><h3 className="font-display text-[1.35rem] font-semibold leading-tight text-jade">{item.title}</h3><p className="mt-2 text-[11px] leading-5 text-charcoal/58">{item.copy}</p><span className="mt-4 flex items-center justify-between border-t border-jade/8 pt-3 text-[10px] font-bold text-jade">Open the guide <ArrowRight size={14}/></span></div></Link>)}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-jade/10 bg-white px-5 py-4"><p className="text-xs leading-5 text-charcoal/56"><strong className="text-jade">Comparing boat days?</strong> Check marine-park fees, boat type, pickup coast and cancellation terms.</p><a href={activitiesHref} target="_blank" rel={AFFILIATE_REL} className="inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Check current options on Klook <ExternalLink size={14}/></a></div></div></section>

      <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="relative overflow-hidden rounded-2xl bg-jade-dark text-white shadow-editorial-lift"><Image src="/images/redesign/koh-samui-zones-banner.webp" alt="Koh Samui coast at sunset" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-jade-dark via-jade-dark/86 to-jade-dark/12"/><div className="relative grid min-h-[390px] items-center gap-8 px-7 py-10 sm:px-10 lg:grid-cols-[0.72fr_1.2fr] lg:px-14"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-saffron-light">The island-loop rule</p><h2 className="mt-3 max-w-md font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] sm:text-[3.7rem]">One loop. Three anchors. No road-trip marathon.</h2><p className="mt-5 max-w-md text-sm leading-7 text-white/70">Use Samui’s ring road to connect one temple cluster, one interior or south-coast stop and one evening area. A loop is useful only when the road does not replace the island.</p></div><div className="relative hidden min-h-[250px] lg:block"><StoryDottedRoute className="absolute left-0 top-14 h-40 w-72 opacity-90"/><div className="absolute right-0 top-0 grid w-[390px] grid-cols-2 gap-3">{['Northeast temples','Chosen beach','Interior stop','Bophut or Lamai'].map((label,index)=><div key={label} className="rounded-xl border border-white/15 bg-white/[0.09] p-4 backdrop-blur-sm"><span className="text-[9px] font-bold uppercase tracking-[0.18em] text-saffron-light">Anchor {index+1}</span><strong className="mt-1.5 block font-display text-lg font-semibold">{label}</strong></div>)}</div></div></div></div></div></section>

      <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom grid gap-10 lg:grid-cols-[0.55fr_1.8fr] lg:gap-14"><div><p className="eyebrow">A realistic first visit</p><h2 className="font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] text-jade sm:text-[3.55rem]">Five days, with island time intact.</h2><p className="mt-5 text-sm leading-7 text-charcoal/62">Four full days can work; five gives weather flexibility and a slower final day. Stay longer if the beach and hotel are the destination, not to multiply transfers.</p></div><div className="relative grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><div className="pointer-events-none absolute left-8 right-8 top-8 hidden border-t border-dashed border-saffron/55 lg:block"/>{itinerary.map((item,index)=><article key={item.day} className="relative rounded-xl border border-jade/10 bg-white p-5 shadow-[0_5px_18px_rgba(18,63,54,0.035)]"><span className="grid h-8 w-8 place-items-center rounded-full border border-saffron/45 bg-[#fcfaf6] text-[10px] font-extrabold text-saffron-dark">{index+1}</span><p className="mt-5 text-[9px] font-bold uppercase tracking-[0.18em] text-saffron-dark">{item.day}</p><h3 className="mt-1 font-display text-[1.3rem] font-semibold text-jade">{item.title}</h3><p className="mt-4 text-[11px] font-bold leading-5 text-jade">{item.route}</p><p className="mt-3 text-[10px] leading-5 text-charcoal/56">{item.note}</p></article>)}</div></div></section>

      <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom grid gap-5 lg:grid-cols-2"><article className="overflow-hidden rounded-2xl border border-jade/10 bg-white shadow-[0_6px_22px_rgba(18,63,54,0.045)]"><div className="relative aspect-[16/8.5]"><Image src="/images/redesign/koh-samui-food.webp" alt="Food and evening atmosphere on Koh Samui" fill sizes="50vw" className="object-cover"/></div><div className="p-6 sm:p-8"><p className="eyebrow">Eat by neighbourhood</p><h2 className="font-display text-[2.75rem] font-semibold leading-[0.95] tracking-[-0.035em] text-jade">The best dinner is not always across the island.</h2><p className="mt-4 text-sm leading-7 text-charcoal/62">Chaweng, Lamai and Fisherman’s Village each offer a different evening. Use the food owner to choose a cluster that matches your coast rather than commuting for every saved restaurant.</p><Link href="/city/koh-samui/food/" className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Plan where to eat on Koh Samui <ArrowRight size={15}/></Link></div></article><article className="overflow-hidden rounded-2xl border border-jade/10 bg-white shadow-[0_6px_22px_rgba(18,63,54,0.045)]"><div className="relative aspect-[16/8.5]"><Image src="/images/redesign/koh-samui-weather-green-season.webp" alt="Changing weather over the Gulf of Thailand" fill sizes="50vw" className="object-cover"/></div><div className="p-6 sm:p-8"><p className="eyebrow">Plan for the Gulf</p><h2 className="font-display text-[2.75rem] font-semibold leading-[0.95] tracking-[-0.035em] text-jade">Samui is not Phuket with a different name.</h2><p className="mt-4 text-sm leading-7 text-charcoal/62">Koh Samui’s Gulf location creates a different rainfall pattern from the Andaman coast. Monthly averages guide the trip; live sea and weather conditions still decide the day.</p><Link href="/city/koh-samui/weather/" className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark"><CalendarDays size={15}/> Compare Koh Samui by month <ArrowRight size={15}/></Link></div></article></div></section>

      <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom grid items-center gap-9 lg:grid-cols-[0.9fr_1.1fr] lg:gap-14"><div className="relative aspect-[4/3] overflow-hidden rounded-2xl border border-jade/10 shadow-editorial-lift"><Image src="/images/redesign/koh-samui-hotels-hero.webp" alt="Arrival and movement planning on Koh Samui" fill sizes="48vw" className="object-cover"/></div><div><p className="eyebrow">Airport, ferry and ring road</p><h2 className="font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] text-jade sm:text-[3.6rem]">Choose the arrival that fits the whole route.</h2><p className="mt-5 text-sm leading-7 text-charcoal/62">A direct flight is convenient, while ferry combinations can fit a wider Gulf or overland route. Compare the complete door-to-door journey—including the final island transfer.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{transport.map(({icon:Icon,title,copy})=><article key={title} className="rounded-xl border border-jade/10 bg-white p-4"><Icon size={19} className="text-jade" strokeWidth={1.55}/><h3 className="mt-3 font-display text-xl font-semibold text-jade">{title}</h3><p className="mt-2 text-[10px] leading-5 text-charcoal/55">{copy}</p></article>)}</div><a href={transportHref} target="_blank" rel={AFFILIATE_REL} className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-jade hover:text-saffron-dark">Check current ferry and transport options on 12Go <ExternalLink size={14}/></a></div></div></section>

      <section className="section-divider-bottom bg-[#fcfaf6] py-12 lg:py-16"><div className="container-custom"><div className="grid gap-8 lg:grid-cols-[0.72fr_1.5fr] lg:gap-14"><div><p className="eyebrow">Before you go</p><h2 className="font-display text-[3rem] font-semibold leading-[0.92] tracking-[-0.04em] text-jade sm:text-[3.55rem]">Good island planning stays flexible.</h2><p className="mt-5 text-sm leading-7 text-charcoal/62">Your coast, the live conditions and a safe return plan matter more than squeezing one extra pin into the day.</p></div><div className="grid gap-3 sm:grid-cols-2">{practical.map(({icon:Icon,title,copy})=><article key={title} className="rounded-xl border border-jade/10 bg-white p-5 shadow-[0_5px_18px_rgba(18,63,54,0.035)]"><span className="grid h-10 w-10 place-items-center rounded-lg border border-jade/10 bg-jade/[0.025] text-jade"><Icon size={20} strokeWidth={1.55}/></span><h3 className="mt-4 font-display text-2xl font-semibold text-jade">{title}</h3><p className="mt-2 text-[11px] leading-5 text-charcoal/57">{copy}</p></article>)}</div></div><div className="mt-9 rounded-2xl border border-jade/10 bg-white px-6 py-7 sm:px-8"><div className="grid gap-6 lg:grid-cols-[0.72fr_1.4fr] lg:items-center"><div><p className="eyebrow">Useful arrival reset</p><h3 className="font-display text-[2.35rem] font-semibold leading-[0.95] text-jade">Keep the first island day local.</h3></div><ul className="grid gap-3 text-xs leading-5 text-charcoal/60 sm:grid-cols-2">{['Save the exact hotel pin and transfer contact.','Check live beach and sea conditions.','Confirm the pickup zone for any early boat day.','Choose one nearby dinner and an easy return.'].map(item=><li key={item} className="flex gap-2.5"><Check size={15} className="mt-0.5 shrink-0 text-saffron-dark"/>{item}</li>)}</ul></div></div></div></section>

      <section className="section-divider-bottom bg-jade-dark py-12 text-white lg:py-16"><div className="container-custom grid gap-9 lg:grid-cols-[0.68fr_1.5fr] lg:items-center lg:gap-14"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-saffron-light">Continue planning</p><h2 className="mt-3 font-display text-[3rem] font-semibold leading-[0.93] tracking-[-0.04em]">Build the rest of your Koh Samui trip.</h2><p className="mt-5 text-sm leading-7 text-white/65">Move from the island overview into specialist owners without repeating the same broad advice.</p></div><div className="grid gap-3 sm:grid-cols-3">{[{title:'Things to do',copy:'Beaches, temples and stronger day trips.',href:'/city/koh-samui/attractions/'},{title:'Where to stay',copy:'Compare zones before comparing hotels.',href:'/best-hotels/koh-samui/'},{title:'Best time',copy:'Plan around Samui’s Gulf weather pattern.',href:'/city/koh-samui/weather/'}].map(item=><Link key={item.title} href={item.href} className="group rounded-xl border border-white/12 bg-white/[0.07] p-5 backdrop-blur-sm transition hover:-translate-y-1 hover:bg-white/[0.11]"><h3 className="font-display text-2xl font-semibold">{item.title}</h3><p className="mt-2 min-h-10 text-[10px] leading-5 text-white/57">{item.copy}</p><span className="mt-5 flex items-center justify-between text-[10px] font-bold text-saffron-light">Open guide <ArrowRight size={14} className="transition group-hover:translate-x-1"/></span></Link>)}</div></div></section>
    </>
  );
}
