// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/about.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_we_cover": "We cover",
  "s002_go2_travel_network": "Go2 Travel Network",
  "s004_transparent_affiliates": "Transparent affiliates",
  "s005_ai_assisted_human_verified": "AI-assisted, human-verified:",
  "s006_we_use_ai_tools": "We use AI tools to assist with research, drafting, and data analysis. All content is reviewed, fact-checked, and verified by our editorial team before publication. Statistics are sourced from official organizations (Tourism Authority of Thailand, UNESCO, government agencies) and linked directly to their origin.",
  "s007_correction_policy": "Correction policy:",
  "s008_thailand_travel_index": "Thailand Travel Index",
  },
  nl: {
  "s001_we_cover": "We behandelen",
  "s002_go2_travel_network": "Go2 Travel Network",
  "s004_transparent_affiliates": "Transparante affiliates",
  "s005_ai_assisted_human_verified": "AI-ondersteund, door mensen geverifieerd:",
  "s006_we_use_ai_tools": "We gebruiken AI-tools om te helpen bij onderzoek, opstellen en data-analyse. Alle inhoud wordt beoordeeld, feit-gecontroleerd en geverifieerd door ons redactionele team voordat het gepubliceerd wordt. Statistieken zijn afkomstig van officiële organisaties (Tourism Authority of Thailand, UNESCO, overheidsinstanties) en direct gelinkt naar de bron.",
  "s007_correction_policy": "Correctiebeleid:",
  "s008_thailand_travel_index": "Thailand Travel Index",
  },
};
