// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/affiliate-disclosure.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_we_recommend_hotels_tours": "We recommend hotels, tours, and services based on quality and relevance to the reader, not commission rates.",
  "s002_if_a_destination_hotel": "If a destination, hotel, or service has real drawbacks, we say so — regardless of whether we have an affiliate relationship.",
  "s003_affiliate_partners_are_selected": "Affiliate partners are selected based on traveller feedback, industry reputation, and our own assessment of their service quality.",
  },
  nl: {
  "s001_we_recommend_hotels_tours": "We raden hotels, tours en diensten aan op basis van kwaliteit en relevantie voor de reiziger, niet op commissietarieven.",
  "s002_if_a_destination_hotel": "Als een bestemming, hotel of dienst echte nadelen heeft, zeggen we dat — ongeacht of we een affiliate-relatie hebben.",
  "s003_affiliate_partners_are_selected": "Affiliate partners worden geselecteerd op basis van feedback van reizigers, reputatie in de branche en onze eigen beoordeling van hun servicekwaliteit.",
  },
};
