// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/best-beaches-in-thailand.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_sources_tat_thailand_dnp": "Sources: TAT, Thailand DNP",
  "s002_updated_march_28_2026": "Updated March 28, 2026",
  },
  nl: {
  "s001_sources_tat_thailand_dnp": "Bronnen: TAT, Thailand DNP",
  "s002_updated_march_28_2026": "Bijgewerkt 28 maart 2026",
  },
};
