// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/best-elephant-sanctuaries-in-thailand.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_elephas_maximus": "Elephas maximus",
  "s002_save_elephant_foundation": "Save Elephant Foundation",
  "s003_red_flag_checklist": "Red flag checklist:",
  "s004_avoid_any_venue_that": "Avoid any venue that offers elephant riding, bull hooks, shows where elephants perform tricks (painting, football), or chains visible in guest photos. World Animal Protection and Wildlife Friends Foundation Thailand are reliable sources for identifying abusive operations.",
  "s005_travel_insurance": "Travel Insurance",
  "s006_essential_for_activities": "Essential for activities",
  "s007_thai_food_guide": "Thai Food Guide",
  "s008_cuisine_street_food": "Cuisine & street food",
  "s009_best_places_to_visit": "Best Places to Visit",
  "s010_top_destinations": "Top destinations",
  "s011_thai_islands": "Thai Islands",
  "s012_beaches_island_life": "Beaches & island life",
  "s013_first_timer_apos_s": "First Timer&apos;s Guide",
  "s014_everything_you_need_to": "Everything you need to know",
  "s015_diving_amp_snorkeling": "Diving &amp; Snorkeling",
  "s016_reefs_underwater_life": "Reefs & underwater life",
  "s017_muay_thai": "Muay Thai",
  "s018_training_fight_nights": "Training & fight nights",
  },
  nl: {
  "s001_elephas_maximus": "Elephas maximus",
  "s002_save_elephant_foundation": "Save Elephant Foundation",
  "s003_red_flag_checklist": "Rode vlaggen checklist:",
  "s004_avoid_any_venue_that": "Vermijd elke locatie die olifantenritten, bull hooks, shows waar olifanten trucjes doen (schilderen, voetbal) aanbiedt, of kettingen die zichtbaar zijn op gastenfoto's. World Animal Protection en Wildlife Friends Foundation Thailand zijn betrouwbare bronnen om misbruikende operaties te identificeren.",
  "s005_travel_insurance": "Reisverzekering",
  "s006_essential_for_activities": "Essentieel voor activiteiten",
  "s007_thai_food_guide": "Thaise Eetgids",
  "s008_cuisine_street_food": "Keuken & straeteet",
  "s009_best_places_to_visit": "Beste Plekken om te Bezoeken",
  "s010_top_destinations": "Topbestemmingen",
  "s011_thai_islands": "Thaise Eilanden",
  "s012_beaches_island_life": "Stranden & eilandleven",
  "s013_first_timer_apos_s": "Gids voor Beginners",
  "s014_everything_you_need_to": "Alles wat je moet weten",
  "s015_diving_amp_snorkeling": "Duiken & Snorkelen",
  "s016_reefs_underwater_life": "Riffen & onderwaterleven",
  "s017_muay_thai": "Muay Thai",
  "s018_training_fight_nights": "Training & vechtavonden",
  },
};
