// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/best-muay-thai-in-thailand.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_muay_thai_the_quot": "Muay Thai — the &quot;Art of Eight Limbs&quot; — evolved from",
  "s002_muay_boran": "Muay Boran",
  "s003_the_most_celebrated_figure": "The most celebrated figure in Muay Thai folklore is",
  "s004_nai_khanom_tom": "Nai Khanom Tom",
  "s005_march_17": "March 17",
  "s006_muay_thai_in_its": "Muay Thai in its modern codified form — with gloves, rounds, and a referee — emerged under",
  "s007_king_rama_vii": "King Rama VII",
  "s008_unesco_apos_s_representative": "UNESCO&apos;s Representative List of the Intangible Cultural Heritage of Humanity",
  "s009_dtv_visa_tip": "DTV Visa tip:",
  "s010_if_you_apos_re": "If you&apos;re planning a longer training stay, check if your chosen gym can sponsor a 6 or 12 month DTV (Destination Thailand Visa) for Muay Thai training. Lamay Muay Thai and Diamond Muay Thai are known to offer this.",
  },
  nl: {
  "s001_muay_thai_the_quot": "Muay Thai — de &quot;Kunst van de Acht Leden&quot; — ontwikkelde zich uit",
  "s002_muay_boran": "Muay Boran",
  "s003_the_most_celebrated_figure": "De meest gevierde figuur in de Muay Thai-folklore is",
  "s004_nai_khanom_tom": "Nai Khanom Tom",
  "s005_march_17": "17 maart",
  "s006_muay_thai_in_its": "Muay Thai in zijn moderne gecodificeerde vorm — met handschoenen, ronden en een scheidsrechter — ontstond onder",
  "s007_king_rama_vii": "King Rama VII",
  "s008_unesco_apos_s_representative": "UNESCO&apos;s Representatieve Lijst van het Immaterieel Cultureel Erfgoed van de Mensheid",
  "s009_dtv_visa_tip": "Tip voor DTV Visa:",
  "s010_if_you_apos_re": "Als je een langere trainingsverblijf plant, controleer dan of je gekozen sportschool een DTV (Destination Thailand Visa) van 6 of 12 maanden voor Muay Thai-training kan sponsoren. Lamay Muay Thai en Diamond Muay Thai staan bekend om dit aan te bieden.",
  },
};
