// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/blog/index.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_thailand_travel_blog_tips": "Thailand Travel Blog | Tips, Guides & Stories | Go2Thailand",
  "s002_explore_thailand_through_our": "Explore Thailand through our travel blog. Get insider tips, destination guides, food recommendations, and travel stories from the Land of Smiles.",
  "s003_thailand_travel_blog_thailand": "Thailand travel blog, Thailand tips, Thailand guides, Thai culture, Thailand stories",
  "s004_blog_pagination": "Blog pagination",
  "s005_affiliate_links": "Affiliate links",
  "s006_klook_activities": "Klook Activities",
  "s007_getyourguide_tours": "GetYourGuide Tours",
  "s009_thailand_esim": "Thailand eSIM",
  "s010_saily_esim": "Saily eSIM",
  },
  nl: {
  "s001_thailand_travel_blog_tips": "Thailand Reisblog | Tips, Gidsen & Verhalen | Go2Thailand",
  "s002_explore_thailand_through_our": "Ontdek Thailand via onze reisblog. Ontvang insider tips, bestemmingsgidsen, eetgelegenheidsaanbevelingen en reisverhalen uit het Land van de Glimlach.",
  "s003_thailand_travel_blog_thailand": "Thailand reisblog, Thailand tips, Thailand gidsen, Thaise cultuur, Thailand verhalen",
  "s004_blog_pagination": "Blog paginering",
  "s005_affiliate_links": "Partnerlinks",
  "s006_klook_activities": "Klook Activiteiten",
  "s007_getyourguide_tours": "GetYourGuide Excursies",
  "s009_thailand_esim": "Thailand eSIM",
  "s010_saily_esim": "Saily eSIM",
  },
};
