// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/blog/category/[category].tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_no_posts_found_in": "No posts found in this category.",
  "s002_plan_your_thailand_trip": "Plan Your Thailand Trip",
  "s003_book_hotels_transport_activities": "Book hotels, transport, activities, and get connected with an eSIM",
  },
  nl: {
  "s001_no_posts_found_in": "Geen berichten gevonden in deze categorie.",
  "s002_plan_your_thailand_trip": "Plan je reis naar Thailand",
  "s003_book_hotels_transport_activities": "Boek hotels, vervoer, activiteiten en verbind met een eSIM",
  },
};
