// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/city/[slug]/cooking-classes.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_not_found": "Not found",
  "s002_classes_available": "Classes Available",
  "s003_duration_formats": "Duration Formats",
  "s004_group_styles": "Group Styles",
  "s005_local_fit": "Local Fit",
  "s006_limited_local_fit": "Limited local fit",
  "s007_planning_fit": "Planning fit",
  "s008_food_dining": "Food & Dining",
  "s009_pair_a_class_with": "Pair a class with better local eating context.",
  "s010_choose_a_base_that": "Choose a base that fits your class schedule.",
  "s011_round_out_the_day": "Round out the day with a Bangkok sightseeing plan.",
  "s012_stronger_local_fit_than": "Stronger local fit than cooking classes.",
  "s013_heritage_planning_with_the": "Heritage planning with the highest local payoff.",
  "s014_top_things_to_see": "Top things to see",
  "s016_local_cuisine_guide": "Local cuisine guide",
  "s017_where_to_stay": "Where to stay",
  },
  nl: {
  "s001_not_found": "Niet gevonden",
  "s002_classes_available": "Beschikbare lessen",
  "s003_duration_formats": "Duurvormen",
  "s004_group_styles": "Groepstijlen",
  "s005_local_fit": "Lokale afstemming",
  "s006_limited_local_fit": "Beperkte lokale afstemming",
  "s007_planning_fit": "Planningsafstemming",
  "s008_food_dining": "Eten & Dineren",
  "s009_pair_a_class_with": "Koppel een les aan betere lokale eetcontext.",
  "s010_choose_a_base_that": "Kies een basis die past bij je lesrooster.",
  "s011_round_out_the_day": "Vul de dag aan met een Bangkok sightseeingplan.",
  "s012_stronger_local_fit_than": "Sterkere lokale afstemming dan kooklessen.",
  "s013_heritage_planning_with_the": "Erfgoedplanning met de hoogste lokale waarde.",
  "s014_top_things_to_see": "Top bezienswaardigheden",
  "s016_local_cuisine_guide": "Gids lokale keuken",
  "s017_where_to_stay": "Waar te verblijven",
  },
};
