// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/city/[slug]/muay-thai.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_not_found": "Not found",
  "s002_experience_types": "Experience Types",
  "s003_fight_venues": "Fight Venues",
  "s004_training_gyms": "Training Gyms",
  "s005_limited_local_fit": "Limited local fit",
  "s006_planning_fit": "Planning fit",
  "s009_top_things_to_see": "Top things to see",
  "s010_cooking_classes": "Cooking Classes",
  "s011_learn_thai_cuisine": "Learn Thai cuisine",
  "s012_where_to_stay": "Where to stay",
  "s013_better_muay_thai_alternatives": "Better Muay Thai alternatives",
  },
  nl: {
  "s001_not_found": "Niet gevonden",
  "s002_experience_types": "Ervaringstypes",
  "s003_fight_venues": "Vechtlocaties",
  "s004_training_gyms": "Trainingsgyms",
  "s005_limited_local_fit": "Beperkt lokaal aanbod",
  "s006_planning_fit": "Planningsaanbod",
  "s009_top_things_to_see": "Top bezienswaardigheden",
  "s010_cooking_classes": "Kooklessen",
  "s011_learn_thai_cuisine": "Leer Thaise keuken",
  "s012_where_to_stay": "Waar te verblijven",
  "s013_better_muay_thai_alternatives": "Betere Muay Thai alternatieven",
  },
};
