// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/city/[slug]/elephant-sanctuaries.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_not_found": "Not found",
  "s002_visit_formats": "Visit Formats",
  "s003_group_styles": "Group Styles",
  "s004_local_fit": "Local Fit",
  "s005_limited_local_fit": "Limited local fit",
  "s006_planning_fit": "Planning fit",
  "s007_a_better_local_fit": "A better local fit than sanctuary search.",
  "s008_chiang_mai_sanctuaries": "Chiang Mai sanctuaries",
  "s009_thailand_s_strongest_sanctuary": "Thailand's strongest sanctuary market.",
  "s010_phuket_sanctuaries": "Phuket sanctuaries",
  "s011_another_stronger_fit_for": "Another stronger fit for this activity.",
  "s012_top_things_to_see": "Top things to see",
  "s013_cooking_classes": "Cooking Classes",
  "s014_learn_thai_cooking": "Learn Thai cooking",
  "s015_where_to_stay": "Where to stay",
  },
  nl: {
  "s001_not_found": "Niet gevonden",
  "s002_visit_formats": "Bezoekformaten",
  "s003_group_styles": "Groepstijlen",
  "s004_local_fit": "Lokale match",
  "s005_limited_local_fit": "Beperkte lokale match",
  "s006_planning_fit": "Planningsmatch",
  "s007_a_better_local_fit": "Een betere lokale match dan de sanctuary-zoekopdracht.",
  "s008_chiang_mai_sanctuaries": "Chiang Mai sanctuaria",
  "s009_thailand_s_strongest_sanctuary": "Thailand's sterkste markt voor sanctuaria.",
  "s010_phuket_sanctuaries": "Phuket sanctuaria",
  "s011_another_stronger_fit_for": "Nog een sterkere match voor deze activiteit.",
  "s012_top_things_to_see": "Top bezienswaardigheden",
  "s013_cooking_classes": "Kookcursussen",
  "s014_learn_thai_cooking": "Leer Thais koken",
  "s015_where_to_stay": "Waar te verblijven",
  },
};
