// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/city/[slug]/top-10-restaurants.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_city_not_found": "City not found",
  "s002_top_10_guide": "Top 10 Guide",
  "s003_primary_sources_linked_below": "Primary sources linked below",
  "s004_quick_jump": "Quick Jump",
  "s005_explore_more": "Explore More",
  "s006_top_10_hotels": "Top 10 Hotels",
  "s007_top_10_attractions": "Top 10 Attractions",
  "s008_related_guides": "Related Guides",
  "s009_thai_food_guide": "Thai Food Guide",
  "s010_cooking_classes": "Cooking Classes",
  "s011_thai_drinks_guide": "Thai Drinks Guide",
  "s012_view_on_google_maps": "View on Google Maps",
  "s013_get_the_complete_guide": "Get the complete guide with attractions, hotels, and more insider tips.",
  "s015_explore_thai_food_amp": "Explore Thai Food &amp; Drink",
  "s017_dishes_flavours_amp_where": "Dishes, flavours &amp; where to eat →",
  "s019_learn_to_cook_thai": "Learn to cook Thai food →",
  "s021_what_to_drink_in": "What to drink in Thailand →",
  "s022_sources_amp_references": "Sources &amp; References",
  },
  nl: {
  "s001_city_not_found": "Stad niet gevonden",
  "s002_top_10_guide": "Top 10 Gids",
  "s003_primary_sources_linked_below": "Primaire bronnen hieronder gelinkt",
  "s004_quick_jump": "Snelle Sprong",
  "s005_explore_more": "Ontdek Meer",
  "s006_top_10_hotels": "Top 10 Hotels",
  "s007_top_10_attractions": "Top 10 Bezienswaardigheden",
  "s008_related_guides": "Gerelateerde Gidsen",
  "s009_thai_food_guide": "Gids voor Thais Eten",
  "s010_cooking_classes": "Kooklessen",
  "s011_thai_drinks_guide": "Gids voor Thaise Dranken",
  "s012_view_on_google_maps": "Bekijk op Google Maps",
  "s013_get_the_complete_guide": "Ontvang de complete gids met bezienswaardigheden, hotels en meer insider tips.",
  "s015_explore_thai_food_amp": "Ontdek Thais Eten & Drinken",
  "s017_dishes_flavours_amp_where": "Gerechten, smaken & waar te eten →",
  "s019_learn_to_cook_thai": "Leer Thais eten koken →",
  "s021_what_to_drink_in": "Wat te drinken in Thailand →",
  "s022_sources_amp_references": "Bronnen & Referenties",
  },
};
