// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/city/[slug]/diving-snorkeling.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_not_found": "Not found",
  "s002_planning_fit": "Planning fit",
  "s003_experience_types": "Experience Types",
  "s004_trip_formats": "Trip Formats",
  "s005_local_fit": "Local Fit",
  "s006_limited_local_fit": "Limited local fit",
  "s007_better_context_for_an": "Better context for an inland city.",
  "s008_phuket_marine_trips": "Phuket marine trips",
  "s009_a_much_stronger_water": "A much stronger water-activity base.",
  "s010_krabi_marine_trips": "Krabi marine trips",
  "s011_another_strong_coastal_alternative": "Another strong coastal alternative.",
  "s012_frequently_asked_questions": "Frequently Asked Questions",
  "s013_top_things_to_see": "Top things to see",
  "s014_elephant_sanctuaries": "Elephant Sanctuaries",
  "s015_ethical_elephant_experiences": "Ethical elephant experiences",
  "s016_where_to_stay": "Where to stay",
  },
  nl: {
  "s001_not_found": "Niet gevonden",
  "s002_planning_fit": "Planningsfit",
  "s003_experience_types": "Ervaringstypes",
  "s004_trip_formats": "Reisformaten",
  "s005_local_fit": "Lokale fit",
  "s006_limited_local_fit": "Beperkte lokale fit",
  "s007_better_context_for_an": "Betere context voor een binnenlandse stad.",
  "s008_phuket_marine_trips": "Phuket zee-excursies",
  "s009_a_much_stronger_water": "Een veel sterker basis voor wateractiviteiten.",
  "s010_krabi_marine_trips": "Krabi zee-excursies",
  "s011_another_strong_coastal_alternative": "Een andere sterke kustalternatief.",
  "s012_frequently_asked_questions": "Veelgestelde vragen",
  "s013_top_things_to_see": "Top bezienswaardigheden",
  "s014_elephant_sanctuaries": "Olifantenopvangcentra",
  "s015_ethical_elephant_experiences": "Ethische olifantenervaringen",
  "s016_where_to_stay": "Waar te verblijven",
  },
};
