// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: components/CookieConsent.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_necessary_cookies": "Necessary cookies:",
  "s002_required_for_the_website": "Required for the website to function properly (authentication, security, preferences).",
  "s003_analytics_cookies": "Analytics cookies:",
  "s004_help_us_understand_how": "Help us understand how visitors use our website through Google Analytics.",
  "s005_marketing_cookies": "Marketing cookies:",
  "s006_used_to_show_relevant": "Used to show relevant ads and measure their effectiveness.",
  },
  nl: {
  "s001_necessary_cookies": "Noodzakelijke cookies:",
  "s002_required_for_the_website": "Vereist voor de juiste werking van de website (authenticatie, beveiliging, voorkeuren).",
  "s003_analytics_cookies": "Analytische cookies:",
  "s004_help_us_understand_how": "Helpen ons te begrijpen hoe bezoekers onze website gebruiken via Google Analytics.",
  "s005_marketing_cookies": "Marketingcookies:",
  "s006_used_to_show_relevant": "Gebruikt om relevante advertenties te tonen en hun effectiviteit te meten.",
  },
};
