// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: components/ExitIntentPopup.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_you_apos_re_in": "You&apos;re in!",
  "s002_check_your_inbox_for": "Check your inbox for Thailand travel tips.",
  "s003_wait_don_apos_t": "Wait — don&apos;t miss out!",
  "s004_get_free_thailand_travel": "Get free Thailand travel tips, hidden gems, and budget hacks straight to your inbox. No spam, unsubscribe anytime.",
  "s005_something_went_wrong_please": "Something went wrong. Please try again.",
  "s006_join_1_000_thailand": "Join 1,000+ Thailand travelers. Unsubscribe anytime.",
  },
  nl: {
  "s001_you_apos_re_in": "Je bent erbij!",
  "s002_check_your_inbox_for": "Bekijk je inbox voor Thailand-reistips.",
  "s003_wait_don_apos_t": "Wacht — mis het niet!",
  "s004_get_free_thailand_travel": "Ontvang gratis Thailand-reistips, verborgen parels en budgettips direct in je inbox. Geen spam, afmelden wanneer je wilt.",
  "s005_something_went_wrong_please": "Er is iets misgegaan. Probeer het opnieuw.",
  "s006_join_1_000_thailand": "Sluit je aan bij 1.000+ Thailand-reizigers. Afmelden wanneer je wilt.",
  },
};
