// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: components/FeedbackForm.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_thank_you_for_your": "Thank You for Your Feedback!",
  "s002_your_input_helps_us": "Your input helps us improve Go2 Thailand.",
  "s003_was_this_page_helpful": "Was this page helpful?",
  },
  nl: {
  "s001_thank_you_for_your": "Bedankt voor je feedback!",
  "s002_your_input_helps_us": "Je reactie helpt ons Go2 Thailand te verbeteren.",
  "s003_was_this_page_helpful": "Was deze pagina nuttig?",
  },
};
