// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: components/ShareButtons.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_share_on_pinterest": "Share on Pinterest",
  "s002_share_on_facebook": "Share on Facebook",
  "s003_share_on_x": "Share on X",
  "s004_share_on_whatsapp": "Share on WhatsApp",
  "s005_copy_link": "Copy link",
  },
  nl: {
  "s001_share_on_pinterest": "Delen op Pinterest",
  "s002_share_on_facebook": "Delen op Facebook",
  "s003_share_on_x": "Delen op X",
  "s004_share_on_whatsapp": "Delen op WhatsApp",
  "s005_copy_link": "Link kopiëren",
  },
};
