// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: components/FeedbackForm.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_thank_you_for_your": "Thank You for Your Feedback!",
  "s002_your_input_helps_us": "Your input helps us improve Go2 Thailand.",
  "s003_was_this_page_helpful": "Was this page helpful?",
  "s004_submit_error": "Failed to submit feedback. Please try again.",
  "s005_help_us_improve": "Let us know how we can improve this travel guide.",
  "s006_rate_this_page": "Rate this page",
  "s007_rate": "Rate",
  "s008_stars": "stars",
  "s009_tell_us_more": "Tell us more (required)",
  "s010_what_could_improve": "What could we improve?",
  "s011_what_did_you_like": "What did you like about this page?",
  "s012_email_optional": "Email (optional)",
  "s013_keep_me_updated": "Keep me updated about Go2 Thailand travel tips",
  "s014_email_use": "We'll only use this if we need to follow up on your feedback.",
  "s015_sending": "Sending...",
  "s016_send_feedback": "Send feedback",
  "s017_rate_one_star": "Rate 1 star",
  },
  nl: {
  "s001_thank_you_for_your": "Bedankt voor je feedback!",
  "s002_your_input_helps_us": "Je reactie helpt ons Go2 Thailand te verbeteren.",
  "s003_was_this_page_helpful": "Was deze pagina nuttig?",
  "s004_submit_error": "Je feedback kon niet worden verzonden. Probeer het nog eens.",
  "s005_help_us_improve": "Laat ons weten hoe we deze reisgids kunnen verbeteren.",
  "s006_rate_this_page": "Beoordeel deze pagina",
  "s007_rate": "Geef",
  "s008_stars": "sterren",
  "s009_tell_us_more": "Vertel ons meer (verplicht)",
  "s010_what_could_improve": "Wat kunnen we verbeteren?",
  "s011_what_did_you_like": "Wat vond je goed aan deze pagina?",
  "s012_email_optional": "E-mailadres (optioneel)",
  "s013_keep_me_updated": "Houd me op de hoogte van reistips van Go2 Thailand",
  "s014_email_use": "We gebruiken je e-mailadres alleen als we op je feedback moeten terugkomen.",
  "s015_sending": "Verzenden...",
  "s016_send_feedback": "Feedback verzenden",
  "s017_rate_one_star": "Geef 1 ster",
  },
};
