// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: components/blog/BlogTableOfContents.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_table_of_contents": "Table of contents",
  "s002_on_this_page": "On this page",
  },
  nl: {
  "s001_table_of_contents": "Inhoudsopgave",
  "s002_on_this_page": "Op deze pagina",
  },
};
