// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/cookie-policy.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_google_analytics_opt_out": "Google Analytics Opt-out",
  "s002_google_analytics": "Google Analytics:",
  "s003_we_use_google_analytics": "We use Google Analytics to understand visitor behavior — which pages are most popular, how long visitors stay, and where they come from. This helps us improve our Thailand travel content. Google Analytics sets cookies such as",
  "s005_google_ads_beleid": "Google Ads beleid",
  "s006_google_adsense": "Google AdSense:",
  "s007_displays_contextual_and_personalized": "Displays contextual and personalized ads. Google may use cookies such as",
  "s008_google_ads_policies": "Google Ads policies",
  "s009_ezoic_apos_s_privacyverklaringen": "Ezoic&apos;s privacyverklaringen voor Go2Thailand.com",
  "s010_ezoic_apos_s_privacy": "Ezoic&apos;s privacy disclosures for Go2Thailand.com",
  "s011_saily_nordvpn_safetywing": "Saily / NordVPN / SafetyWing",
  "s012_google_chrome": "Google Chrome",
  "s013_mozilla_firefox": "Mozilla Firefox",
  "s014_apple_safari": "Apple Safari",
  "s015_microsoft_edge": "Microsoft Edge",
  },
  nl: {
  "s001_google_analytics_opt_out": "Google Analytics uitschakelen",
  "s002_google_analytics": "Google Analytics:",
  "s003_we_use_google_analytics": "We gebruiken Google Analytics om het gedrag van bezoekers te begrijpen — welke pagina's het populairst zijn, hoe lang bezoekers blijven en waar ze vandaan komen. Dit helpt ons onze Thailand-reisinhoud te verbeteren. Google Analytics stelt cookies in zoals",
  "s005_google_ads_beleid": "Google Ads-beleid",
  "s006_google_adsense": "Google AdSense:",
  "s007_displays_contextual_and_personalized": "Toont contextuele en gepersonaliseerde advertenties. Google kan cookies gebruiken zoals",
  "s008_google_ads_policies": "Google Ads-beleid",
  "s009_ezoic_apos_s_privacyverklaringen": "Ezoic's privacyverklaringen voor Go2Thailand.com",
  "s010_ezoic_apos_s_privacy": "Ezoic's privacyverklaringen voor Go2Thailand.com",
  "s011_saily_nordvpn_safetywing": "Saily / NordVPN / SafetyWing",
  "s012_google_chrome": "Google Chrome",
  "s013_mozilla_firefox": "Mozilla Firefox",
  "s014_apple_safari": "Apple Safari",
  "s015_microsoft_edge": "Microsoft Edge",
  },
};
