// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/editorial-policy.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_accuracy_first": "Accuracy First",
  "s002_regular_updates": "Regular Updates",
  "s003_we_recommend_products_and": "We recommend products and services we genuinely believe provide value",
  "s004_affiliate_verklaring": "Affiliate Verklaring",
  "s005_affiliate_disclosure": "Affiliate Disclosure",
  "s006_we_welcome_corrections": "We welcome corrections.",
  "s007_significant_factual_corrections_are": "Significant factual corrections are noted in the updated content where appropriate, so readers know the information has been reviewed.",
  },
  nl: {
  "s001_accuracy_first": "Nauwkeurigheid Eerst",
  "s002_regular_updates": "Regelmatige Updates",
  "s003_we_recommend_products_and": "We bevelen producten en diensten aan die we oprecht geloven waarde te bieden",
  "s004_affiliate_verklaring": "Affiliateverklaring",
  "s005_affiliate_disclosure": "Affiliate-openbaarmaking",
  "s006_we_welcome_corrections": "We verwelkomen correcties.",
  "s007_significant_factual_corrections_are": "Belangrijke feitelijke correcties worden vermeld in de bijgewerkte inhoud waar gepast, zodat lezers weten dat de informatie is nagekeken.",
  },
};
