// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/festivals/index.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_thailand_festivals_2026_complete": "Thailand Festivals 2026: Complete Calendar & Guide to Every Major Celebration",
  "s002_the_big_three_festivals": "The Big Three: Festivals Every Visitor Should See",
  "s003_month_by_month_festival": "Month-by-Month Festival Calendar",
  "s004_practical_tips_for_festival": "Practical Tips for Festival Travel",
  "s005_book_early": "Book Early",
  "s006_alcohol_bans": "Alcohol Bans",
  "s007_temple_etiquette": "Temple Etiquette",
  "s008_transport_chaos": "Transport Chaos",
  "s009_related_reading": "Related Reading",
  },
  nl: {
  "s001_thailand_festivals_2026_complete": "Thailand Festivals 2026: Volledige Kalender & Gids voor Elke Grote Viering",
  "s002_the_big_three_festivals": "De Grote Drie: Festivals Die Elke Bezoeker Moet Zien",
  "s003_month_by_month_festival": "Festival Kalender per Maand",
  "s004_practical_tips_for_festival": "Praktische Tips voor Festivalreizen",
  "s005_book_early": "Boek Vroeg",
  "s006_alcohol_bans": "Alcoholverboden",
  "s007_temple_etiquette": "Tempel-etiquette",
  "s008_transport_chaos": "Transportchaos",
  "s009_related_reading": "Gerelateerd Lezen",
  },
};
