// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/nightlife/index.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_thailand_nightlife_guide_2026": "Thailand Nightlife Guide 2026 — Best Bars & Clubs by City",
  "s002_explore_the_best_nightlife": "Explore the best nightlife in Thailand. City-by-city guides covering bars, clubs, rooftop lounges, and late-night spots with real drink prices for 2026.",
  "s003_thailand_s_nightlife_culture": "Thailand's Nightlife Culture: What to Expect",
  },
  nl: {
  "s001_thailand_nightlife_guide_2026": "Thailand Nachtleven Gids 2026 — Beste Bars & Clubs per Stad",
  "s002_explore_the_best_nightlife": "Ontdek het beste nachtleven in Thailand. Gidsen per stad over bars, clubs, dakterraslounges en late-night spots met echte drankprijzen voor 2026.",
  "s003_thailand_s_nightlife_culture": "Nachtleven Cultuur in Thailand: Wat te Verwachten",
  },
};
