// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/privacy.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_google_privacybeleid": "Google Privacybeleid",
  "s002_google_privacy_policy": "Google Privacy Policy",
  "s003_ezoic_privacy_verklaringen_voor": "Ezoic Privacy Verklaringen voor Go2Thailand.com",
  "s004_ezoic_privacy_disclosures_for": "Ezoic Privacy Disclosures for Go2Thailand.com",
  },
  nl: {
  "s001_google_privacybeleid": "Google Privacybeleid",
  "s002_google_privacy_policy": "Google Privacybeleid",
  "s003_ezoic_privacy_verklaringen_voor": "Ezoic Privacyverklaringen voor Go2Thailand.com",
  "s004_ezoic_privacy_disclosures_for": "Ezoic Privacyverklaringen voor Go2Thailand.com",
  },
};
