// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/temples/[slug].tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_booking_com_hotels": "Booking.com Hotels",
  "s002_thailand_transportgids": "Thailand transportgids",
  "s003_thailand_transport_guide": "Thailand transport guide",
  },
  nl: {
  "s001_booking_com_hotels": "Booking.com Hotels",
  "s002_thailand_transportgids": "Thailand transportgids",
  "s003_thailand_transport_guide": "Thailand transportgids",
  },
};
