// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/thailand-temples.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_thailand_temples_10_sacred": "Thailand Temples — 10 Sacred Sites with Verified History (2026 Guide)",
  "s002_thailand_temples_wat_phra": "Thailand temples, Wat Phra Kaew, Wat Pho, Wat Arun, Doi Suthep, White Temple Chiang Rai, Ayutthaya temples, UNESCO Thailand, Thai temple etiquette, Buddhist temples Thailand",
  "s003_bangkok_the_rattanakosin_core": "Bangkok — The Rattanakosin Core",
  "s004_chiang_mai_capital_of": "Chiang Mai — Capital of the Lanna Kingdom",
  "s005_ayutthaya_the_destroyed_royal": "Ayutthaya — The Destroyed Royal Capital",
  "s006_isan_and_the_south": "Isan and the South — Beyond the Tourist Trail",
  },
  nl: {
  "s001_thailand_temples_10_sacred": "Thailand Tempels — 10 Heilige Plaatsen met Geverifieerde Geschiedenis (2026 Gids)",
  "s002_thailand_temples_wat_phra": "Thailand tempels, Wat Phra Kaew, Wat Pho, Wat Arun, Doi Suthep, Witte Tempel Chiang Rai, Ayutthaya tempels, UNESCO Thailand, Thaise tempel etiquette, Boeddhistische tempels Thailand",
  "s003_bangkok_the_rattanakosin_core": "Bangkok — De Rattanakosin Kern",
  "s004_chiang_mai_capital_of": "Chiang Mai — Hoofdstad van het Lanna Koninkrijk",
  "s005_ayutthaya_the_destroyed_royal": "Ayutthaya — De Vernietigde Koninklijke Hoofdstad",
  "s006_isan_and_the_south": "Isan en het Zuiden — Buiten de Gebaande Paden",
  },
};
