// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/thailand-in/[month].tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_chiang_mai_chiang_rai": "Chiang Mai, Chiang Rai",
  "s002_bangkok_ayutthaya": "Bangkok, Ayutthaya",
  "s003_phuket_krabi_koh_samui": "Phuket, Krabi, Koh Samui",
  },
  nl: {
  "s001_chiang_mai_chiang_rai": "Chiang Mai, Chiang Rai",
  "s002_bangkok_ayutthaya": "Bangkok, Ayutthaya",
  "s003_phuket_krabi_koh_samui": "Phuket, Krabi, Koh Samui",
  },
};
