// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/top-10/restaurants.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_thailand_restaurants_top_10": "Thailand restaurants, top 10 restaurants, Thai food, restaurant guides, Bangkok restaurants, Phuket dining, Chiang Mai food",
  "s002_city_level_restaurant_shortlists": "City-level restaurant shortlists",
  "s003_visible_source_links_below": "Visible source links below",
  "s004_browse_index": "Browse Index",
  },
  nl: {
  "s001_thailand_restaurants_top_10": "Restaurants Thailand, top 10 restaurants, Thaise keuken, restaurantgidsen, restaurants Bangkok, dineren Phuket, eten Chiang Mai",
  "s002_city_level_restaurant_shortlists": "Restaurantselecties per stad",
  "s003_visible_source_links_below": "Bronlinks zichtbaar hieronder",
  "s004_browse_index": "Index bladeren",
  },
};
