// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/top-10/attractions.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_thailand_attractions_top_10": "Thailand attractions, top 10 attractions, sightseeing, tourist attractions, Bangkok attractions, Phuket activities, Chiang Mai temples, Thailand tourism",
  "s002_city_level_attraction_shortlists": "City-level attraction shortlists",
  "s003_visible_references_below": "Visible references below",
  "s004_browse_index": "Browse Index",
  },
  nl: {
  "s001_thailand_attractions_top_10": "Thailand bezienswaardigheden, top 10 attracties, bezienswaardigheden, toeristische attracties, Bangkok attracties, Phuket activiteiten, Chiang Mai tempels, Thailand toerisme",
  "s002_city_level_attraction_shortlists": "Korte lijsten attracties per stad",
  "s003_visible_references_below": "Zichtbare verwijzingen hieronder",
  "s004_browse_index": "Index doorbladeren",
  },
};
