// Auto-generated by scripts/i18n-extract-translate.mjs
// Source: pages/top-10/hotels.tsx
// Do not edit English values by hand here — edit the source file instead, then re-run.
// Dutch values are safe to tune by hand.

import type { Strings } from './index';

export const strings: Strings = {
  en: {
  "s001_thailand_hotels_thailand_hotel": "Thailand hotels, Thailand hotel guides, city hotel bases, beach resort stays, heritage stays, hotel planning",
  "s002_city_base_and_stay": "City-base and stay-shape planning",
  "s003_visible_source_links_below": "Visible source links below",
  "s004_browse_index": "Browse Index",
  },
  nl: {
  "s001_thailand_hotels_thailand_hotel": "Hotels in Thailand, hotelgidsen Thailand, stadshotels, strandresorts, erfgoedaccommodaties, hotelplanning",
  "s002_city_base_and_stay": "Planning stadsbasis en verblijfsvorm",
  "s003_visible_source_links_below": "Bronlinks zichtbaar hieronder",
  "s004_browse_index": "Index bladeren",
  },
};
