import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CalendarCheck, Check, Clock3, Droplets, ExternalLink, Flower2, MapPinned, MoonStar, Route, ShieldCheck, Sparkles, TicketCheck, UsersRound } from "lucide-react";
import SEOHead from "../SEOHead";
import { AffiliateDisclosure } from "../design/AffiliateDisclosure";
import { EditorialHero } from "../design/EditorialHero";
import { FaqSplitSection } from "../design/FaqSplitSection";
import { PageSectionNav } from "../design/PageSectionNav";
import { RelatedGuidesSection } from "../design/RelatedGuidesSection";
import { SectionHeading } from "../design/SectionHeading";
import { SourceMethodSection } from "../design/SourceMethodSection";
import { KLOOK_GENERIC, withPlacementSubId } from "../../lib/affiliates";
import { useSubId } from "../../lib/useSubId";

const profiles = [
  { title:"Songkran", tag:"Thais nieuwjaar", period:"Gebruikelijk rond april · editie verifiëren", copy:"Culturele tradities, familie- en tempelmomenten en publieke waterfestiviteiten bestaan naast elkaar. De uitvoering verschilt per stad, wijk en jaar.", verify:"Officieel programma, waterzone, wegafsluiting, droge terugweg", icon:Droplets },
  { title:"Loi Krathong", tag:"Licht, water & dankbaarheid", period:"Maankalender · exacte datum verifiëren", copy:"Lokale ceremonies en activiteiten verschillen per provincie. Behandel het ritueel niet als decor en volg materiaal-, water- en locatie-instructies.", verify:"Stad, waterlocatie, ceremonie, milieuregels en vervoer", icon:Flower2 },
  { title:"Yi Peng-context", tag:"Lanna-traditie", period:"Noord-Thailand · editie en toegang verifiëren", copy:"Wordt vaak met Loi Krathong samengevoegd, maar locatie, ceremonie, parade en eventuele ticketed activiteiten vragen een eigen check.", verify:"Organisator, locatie, ticketstatus, veiligheidsregels en timing", icon:MoonStar },
  { title:"Regionaal festival", tag:"Folklore, religie of seizoen", period:"Plaatsgebonden · niet automatisch jaarlijks gelijk", copy:"Denk aan Phi Ta Khon, kaarsen-, boot- of lokale oogsttradities. De betekenis en deelname horen vóór de fotolijst te komen.", verify:"Lokale autoriteit, datum, route, tempelcontext en gedrag", icon:UsersRound },
];

const checks = [
  { title:"Traditie of specifieke editie?", copy:"Lees evergreen betekenis apart van de bevestigde editie met kalenderjaar. Een oude datum mag nooit stilzwijgend doorschuiven.", icon:CalendarCheck },
  { title:"Waar precies?", copy:"Verifieer stad, district, venue, tempel, park, waterkant en ingang. De festivalnaam alleen is geen routebeschrijving.", icon:MapPinned },
  { title:"Openbaar of ticketed?", copy:"Een openbaar ritueel kan gratis zijn terwijl een tribune, concert of besloten lantaarnactiviteit een apart ticket gebruikt.", icon:TicketCheck },
  { title:"Hoe kom je terug?", copy:"Controleer wegafsluiting, laatste trein/boot, ophaalpunt, looproute, ontmoetingspunt en een rustiger alternatief.", icon:Route },
  { title:"Wat kan nog wijzigen?", copy:"Tijd, programma, toegang, locatie en vorm kunnen door weer, veiligheid, rouwperiode of lokale besluiten worden aangepast.", icon:Clock3 },
];

const faqs = [
  {question:"Wat zijn de belangrijkste festivals in Thailand?",answer:"Songkran en Loi Krathong zijn landelijk bekende tradities. Yi Peng heeft een sterke Lanna-context en daarnaast bestaan regionale religieuze, folkloristische, agrarische en moderne events. Kies niet op een universele ranglijst maar op route, betekenis en een bevestigde actuele editie."},
  {question:"Wanneer is Songkran en wat wordt er gevierd?",answer:"Songkran markeert het Thaise nieuwjaar en wordt doorgaans rond april gevierd. Culturele en publieke programma’s verschillen per jaar en plaats. Controleer voor jouw reis het actuele TAT- of lokale programma, de exacte dagen, zones en vervoersmaatregelen."},
  {question:"Wanneer is Loy Krathong?",answer:"Loi Krathong volgt de Thaise maankalender en valt daardoor niet ieder jaar op dezelfde Gregoriaanse datum. Ook programma en locatie verschillen per provincie. Gebruik alleen een bron die het juiste kalenderjaar en de concrete stad benoemt."},
  {question:"Is Yi Peng hetzelfde als Loy Krathong?",answer:"Ze kunnen in Noord-Thailand in dezelfde periode zichtbaar zijn, maar hebben een andere regionale en ceremoniële context. Vermeng een lokaal Loi Krathong-programma niet automatisch met een Yi Peng- of ticketed lantaarnevent; controleer naam, organisator en locatie afzonderlijk."},
  {question:"Moet je tickets kopen voor festivals in Thailand?",answer:"Niet altijd. Veel openbare tradities en ceremonies hebben geen algemeen toegangsticket, terwijl concerten, tribunes, georganiseerde diners of besloten activiteiten wel ticketed kunnen zijn. Controleer of een verkoper toegang tot het echte evenement aanbiedt of slechts een omliggende tour."},
];

export default function ThailandFestivalsEventsGuideNl(){
  const subId=useSubId();
  const klookHref=withPlacementSubId(KLOOK_GENERIC,subId,"festivals-events-thailand-nl-cultural");
  const pageUrl="https://go2-thailand.com/nl/travel-guides/festivals-events-thailand/";
  const schemas=[
    {"@context":"https://schema.org","@type":"Article",headline:"Festivals in Thailand: betekenis, editie en reisplanning",description:"Kies een festivalprofiel en controleer actuele datum, locatie, toegang, vervoer, gedrag en programma.",image:"https://go2-thailand.com/images/redesign/thailand-festivals-events-hero-v2.webp",url:pageUrl,inLanguage:"nl-NL",author:{"@type":"Organization",name:"GO2 Thailand"},publisher:{"@type":"Organization",name:"GO2 Thailand"},dateModified:"2026-07-31"},
    {"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(({question,answer})=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))},
    {"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Thailand",item:"https://go2-thailand.com/nl/"},{"@type":"ListItem",position:2,name:"Reisgidsen",item:"https://go2-thailand.com/nl/travel-guides/"},{"@type":"ListItem",position:3,name:"Festivals en evenementen",item:pageUrl}]},
  ];
  return <>
    <SEOHead title="Festivals Thailand: Songkran, Loy Krathong en meer" description="Plan festivals in Thailand met betekenis én actuele editiecontrole. Verifieer datum, locatie, toegang, vervoer, gedrag en programma vóór vertrek." ogImage="https://go2-thailand.com/images/redesign/thailand-festivals-events-hero-v2.webp">{schemas.map((schema,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>)}</SEOHead>
    <div data-premium-template="festivals-events-thailand-nl" className="overflow-hidden bg-canvas text-charcoal">
      <EditorialHero image="/images/redesign/thailand-festivals-events-hero-v2.webp" imageAlt="Lokale families en reizigers nemen respectvol deel aan een lichttraditie aan het water in Thailand" breadcrumbs={[{label:"Thailand",href:"/"},{label:"Reisgidsen",href:"/travel-guides/"},{label:"Festivals"}]} eyebrow="Vier de traditie, check de editie" title={<>Thailand viert.<br/><span className="text-saffron-light">Jij plant mee.</span></>} subtitle="Een festivalnaam is nog geen bevestigd programma." description="Kies betekenis en plaats eerst. Controleer daarna kalenderjaar, datum, locatie, toegang, vervoer en lokale instructies—vlak voordat je de reis erop bouwt." actions={[{label:"Vergelijk festivalprofielen",href:"#profielen",kind:"primary"},{label:"Open de editiecheck",href:"#editiecheck",kind:"secondary"}]} contentTone="light" gradientClassName="bg-[linear-gradient(90deg,rgba(2,24,21,.98)_0%,rgba(2,24,21,.91)_43%,rgba(2,24,21,.22)_69%,rgba(2,24,21,.02)_100%)]" imageClassName="object-cover object-[65%_center]" titleClassName="max-w-[760px] text-[4rem] leading-[.84] !text-white sm:text-[5rem] lg:text-[5.8rem]" subtitleClassName="max-w-[620px] text-[1.35rem] leading-[1.12] !text-white sm:text-[1.6rem]" descriptionClassName="mt-4 max-w-[610px] text-sm leading-7 !text-white/75"/>
      <PageSectionNav items={[{href:"#profielen",label:"Festival kiezen",icon:Flower2},{href:"#editiecheck",label:"Editie checken",icon:CalendarCheck},{href:"#deelnemen",label:"Deelnemen",icon:ShieldCheck},{href:"#vragen",label:"Vragen",icon:Sparkles}]}/>
      <section className="section-divider-bottom bg-jade py-5 text-white"><div className="container-custom grid gap-3 sm:grid-cols-3">{[{k:"Evergreen",v:"Betekenis en traditie",I:MoonStar},{k:"Veranderlijk",v:"Datum, locatie en programma",I:CalendarCheck},{k:"Jouw route",v:"Toegang en terugweg",I:Route}].map(({k,v,I})=><div key={k} className="flex min-h-20 items-center gap-4 rounded-xl border border-white/12 bg-white/7 px-5 py-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-saffron text-jade"><I size={20}/></span><span><span className="block text-[9px] font-extrabold uppercase tracking-[.15em] text-white/55">{k}</span><strong className="font-display text-xl">{v}</strong></span></div>)}</div></section>
      <section id="profielen" className="section-divider-bottom scroll-mt-24 py-14 lg:py-20"><div className="container-custom"><SectionHeading eyebrow="Geen festival-toplijst" title={<>Vier profielen.<br/>Vier manieren om mee te doen.</>} description="Dezelfde festivalnaam kan per stad anders voelen. Kies eerst traditie en route; verifieer daarna de concrete editie."/><div className="mt-9 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{profiles.map(({title,tag,period,copy,verify,icon:Icon},index)=><article key={title} className="flex min-h-[410px] flex-col rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl border border-saffron/25 bg-saffron/8 text-jade"><Icon size={21}/></span><span className="font-display text-4xl text-jade/12">0{index+1}</span></div><p className="mt-7 text-[9px] font-extrabold uppercase tracking-[.15em] text-saffron-dark">{tag}</p><h3 className="mt-2 font-display text-[1.7rem] font-semibold leading-none text-jade">{title}</h3><p className="mt-3 text-[10px] font-extrabold text-charcoal/52">{period}</p><p className="mt-4 text-xs font-medium leading-6 text-charcoal/68">{copy}</p><p className="mt-auto border-t border-jade/10 pt-4 text-[10px] font-semibold leading-5 text-charcoal/50">Verifieer: {verify}</p></article>)}</div></div></section>
      <section id="editiecheck" className="section-divider-bottom scroll-mt-24 bg-tonal py-14 lg:py-20"><div className="container-custom grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div className="lg:sticky lg:top-28"><SectionHeading eyebrow="Gebruikelijke periode ≠ bevestigd programma" title="Vijf vragen vóór je boekt" description="Zet kalenderjaar en plaats naast iedere datum. Als één van beide ontbreekt, is de informatie te zwak voor je reisplan."/><div className="mt-7 rounded-2xl border border-saffron/25 bg-white p-5"><p className="text-[9px] font-extrabold uppercase tracking-[.15em] text-saffron-dark">Freshnessregel</p><p className="mt-3 text-xs font-medium leading-6 text-charcoal/68">Controleer opnieuw zodra je route vastligt én kort voor vertrek. Bewaar een alternatief dat niet van één eventslot afhankelijk is.</p></div></div><div className="grid gap-4 sm:grid-cols-2">{checks.map(({title,copy,icon:Icon},index)=><article key={title} className={`min-h-[235px] rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card ${index===4?'sm:col-span-2':''}`}><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-full bg-jade text-saffron"><Icon size={20}/></span><span className="text-[10px] font-extrabold tracking-[.15em] text-saffron-dark">CHECK 0{index+1}</span></div><h3 className="mt-6 font-display text-[1.65rem] font-semibold leading-none text-jade">{title}</h3><p className="mt-4 max-w-2xl text-xs font-medium leading-6 text-charcoal/66">{copy}</p></article>)}</div></div></section>
      <section id="deelnemen" className="section-divider-bottom scroll-mt-24 py-14 lg:py-20"><div className="container-custom"><div className="grid overflow-hidden rounded-[1.7rem] bg-jade text-white shadow-editorial-card lg:grid-cols-[1.02fr_.98fr]"><div className="relative min-h-[430px]"><Image src="/images/redesign/ubon-ratchathani-candle-festival.webp" alt="Culturele processie tijdens een regionaal Thais kaarsenfestival" fill sizes="(max-width:1024px) 100vw, 52vw" className="object-cover"/></div><div className="p-7 lg:p-10"><p className="eyebrow !text-saffron-light">Gast, geen hoofdrol</p><h2 className="font-display text-[3.15rem] font-semibold leading-[.89] tracking-[-.04em]">Doe mee zonder de betekenis weg te duwen</h2><ul className="mt-7 space-y-3">{["Volg tempel-, ceremonie-, water- en kledinginstructies ter plaatse","Vraag toestemming voor close-upbeelden en blokkeer geen processie of ritueel","Gebruik alleen lokaal toegestane materialen en laat niets achter in water of straat","Respecteer droge zones, ouderen, kinderen, monniken en mensen die niet willen deelnemen","Maak telefoon, documenten, ontmoetingspunt en rustige terugweg vooraf concreet"].map(item=><li key={item} className="flex gap-3 text-xs font-medium leading-5 text-white/72"><span className="mt-.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-saffron text-jade"><Check size={12} strokeWidth={3}/></span>{item}</li>)}</ul></div></div></div></section>
      <section className="section-divider-bottom bg-tonal py-14 lg:py-20"><div className="container-custom grid gap-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><SectionHeading eyebrow="Boek alleen een echte vervolgstap" title="Controleer activiteit en toegang apart" description="Een culturele tour kan context geven, maar bewijst niet dat een openbaar festival een ticket vraagt of dat een specifieke editie doorgaat."/><AffiliateDisclosure className="mt-5">Klook-affiliatelink: we kunnen commissie ontvangen zonder extra kosten voor jou. Controleer kalenderjaar, activiteit, organisator, inclusies, toegang, prijs en annuleringsvoorwaarden zelf.</AffiliateDisclosure></div><div className="rounded-2xl bg-jade p-7 text-white"><TicketCheck className="text-saffron"/><h3 className="mt-5 font-display text-3xl font-semibold">Culturele activiteiten vergelijken</h3><p className="mt-3 text-xs font-medium leading-6 text-white/65">Gebruik dit als aanvullende activiteit, niet als bewijs van toegang tot Songkran, Loi Krathong of Yi Peng.</p><a href={klookHref} target="_blank" rel="noopener noreferrer nofollow sponsored" className="btn-cream mt-6 min-h-12 px-6 text-saffron-dark">Bekijk actuele activiteiten <ExternalLink size={15}/></a></div></div></section>
      <section className="section-divider-bottom py-14 lg:py-20"><div className="container-custom grid gap-9 lg:grid-cols-[.68fr_1.32fr]"><div><p className="eyebrow">OneLink · één natte dagtaak</p><h2 className="font-display text-[3.1rem] font-semibold leading-[.9] text-jade">Droog bewaren.<br/>Verder niets.</h2><p className="mt-5 text-sm font-medium leading-7 text-charcoal/65">Geen festivalgadget of willekeurige outfit. Alleen een mogelijke opbergtaak bij Songkran of regen.</p></div><div><article className="flex min-h-[245px] flex-col rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card"><Droplets className="text-jade"/><h3 className="mt-6 font-display text-[1.7rem] font-semibold text-jade">Dry bag voor documenten of droge laag</h3><p className="mt-4 flex-1 text-xs font-medium leading-6 text-charcoal/62">Controleer maat, sluiting, productspecificaties en verkoper. Geen garantie voor elektronica en geen vervanging voor een rustig vervoer- of crowdplan.</p><a href="/go/earth-pak-dry-bag/" target="_blank" rel="noopener noreferrer nofollow sponsored" className="mt-6 inline-flex items-center gap-2 text-[10px] font-extrabold text-saffron-dark">Bekijk actuele prijs bij Amazon <ExternalLink size={12}/></a></article><AffiliateDisclosure className="mt-4">Als Amazon-partner verdienen wij aan in aanmerking komende aankopen, zonder extra kosten voor jou. OneLink kan doorsturen naar een lokale winkel; product, verkoper, prijs en beschikbaarheid verschillen.</AffiliateDisclosure></div></div></section>
      <div id="vragen"><FaqSplitSection eyebrow="Echte zoekvragen" title="Veelgestelde vragen over festivals in Thailand" description="Antwoorden die betekenis scheiden van de veranderlijke editie en ticketstatus." items={faqs}/></div>
      <RelatedGuidesSection title="Kies de juiste festivalbasis" guides={[{title:"Bangkok",description:"Plan buurten, vervoer en een rustige terugweg rond grote stadsprogramma’s.",href:"/city/bangkok/",image:"/images/redesign/bangkok-destination-hero.webp"},{title:"Chiang Mai",description:"Verdiep Lanna-context, oude stad en lokale verplaatsingen.",href:"/city/chiang-mai/",image:"/images/redesign/pai-food-valley-lanterns-nl.webp"},{title:"Sukhothai",description:"Combineer erfgoedcontext met een bevestigde lokale editie.",href:"/city/sukhothai/",image:"/images/redesign/sukhothai-destination-hero.webp"}]}/>
      <SourceMethodSection title="De betekenis blijft, de editie verandert" description="Nederlandse PAA en SERP zijn op 31 juli 2026 zichtbaar gecontroleerd. TAT onderbouwt festivalcontext en publiceert jaarspecifieke locaties en updates; controleer de juiste editie opnieuw voordat je vervoer of toegang boekt." sources={[{title:"Festivals in Thailand",creator:"Tourism Authority of Thailand",url:"https://www.tourismthailand.org/Experiences/Details/festivals/29",note:"Officiële evergreen context over nationale, religieuze, folkloristische en regionale festivals."},{title:"Songkran Festival 2026",creator:"TAT Newsroom",url:"https://www.tatnews.org/2026/03/songkran-festival-2026-to-proceed-nationwide-welcoming-global-visitors-to-thailands-unesco-recognised-new-year-celebration/",note:"Voorbeeld van een jaarspecifieke bevestiging met uiteenlopende lokale programma’s."},{title:"Loi Krathong 2025",creator:"Tourism Authority of Thailand",url:"https://www.tourismthailand.org/Articles/loi-krathong-2025-all-area-en",note:"Voorbeeld van plaatsgebonden data, locaties en programmavormen binnen één editie."},{title:"Official event updates",creator:"Tourism Authority of Thailand",url:"https://thai.tourismthailand.org/Articles/tat-events-update",note:"Laat zien waarom actuele programma- en locatiewijzigingen apart moeten worden gecontroleerd."}]}/>
    </div>
  </>;
}
