import Link from 'next/link';
import { ArrowRight, CalendarRange, Compass, HousePlug, MapPinned, Route, ShieldCheck, WalletCards } from 'lucide-react';
import SEOHead from '../SEOHead';
import { EditorialHero } from '../design/EditorialHero';
import { PageSectionNav } from '../design/PageSectionNav';
import { RelatedGuidesSection } from '../design/RelatedGuidesSection';
import { SectionHeading } from '../design/SectionHeading';
import { SourceMethodSection } from '../design/SourceMethodSection';

const dimensions = [
  { id: 'kosten', title: 'Kosten', eyebrow: 'Persoonlijke bandbreedte', question: 'Wat verandert jouw totaal?', answer: 'Reisdata, hotelstijl, aantal lange trajecten, regio en betaalde activiteiten. De planner rekent scenario’s; de aanbieder toont de actuele prijs.', href: '/thailand-index/budget/', label: 'Open de budgetplanner', icon: WalletCards, accent: 'bg-saffron/12' },
  { id: 'seizoen', title: 'Reisvenster', eyebrow: 'Regio en kust', question: 'Wanneer past jouw route?', answer: 'Vergelijk de maanden voor je exacte steden, eilanden en kust. Weer, luchtkwaliteit en zeeconditie kunnen per netwerk verschillen.', href: '/weather/', label: 'Vergelijk het weer', icon: CalendarRange, accent: 'bg-sky-100' },
  { id: 'vervoer', title: 'Vervoer', eyebrow: 'Traject voor traject', question: 'Welke verbinding is logisch?', answer: 'Kijk naar terminal, vertrekvenster, bagage, overstap en aankomst. Eén landelijke vervoersscore verbergt de echte routebeslissing.', href: '/transport/', label: 'Kies je traject', icon: Route, accent: 'bg-emerald-50' },
  { id: 'veiligheid', title: 'Veiligheid', eyebrow: 'Actuele status en gedrag', question: 'Wat moet je nu controleren?', answer: 'Open reisadvies, lokale instructies, verzekering en de voorwaarden van de activiteit. Een bestemming krijgt geen eeuwige veiligheidsscore.', href: '/is-thailand-safe/', label: 'Open de veiligheidsgids', icon: ShieldCheck, accent: 'bg-rose-50' },
  { id: 'lang-verblijf', title: 'Langer verblijf', eyebrow: 'Leefkeuze, geen toeristenranglijst', question: 'Welke basis past bij je maandritme?', answer: 'Vergelijk internet, woningtype, dagelijkse voorzieningen, klimaat en netwerk. Visum, werk en belasting blijven afzonderlijke officiële beslissingen.', href: '/thailand-index/digital-nomad/', label: 'Vergelijk leefbases', icon: HousePlug, accent: 'bg-violet-50' },
];

const useSteps = [
  { number: '01', title: 'Filter eerst je route', copy: 'Kies stad, noord, Isaan of één kustnetwerk. Vergelijk geen plekken die nooit in dezelfde reis passen.' },
  { number: '02', title: 'Open één dimensie', copy: 'Los kosten, seizoen, vervoer of veiligheid op bij de owner met de juiste methode en bron.' },
  { number: '03', title: 'Controleer je echte data', copy: 'Gebruik vertrekdatum, hotelbasis en traject. Een indexsignaal is een startpunt, geen boekingsbewijs.' },
];

export default function ThailandDecisionIndexNl() {
  const pageUrl = 'https://go2-thailand.com/nl/thailand-index/';
  const schemas = [
    { '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'Thailand reisindex', description: 'Beslisdashboard voor kosten, reisvenster, vervoer, veiligheid en langer verblijf in Thailand.', url: pageUrl, inLanguage: 'nl-NL', mainEntity: { '@type': 'ItemList', numberOfItems: dimensions.length, itemListElement: dimensions.map((item, index) => ({ '@type': 'ListItem', position: index + 1, name: item.title, url: `https://go2-thailand.com/nl${item.href}` })) } },
    { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Thailand', item: 'https://go2-thailand.com/nl/' }, { '@type': 'ListItem', position: 2, name: 'Thailand reisindex', item: pageUrl }] },
  ];

  return <>
    <SEOHead title="Thailand reisindex: vergelijk de beslissingen" description="Vergelijk Thailand op kosten, reisvenster, vervoer, veiligheid en langer verblijf—zonder schijnexacte totaalscore of vaste prijsranglijst." ogImage="https://go2-thailand.com/images/redesign/thailand-route-rhythm.webp">
      {schemas.map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}
    </SEOHead>
    <div data-premium-template="thailand-decision-index-nl" className="overflow-hidden bg-canvas text-charcoal">
      <EditorialHero image="/images/redesign/thailand-route-rhythm.webp" imageAlt="Visuele reisroute door verschillende landschappen van Thailand" breadcrumbs={[{ label: 'Thailand', href: '/' }, { label: 'Reisindex' }]} eyebrow="Vergelijk de beslissing, niet één magisch cijfer" title={<>Thailand-index.<br /><span className="text-saffron-dark">Wat bepaalt jouw reis?</span></>} subtitle="Vijf owners. Vijf verschillende methodes." description="Kosten, seizoen, vervoer, veiligheid en langer verblijf kun je niet eerlijk optellen tot één universele winnaar. Kies de dimensie die jouw plan nu tegenhoudt." actions={[{ label: 'Open de vijf dimensies', href: '#dimensies', kind: 'primary' }, { label: 'Kies een bestemming', href: '/city/', kind: 'secondary' }]} imageClassName="object-cover object-[62%_center]" />
      <PageSectionNav items={[{ href: '#dimensies', label: 'Dimensies', icon: Compass }, { href: '#gebruiken', label: 'Gebruiken', icon: MapPinned }, { href: '#methode', label: 'Methode', icon: ShieldCheck }]} />

      <section id="dimensies" className="section-divider-bottom scroll-mt-24 py-16 lg:py-24"><div className="container-custom"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><SectionHeading eyebrow="Beslisdashboard" title="Open alleen de vergelijking die je nodig hebt." description="Iedere owner gebruikt andere invoer en een ander controlemoment. Daardoor blijven weer, prijs en beleid bij te werken zonder een verzonnen totaalscore." /><p className="max-w-2xl text-sm font-medium leading-7 text-charcoal/62">Een bestemming kan voordelig zijn maar slecht passen bij je maand, route of zorgbehoefte. Daarom publiceert deze Nederlandse index geen vaste top-10, samengestelde score of eeuwige ‘beste stad’.</p></div><div className="mt-10 grid gap-4 lg:grid-cols-2">{dimensions.map(({ id, title, eyebrow, question, answer, href, label, icon: Icon, accent }, index) => <Link key={id} href={href} className={`group rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card ${index === dimensions.length - 1 ? 'lg:col-span-2' : ''}`}><div className={`grid h-12 w-12 place-items-center rounded-xl ${accent} text-jade`}><Icon size={21} /></div><div className={index === dimensions.length - 1 ? 'lg:grid lg:grid-cols-[.55fr_1fr_auto] lg:items-end lg:gap-8' : ''}><div><p className="mt-5 text-[9px] font-extrabold uppercase tracking-[.14em] text-saffron-dark">{eyebrow}</p><h2 className="mt-2 font-display text-[2.25rem] font-semibold leading-none text-jade">{title}</h2></div><div><h3 className="mt-4 text-sm font-extrabold text-charcoal">{question}</h3><p className="mt-2 text-xs font-medium leading-6 text-charcoal/64">{answer}</p></div><span className="mt-5 inline-flex min-h-11 items-center gap-2 text-xs font-extrabold text-jade">{label} <ArrowRight size={13} className="text-saffron-dark transition group-hover:translate-x-1" /></span></div></Link>)}</div></div></section>

      <section id="gebruiken" className="section-divider-bottom scroll-mt-24 bg-tonal py-16 lg:py-24"><div className="container-custom grid gap-10 lg:grid-cols-[.68fr_1.32fr]"><SectionHeading eyebrow="Zo gebruik je de index" title="Van breed signaal naar echte keuze." description="De index helpt je de volgende vraag te vinden. De definitieve beslissing ontstaat pas met jouw route, data en actuele voorwaarden." /><div className="grid gap-4">{useSteps.map((step) => <article key={step.number} className="grid gap-5 rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card sm:grid-cols-[auto_1fr]"><span className="grid h-11 w-11 place-items-center rounded-full bg-jade text-xs font-black text-saffron">{step.number}</span><div><h2 className="font-display text-[1.8rem] font-semibold leading-none text-jade">{step.title}</h2><p className="mt-3 text-xs font-medium leading-6 text-charcoal/64">{step.copy}</p></div></article>)}</div></div></section>

      <section id="methode" className="section-divider-bottom scroll-mt-24 py-16 lg:py-24"><div className="container-custom rounded-[28px] bg-jade p-7 text-white lg:grid lg:grid-cols-[.72fr_1.28fr] lg:gap-12 lg:p-10"><div><p className="eyebrow !text-saffron">Wat we bewust niet doen</p><h2 className="font-display text-[3rem] font-semibold leading-[.9]">Geen score zonder reproduceerbare dataset.</h2></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:mt-0">{['Geen vaste dollarprijs per dag', 'Geen universele beste maand', 'Geen veiligheidsranglijst', 'Geen gewogen totaalscore', 'Geen beste nomadenstad voor iedereen', 'Geen providerprijs als eigen data'].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl border border-white/12 bg-white/5 p-4 text-xs font-bold text-white/72"><ShieldCheck size={16} className="shrink-0 text-saffron" />{item}</div>)}</div></div></section>

      <RelatedGuidesSection eyebrow="Meer context nodig?" title="Begin vanuit route, onderwerp of bestemming" guides={[{ title: 'Complete Thailand-reisgids', description: 'Zet reisvenster, route, toegang en kosten in de juiste volgorde.', href: '/thailand-travel-guide/', image: '/images/redesign/thailand-travel-guide-hero-v2.webp', imageAlt: 'Thailandreis plannen' }, { title: 'Themagidsen', description: 'Vind gezondheid, connectiviteit, natuur, cultuur en praktische owners.', href: '/travel-guides/', image: '/images/redesign/thailand-practical-hub-hero-nl.webp', imageAlt: 'Thailand themagidsen' }, { title: 'Bestemmingen', description: 'Open de lokale owner voor stad, regio of eiland.', href: '/city/', image: '/images/redesign/thailand-route-rhythm.webp', imageAlt: 'Bestemmingen in Thailand' }]} />
      <SourceMethodSection eyebrow="Bronnen per dimensie" title="Elke vergelijking krijgt zijn eigen primaire bron" description="Kosten verwijzen naar actuele quotes en financiële context, weer naar meteorologische data, veiligheid naar actueel reisadvies en bestemmingcontext naar officiële toerisme-informatie. De gespecialiseerde owner documenteert de volledige methode." sources={[{ title: 'Wisselkoersen en financiële statistiek', creator: 'Bank of Thailand', url: 'https://www.bot.or.th/en/statistics/exchange-rate.html', note: 'Primaire financiële context; geen vervanging voor actuele aanbiederprijzen.' }, { title: 'Weer en waarschuwingen', creator: 'Thai Meteorological Department', url: 'https://www.tmd.go.th/en', note: 'Actuele meteorologische bron voor regio- en kustbeslissingen.' }, { title: 'Reisadvies Thailand', creator: 'NederlandWereldwijd', url: 'https://www.nederlandwereldwijd.nl/reisadvies/thailand', note: 'Actuele Nederlandse veiligheids- en toegangscontext.' }, { title: 'Bestemmingen', creator: 'Tourism Authority of Thailand', url: 'https://www.tourismthailand.org/Destinations', note: 'Officiële startbron voor regio- en bestemmingcontext.' }]} />
    </div>
  </>;
}
