import Link from 'next/link';
import {
  ArrowRight, BookOpenCheck, Building2, CalendarDays, Check, Church, CircleHelp,
  Compass, Eye, Footprints, Landmark, LibraryBig, MapPinned, MessagesSquare,
  ScrollText, Sparkles, UsersRound,
} from 'lucide-react';
import SEOHead from '../SEOHead';
import { EditorialHero } from '../design/EditorialHero';
import { FaqSplitSection } from '../design/FaqSplitSection';
import { PageSectionNav } from '../design/PageSectionNav';
import { RelatedGuidesSection } from '../design/RelatedGuidesSection';
import { SectionHeading } from '../design/SectionHeading';
import { SourceMethodSection } from '../design/SourceMethodSection';

const PAGE_URL = 'https://go2-thailand.com/nl/travel-guides/history-culture-thailand/';
const HERO = '/images/redesign/thailand-history-culture-hero-v2.webp';

const periods = [
  { era: 'Vóór de nationale tijdlijn', title: 'Meerdere werelden', copy: 'Het gebied van het huidige Thailand kende Mon-, Khmer- en maritieme netwerken, Dvaravati-steden en uiteenlopende lokale gemeenschappen. Sukhothai is dus een belangrijke laag, niet het absolute begin van alles.', see: 'Ban Chiang, Si Thep, Phu Phrabat en Khmer-erfgoed laten andere vertrekpunten zien.', icon: Footprints },
  { era: '13e–15e eeuw', title: 'Sukhothai, Lanna & buren', copy: 'Sukhothai groeide uit tot een belangrijk Tai-koninkrijk. Tegelijk ontwikkelden Lanna en andere regionale machtscentra hun eigen politieke, religieuze en artistieke tradities.', see: 'Lees kunst, schrift en boeddhistische architectuur naast de regionale machtskaart.', icon: Landmark },
  { era: '14e–18e eeuw', title: 'Ayutthaya als netwerkstad', copy: 'Ayutthaya was een koninkrijk én internationaal handelscentrum met relaties en gemeenschappen uit Azië, Europa en de islamitische wereld. De ruïnes tonen maar een deel van die kosmopolitische stad.', see: 'Combineer tempelruïnes met museum, rivierlogica en buitenlandse nederzettingen.', icon: Building2 },
  { era: '1767–heden', title: 'Thonburi, Bangkok & staat', copy: 'Na de val van Ayutthaya volgden Thonburi en vanaf 1782 Rattanakosin. De negentiende en twintigste eeuw brachten centralisering, hervormingen, koloniale druk en in 1932 de constitutionele omwenteling.', see: 'Bangkok toont hof-, handels-, migratie- en moderniseringslagen naast elkaar.', icon: ScrollText },
];

const lenses = [
  { title: 'Archeologische site', question: 'Wat is origineel, hersteld of gereconstrueerd?', copy: 'Open het siteplan en museum vóór je foto’s maakt. Een ruïne vertelt pas iets wanneer functie, periode en latere restauratie duidelijk zijn.', action: 'Controleer site- en museumstatus', icon: Landmark },
  { title: 'Actieve religieuze plek', question: 'Is dit erfgoed én gebedsruimte?', copy: 'Observeer bezoekersgedrag, ceremonies en afgezette zones. Lokale kleding- en fotoregels gaan vóór een generieke tempeltip.', action: 'Volg de etiquette-owner', icon: Church },
  { title: 'Museum & interpretatie', question: 'Wie vertelt dit verhaal?', copy: 'Vergelijk objectlabel, datering, herkomst en perspectief. Een nationaal museum, lokaal museum en communityproject kunnen andere lagen zichtbaar maken.', action: 'Lees meer dan één label', icon: LibraryBig },
  { title: 'Levende traditie', question: 'Is dit een evenement, vaardigheid of gemeenschap?', copy: 'UNESCO-inschrijving betekent bescherming van kennis en praktijk, niet dat een traditie voor toeristen wordt opgevoerd of overal hetzelfde is.', action: 'Controleer datum en lokale context', icon: UsersRound },
];

const destinations = [
  { number: '01', title: 'Sukhothai', href: '/city/sukhothai/', subtitle: 'Stad, park en museum', copy: 'Gebruik Sukhothai om vroege Tai-kunst en koningschap te plaatsen, maar benoem ook Lanna, Mon, Khmer en andere regionale tijdlijnen.' },
  { number: '02', title: 'Ayutthaya', href: '/city/ayutthaya/', subtitle: 'Handel, diplomatie en ruïnes', copy: 'Lees Ayutthaya als rivier- en wereldstad. Combineer tempelarchitectuur met handelsgemeenschappen en de breuk van 1767.' },
  { number: '03', title: 'Bangkok & Thonburi', href: '/city/bangkok/', subtitle: 'Hof, migratie en moderniteit', copy: 'Leg Grand Palace en Rattanakosin naast Thonburi, Yaowarat, rivierhandel, musea en moderne stedelijke ontwikkeling.' },
];

const faqs = [
  { question: 'Wat is de geschiedenis van Thailand?', answer: 'Een bruikbare nationale tijdlijn loopt van oudere Mon-, Khmer- en regionale culturen via Sukhothai, Lanna en Ayutthaya naar Thonburi, Rattanakosin en de moderne constitutionele staat. Die lijn is niet volledig: Isaan, het noorden en het zuiden hebben ook eigen, grensoverschrijdende geschiedenissen.' },
  { question: 'Wat is de cultuur van Thailand?', answer: 'Er bestaat niet één uniforme Thaise cultuur. Religie, taal, eten, kunst, familie, hoftradities, migratie en regionale gemeenschappen beïnvloeden elkaar. Boeddhistische, hindoeïstische, islamitische, christelijke, Chinese en lokale praktijken zijn in verschillende combinaties zichtbaar.' },
  { question: 'Wat maakt de Thaise cultuur bijzonder?', answer: 'Niet één eigenschap, maar de manier waarop uiteenlopende tradities naast en door elkaar bestaan: tempel en geestenhuis, hofkunst en markt, regionale taal en nationaal onderwijs, levend ritueel en toeristische presentatie. Vermijd uitspraken als “Thai zijn altijd…”; context en persoon verschillen.' },
  { question: 'Hoe heette Thailand vroeger?', answer: 'Siam was de internationaal gebruikte landsnaam vóór de naamswijziging naar Thailand in 1939. De naam Siam werd kort opnieuw gebruikt na de Tweede Wereldoorlog, waarna Thailand in 1949 weer de officiële naam werd.' },
  { question: 'Is Thailand ooit een kolonie geweest?', answer: 'Thailand werd niet formeel gekoloniseerd door een Europese mogendheid. “Nooit gekoloniseerd” betekent niet dat het buiten koloniale machtsverhoudingen stond: Siam moderniseerde, onderhandelde en stond gebieden af onder Britse en Franse druk.' },
  { question: 'Was Sukhothai het eerste koninkrijk van Thailand?', answer: 'Sukhothai geldt vaak als een vroeg onafhankelijk Tai-koninkrijk en is belangrijk in de nationale geschiedschrijving. Het was niet de eerste samenleving of staat op het grondgebied van het huidige Thailand; oudere Mon-, Khmer-, Dvaravati- en andere regionale culturen gingen eraan vooraf.' },
  { question: 'Wat was het verschil tussen Sukhothai en Ayutthaya?', answer: 'Sukhothai was een eerder noord-centraal Tai-koninkrijk dat bekendstaat om kunst, schrifttraditie en boeddhistisch erfgoed. Ayutthaya groeide later uit tot een groter, langdurig koninkrijk en internationaal handelscentrum. Hun periodes overlapten deels; het is geen eenvoudige opvolging op één dag.' },
  { question: 'Welke culturele plekken moet je bezoeken in Thailand?', answer: 'Kies per vraag: Sukhothai voor vroege Tai-kunst en historische stadsplanning, Ayutthaya voor koninkrijk en wereldhandel, Bangkok/Thonburi voor Rattanakosin en modernisering, en een regionale plek voor Lanna, Isaan, Mon, Khmer of zuidelijke geschiedenis.' },
  { question: 'Is Thailand alleen boeddhistisch?', answer: 'Nee. Theravada-boeddhisme is zeer zichtbaar, maar Thailand kent ook islamitische, christelijke, hindoeïstische, Chinese religieuze en lokale spirituele tradities. Bovendien verschilt de persoonlijke betekenis en praktijk per gemeenschap en individu.' },
  { question: 'Hoe bezoek je een Thaise tempel respectvol?', answer: 'Kijk eerst of het een actieve gebedsruimte is en volg lokale borden en aanwijzingen. Bedek waar gevraagd schouders en knieën, trek schoenen uit vóór aangewezen binnenruimtes, fotografeer niet tijdens ceremonies zonder toestemming en ga nooit op of tegen religieuze objecten zitten.' },
];

const sources = [
  { title: 'World Heritage in Thailand', creator: 'UNESCO World Heritage Centre', url: 'https://whc.unesco.org/en/statesparties/th', note: 'Primaire lijst van materiële werelderfgoedsites en inschrijvingsjaren.' },
  { title: 'Intangible Cultural Heritage in Thailand', creator: 'UNESCO', url: 'https://ich.unesco.org/en/state/thailand-TH', note: 'Primaire lijst van ingeschreven levende erfgoedpraktijken; onderscheidt levende traditie van monument.' },
  { title: 'Khon masked dance drama', creator: 'UNESCO', url: 'https://ich.unesco.org/en/RL/khon-masked-dance-drama-in-thailand-01385', note: 'Primaire omschrijving van Khon als samenspel van uitvoering, muziek, literatuur, ritueel en ambacht.' },
  { title: 'Songkran in Thailand', creator: 'UNESCO', url: 'https://ich.unesco.org/en/RL/songkran-in-thailand-traditional-thai-new-year-festival-01719', note: 'Primaire context voor Songkran als traditionele nieuwjaarspraktijk, niet alleen waterfeest.' },
  { title: 'History & Geography', creator: 'Tourism Authority of Thailand', url: 'https://www.tourismthailand.org/Articles/plan-your-trip-history-and-geography-geology', note: 'Officiële toeristische periodisering en context voor Dvaravati, Khmer, Lanna, Sukhothai en Ayutthaya.' },
];

function schemas() {
  return [
    { '@context': 'https://schema.org', '@type': 'Article', headline: 'Geschiedenis en cultuur van Thailand voor reizigers', description: 'Lees de geschiedenis van Thailand in meerdere tijdlagen en bezoek erfgoed, tempels, musea en levende tradities met context.', url: PAGE_URL, image: `https://go2-thailand.com${HERO}`, inLanguage: 'nl-NL', dateModified: '2026-07-31', author: { '@type': 'Organization', name: 'GO2 Thailand' }, publisher: { '@type': 'Organization', name: 'GO2 Thailand' } },
    { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Thailand', item: 'https://go2-thailand.com/nl/' }, { '@type': 'ListItem', position: 2, name: 'Reisgidsen', item: 'https://go2-thailand.com/nl/travel-guides/' }, { '@type': 'ListItem', position: 3, name: 'Geschiedenis & cultuur', item: PAGE_URL }] },
    { '@context': 'https://schema.org', '@type': 'ItemList', name: 'Vier tijdlagen in de geschiedenis van Thailand', numberOfItems: periods.length, itemListElement: periods.map((item, index) => ({ '@type': 'ListItem', position: index + 1, name: item.title, description: item.copy })) },
    { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(item => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) },
  ];
}

export default function ThailandHistoryCultureGuideNl() {
  return <div className="overflow-hidden bg-canvas text-charcoal" data-premium-template="history-culture-thailand-nl">
    <SEOHead title="Geschiedenis en cultuur Thailand: lees de lagen" description="Ontdek de geschiedenis en cultuur van Thailand via vier tijdlagen, erfgoedsteden, tempels, musea en levende tradities—zonder clichés." ogImage={`https://go2-thailand.com${HERO}`}>
      {schemas().map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}
    </SEOHead>

    <EditorialHero image={HERO} imageAlt="Erfgoedgids geeft twee reizigers uitleg bij historische bakstenen tempelruïnes in Thailand" breadcrumbs={[{ label: 'Thailand', href: '/' }, { label: 'Reisgidsen', href: '/travel-guides/' }, { label: 'Geschiedenis & cultuur' }]} eyebrow="Erfgoed is meer dan een jaartal" title={<>Lees de lagen.<br /><span className="text-saffron-light">Niet alleen de ruïnes.</span></>} subtitle="Van oudere regionale werelden tot levend Thailand." description="Gebruik vier tijdlagen om Sukhothai, Ayutthaya, Bangkok en regionale cultuur te plaatsen. Bekijk daarna iedere plek door de juiste lens: archeologie, religie, museum of levende traditie." actions={[{ label: 'Open de tijdlagen', href: '#tijdlagen', kind: 'primary' }, { label: 'Kies je kijklens', href: '#kijklenzen', kind: 'secondary' }]} contentTone="light" gradientClassName="bg-[linear-gradient(90deg,rgba(3,27,22,.98)_0%,rgba(3,27,22,.91)_41%,rgba(3,27,22,.24)_69%,rgba(3,27,22,.03)_100%)]" imageClassName="object-cover object-[68%_center]" titleClassName="max-w-[870px] text-[3.7rem] leading-[.84] !text-white sm:text-[4.8rem] lg:text-[5.55rem]" subtitleClassName="max-w-[650px] text-[1.35rem] leading-[1.12] !text-white sm:text-[1.6rem]" descriptionClassName="mt-4 max-w-[630px] text-sm leading-7 !text-white/75" />
    <PageSectionNav items={[{ href: '#tijdlagen', label: 'Tijdlagen', icon: ScrollText }, { href: '#kijklenzen', label: 'Kijklenzen', icon: Eye }, { href: '#erfgoedroute', label: 'Erfgoedroute', icon: MapPinned }, { href: '#vragen', label: 'Vragen', icon: Sparkles }]} />

    <section className="section-divider-bottom bg-jade py-5 text-white"><div className="container-custom grid gap-3 sm:grid-cols-3">{[
      { key: 'Geschiedenis', value: 'Meer dan één centrum', icon: Compass }, { key: 'Erfgoed', value: 'Materieel én levend', icon: Landmark }, { key: 'Bezoek', value: 'Context vóór camera', icon: Eye },
    ].map(({ key, value, icon: Icon }) => <div key={key} className="flex min-h-20 items-center gap-4 rounded-xl border border-white/12 bg-white/7 px-5 py-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-saffron text-jade"><Icon size={20} aria-hidden="true" /></span><span><span className="block text-[9px] font-extrabold uppercase tracking-[.15em] text-white/55">{key}</span><strong className="font-display text-xl">{value}</strong></span></div>)}</div></section>

    <section id="tijdlagen" className="section-divider-bottom scroll-mt-24 py-14 lg:py-20"><div className="container-custom"><SectionHeading eyebrow="Een tijdlijn is een hulpmiddel, geen eindpunt" title={<>Vier tijdlagen.<br />Meerdere perspectieven.</>} description="De klassieke reeks Sukhothai–Ayutthaya–Bangkok helpt oriënteren, maar laat oudere en regionale geschiedenissen snel buiten beeld. Lees daarom iedere laag naast de kaart." /><div className="mt-9 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{periods.map(({ era, title, copy, see, icon: Icon }, index) => <article key={title} className="flex min-h-[410px] flex-col rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl border border-saffron/25 bg-saffron/8 text-jade"><Icon size={21} aria-hidden="true" /></span><span className="font-display text-4xl text-jade/12">0{index + 1}</span></div><p className="mt-7 text-[9px] font-extrabold uppercase tracking-[.15em] text-saffron-dark">{era}</p><h3 className="mt-2 font-display text-[1.7rem] font-semibold leading-none text-jade">{title}</h3><p className="mt-4 text-xs font-medium leading-6 text-charcoal/68">{copy}</p><p className="mt-auto border-t border-jade/10 pt-4 text-[10px] font-semibold leading-5 text-charcoal/52">Ter plaatse: {see}</p></article>)}</div></div></section>

    <section id="kijklenzen" className="section-divider-bottom scroll-mt-24 bg-tonal py-14 lg:py-20"><div className="container-custom grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div className="lg:sticky lg:top-28"><SectionHeading eyebrow="Kijk eerst wat voor plek dit is" title="Vier lenzen voor één reisdag" description="Een ruïne, actief tempelcomplex, museum en festival vragen niet dezelfde voorbereiding of hetzelfde gedrag." /><div className="mt-7 rounded-2xl border border-saffron/25 bg-white p-5"><p className="text-[9px] font-extrabold uppercase tracking-[.15em] text-saffron-dark">Open vraag</p><p className="mt-3 text-xs font-medium leading-6 text-charcoal/68">Vraag bij ieder verhaal: welke periode, regio, bron en gemeenschap zie ik—en welke laag ontbreekt nog?</p></div></div><div className="grid gap-4 sm:grid-cols-2">{lenses.map(({ title, question, copy, action, icon: Icon }, index) => <article key={title} className="flex min-h-[300px] flex-col rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-full bg-jade text-saffron"><Icon size={20} aria-hidden="true" /></span><span className="text-[10px] font-extrabold tracking-[.15em] text-saffron-dark">LENS 0{index + 1}</span></div><h3 className="mt-7 font-display text-[1.7rem] font-semibold leading-none text-jade">{title}</h3><p className="mt-2 text-xs font-extrabold text-charcoal/75">{question}</p><p className="mt-3 text-xs font-medium leading-6 text-charcoal/64">{copy}</p><p className="mt-auto pt-4 text-[10px] font-extrabold uppercase tracking-[.1em] text-jade">{action}</p></article>)}</div></div></section>

    <section id="erfgoedroute" className="section-divider-bottom scroll-mt-24 py-14 lg:py-20"><div className="container-custom"><SectionHeading eyebrow="Drie steden, drie andere vragen" title="Bouw een erfgoedroute die iets uitlegt" description="Open de lokale owner voor vervoer, verblijf en bezienswaardigheden. Gebruik deze pagina alleen om de historische vraag scherp te krijgen." /><div className="mt-9 grid gap-4 lg:grid-cols-3">{destinations.map(({ number, title, href, subtitle, copy }, index) => <article key={title} className={`flex min-h-[320px] flex-col rounded-2xl p-7 ${index === 1 ? 'bg-jade text-white' : 'border border-jade/10 bg-white shadow-editorial-card'}`}><span className={`text-[9px] font-extrabold uppercase tracking-[.15em] ${index === 1 ? 'text-saffron-light' : 'text-saffron-dark'}`}>Poort {number}</span><h3 className={`mt-5 font-display text-4xl font-semibold ${index === 1 ? 'text-white' : 'text-jade'}`}>{title}</h3><p className={`mt-2 text-xs font-extrabold ${index === 1 ? 'text-white/85' : 'text-charcoal/75'}`}>{subtitle}</p><p className={`mt-5 text-xs font-medium leading-6 ${index === 1 ? 'text-white/68' : 'text-charcoal/66'}`}>{copy}</p><Link href={href} className={`mt-auto inline-flex min-h-11 items-center gap-2 pt-6 text-xs font-extrabold ${index === 1 ? 'text-white' : 'text-jade'}`}>Open de bestemming <ArrowRight size={15} className="text-saffron" aria-hidden="true" /></Link></article>)}</div></div></section>

    <section className="section-divider-bottom bg-jade py-14 text-white lg:py-20"><div className="container-custom grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="eyebrow !text-saffron-light">Levende cultuur is geen checklist</p><h2 className="font-display text-[3.3rem] font-semibold leading-[.88] tracking-[-.04em]">Observeer. Vraag. Pas je aan.</h2><p className="mt-5 max-w-xl text-sm font-medium leading-7 text-white/70">Een wai, festival, maaltijd of religieuze handeling heeft geen universele betekenis voor iedere Thai. Volg de context en laat lokale aanwijzingen zwaarder wegen dan een online lijst “do's & don'ts”.</p><Link href="/practical-info/etiquette-culture/" className="btn-cream mt-7 min-h-12 px-6 text-saffron-dark">Open de etiquette-owner <ArrowRight size={15} aria-hidden="true" /></Link></div><ul className="grid gap-3 sm:grid-cols-2">{['Vraag vóór portret- of ceremoniefoto’s','Klim of leun niet op erfgoed voor een foto','Zie religieuze objecten niet als decor','Controleer lokale regels en actuele toegang'].map(item => <li key={item} className="flex min-h-20 items-center gap-3 rounded-xl border border-white/12 bg-white/7 p-4 text-xs font-semibold leading-5 text-white/75"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-saffron text-jade"><Check size={14} strokeWidth={3} aria-hidden="true" /></span>{item}</li>)}</ul></div></section>

    <section className="section-divider-bottom bg-tonal py-14 lg:py-20"><div className="container-custom"><SectionHeading eyebrow="Monument en praktijk zijn niet hetzelfde" title="Materieel erfgoed. Levend erfgoed." description="UNESCO-werelderfgoed beschermt onder meer locaties; immaterieel erfgoed draait om kennis en praktijken die gemeenschappen doorgeven." /><div className="mt-8 grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-jade/10 bg-white p-7 shadow-editorial-card"><Landmark className="text-saffron-dark" aria-hidden="true" /><h3 className="mt-5 font-display text-3xl font-semibold text-jade">Plaats & object</h3><p className="mt-3 text-xs font-medium leading-6 text-charcoal/67">Ayutthaya, Sukhothai en Ban Chiang staan op de materiële werelderfgoedlijst. Status zegt niets over actuele opening, route of entree; controleer die bij de site.</p></article><article className="rounded-2xl bg-jade p-7 text-white"><MessagesSquare className="text-saffron" aria-hidden="true" /><h3 className="mt-5 font-display text-3xl font-semibold">Kennis & praktijk</h3><p className="mt-3 text-xs font-medium leading-6 text-white/68">Khon, Nuad Thai en Songkran zijn voorbeelden van levende erfgoedpraktijken. Een inschrijving maakt geen enkele uitvoering automatisch “authentieker” dan de gemeenschap die haar draagt.</p></article></div></div></section>

    <div id="vragen"><FaqSplitSection eyebrow="Echte zoekvragen" title="Veelgestelde vragen over geschiedenis en cultuur" description="Antwoorden met ruimte voor regionale variatie en zonder aantallen, prijzen of politieke momentopnames als tijdloos feit te presenteren." items={faqs} /></div>
    <RelatedGuidesSection eyebrow="Verdiep per reistaak" title="Van context naar een respectvol bezoek" readLabel="Open de gids" guides={[{ title: 'Etiquette & omgang', description: 'Vertaal culturele context naar kleding, gebaren, fotografie en dagelijkse situaties.', href: '/practical-info/etiquette-culture/', image: '/images/redesign/thailand-etiquette-hero.webp', imageAlt: 'Respectvolle omgang in Thailand' }, { title: 'Festivals in Thailand', description: 'Controleer datum, plaats, religieuze context en bezoekersgedrag per evenement.', href: '/travel-guides/festivals-events-thailand/', image: '/images/redesign/thailand-festivals-events-hero-v2.webp', imageAlt: 'Cultureel festival in Thailand' }, { title: 'Thaise keuken', description: 'Lees eten als regionale en levende cultuur, niet als één nationale top tien.', href: '/food/', image: '/images/blog/what-is-thai-food-cuisine-guide.webp', imageAlt: 'Regionale Thaise gerechten op tafel' }]} />
    <SourceMethodSection eyebrow="Bronnen & methode" title="Geen nationale tijdlijn is compleet" description="Bijgewerkt op 31 juli 2026 met zichtbare Nederlandse Google-resultaten, echte PAA-vragen, concurrentpatronen en primaire UNESCO- en TAT-bronnen. De legacycopy met kapotte encoding, vaste prijzen en tijden, onbewezen aantallen, lineaire oorsprongsclaims, culturele generalisaties en politieke actualiteit als tijdloos feit is volledig vervangen." sources={sources} />
  </div>;
}
