import Link from 'next/link';
import {
  ArrowRight, Bus, CalendarCheck, Check, CircleHelp, Compass, ExternalLink,
  Footprints, HeartHandshake, Map, MapPin, Route, ShieldCheck, Sparkles,
  Trees, Waves,
} from 'lucide-react';
import SEOHead from '../SEOHead';
import { EditorialHero } from '../design/EditorialHero';
import { FaqSplitSection } from '../design/FaqSplitSection';
import { PageSectionNav } from '../design/PageSectionNav';
import { RelatedGuidesSection } from '../design/RelatedGuidesSection';
import { SectionHeading } from '../design/SectionHeading';
import { SourceMethodSection } from '../design/SourceMethodSection';

const PAGE_URL = 'https://go2-thailand.com/nl/travel-guides/hidden-gems-off-beaten-path-thailand/';
const HERO = '/images/redesign/thailand-hidden-gems-hero-v2.webp';

const destinations = [
  { title: 'Koh Mak', region: 'Eiland · Trat', href: '/islands/koh-mak/', icon: Waves, fit: 'Een langzaam eilandverblijf dat je bewust als hoofdbestemming kiest.', tradeoff: 'De bootketen en mobiliteit op het eiland geven minder speelruimte dan een vaste landroute.', verify: 'Actuele boot, aankomstpier, verblijftransfer, zeeconditie en terugvaart.' },
  { title: 'Mae Hong Son', region: 'Bergen · Noord', href: '/city/mae-hong-son/', icon: Trees, fit: 'Berglandschap, stad en regionale cultuur met tijd voor een langere aan- en afreis.', tradeoff: 'Bochtige wegen, weer en beperkte vluchtopties kunnen je route fragiel maken.', verify: 'Wegconditie of vlucht, reisziekte, zicht, terugweg en lokale sluitingen.' },
  { title: 'Bueng Kan', region: 'Mekong · Isaan', href: '/city/bueng-kan/', icon: Footprints, fit: 'Natuur en Mekongcontext voor wie een zelfstandige noordoostelijke route bouwt.', tradeoff: 'Lange transfers en natuurlocaties buiten de stad vragen extra voorbereiding.', verify: 'Park- of trailstatus, lokaal vervoer, hitte/regen en terugkeertijd.' },
  { title: 'Nakhon Phanom', region: 'Rivierstad · Isaan', href: '/city/nakhon-phanom/', icon: MapPin, fit: 'Een rustige stadsbasis aan de Mekong die ook zonder afgelegen trail betekenis heeft.', tradeoff: 'Een losse omweg is minder logisch dan een regionale combinatie met voldoende nachten.', verify: 'Vlucht of bus, lokaal vervoer, evenementendata en je volgende aansluiting.' },
  { title: 'Chanthaburi', region: 'Stad & kust · Oost', href: '/city/chanthaburi/', icon: Compass, fit: 'Historische stadswijken, eten, fruitregio en kust als afwisselende landstop.', tradeoff: 'Stad, kust en natuur liggen niet allemaal op loopafstand van één basis.', verify: 'Welke zone je kiest, lokaal vervoer, parkstatus en weekend- of feestdagdrukte.' },
  { title: 'Trang', region: 'Stad & eilandpoort · Zuid', href: '/city/trang/', icon: Route, fit: 'Een zuidelijke basis voor eten, stad en een zorgvuldig gekozen eilandketen.', tradeoff: 'Een eilanddag bestaat uit meerdere schakels; slecht weer raakt meer dan alleen de boot.', verify: 'Pier, bootoperator, eilandverblijf, zeeconditie, parkstatus en plan B op het vasteland.' },
];

const gates = [
  { step: '01', title: 'Bouw de toegangsketen', question: 'Kun je ook betrouwbaar terug?', copy: 'Noteer ieder deel: vlucht, trein of bus, lokale transfer, boot of trail en de laatste haalbare terugverbinding. Eén onduidelijke schakel maakt de hele stop kwetsbaar.', icon: Route },
  { step: '02', title: 'Controleer de basis', question: 'Wat heb je werkelijk nodig?', copy: 'Check verblijf, eten, cash of betaling, data, taalhulp en passende zorg. “Rustig” is geen voordeel als een essentiële voorziening voor jou ontbreekt.', icon: ShieldCheck },
  { step: '03', title: 'Lees de dag opnieuw', question: 'Is jouw plan vandaag open?', copy: 'Controleer vlak voor vertrek weer, zee, weg, park, trail en operator. Een blogfoto of oud schema is geen actuele bevestiging.', icon: CalendarCheck },
  { step: '04', title: 'Bewaar een uitweg', question: 'Wat doe je als plan A vervalt?', copy: 'Leg een landoptie, extra nacht of eerdere terugkeer vast. Plan B hoort vóór de reservering in je route, niet pas wanneer een boot of toegang wegvalt.', icon: Map },
];

const faqs = [
  { question: 'Waar is het rustig in Thailand?', answer: 'Dat hangt af van datum, dagdeel, lokale feestdagen en bereikbaarheid. Koh Mak kan rustiger voelen dan een groot vakantie-eiland; Nakhon Phanom of Chanthaburi kan een rustiger stadsritme bieden dan Bangkok. Controleer live vervoer en verblijf, want rust is geen permanente eigenschap.' },
  { question: 'Welk deel van Thailand is rustig?', answer: 'Delen van Isaan, het oosten, het uiterste noorden en kleinere eilanden krijgen doorgaans een ander bezoekersprofiel dan de bekendste hubs. Kies niet alleen een regio: bepaal welke concrete stad of eilandbasis bij je route, mobiliteit en voorzieningen past.' },
  { question: 'Wat zijn minder toeristische plekken in Thailand?', answer: 'Voorbeelden met verschillende reisprofielen zijn Koh Mak, Mae Hong Son, Bueng Kan, Nakhon Phanom, Chanthaburi en Trang. “Minder toeristisch” betekent niet leeg; weekenddrukte, evenementen en seizoenen kunnen de ervaring sterk veranderen.' },
  { question: 'Welke eilanden in Thailand zijn minder toeristisch?', answer: 'Koh Mak heeft een kleinschaliger profiel dan veel bekende eilanden. Ook binnen de Trang- en Tratregio bestaan rustigere keuzes. Beoordeel eerst de actuele bootketen, zeeconditie, verblijfkeuze en mobiliteit; een onbekender eiland is niet automatisch eenvoudiger.' },
  { question: 'Kan ik buiten de gebaande paden reizen zonder scooter?', answer: 'Ja, als je de basis en lokale transfers daarop kiest. Een rivierstad als Nakhon Phanom kan praktischer zijn dan een verspreid eiland of bergregio. Boek geen scooter als noodoplossing: lees de aparte vervoer- en scooterowner voordat je beslist.' },
  { question: 'Is een rustige plek veilig voor een soloreis?', answer: 'Rust geeft geen veiligheidsgarantie. Controleer het actuele reisadvies, vervoer na aankomst, bereikbaarheid van hulp, mobiel bereik en je terugvalplan. Deel je route en kies een aankomsttijd waarop je verblijf en transfer bevestigd zijn.' },
  { question: 'Hoeveel dagen heb je nodig voor een minder bekende plek?', answer: 'Reken niet alleen de verblijfsnachten, maar ook de aan- en afreis plus een eventuele weer- of vervoersbuffer. Een afgelegen stop voor één gehaaste nacht levert vaak meer logistiek dan rust op. Voeg liever één passende basis toe dan meerdere korte omwegen.' },
  { question: 'Hoe voeg ik een rustige plek toe aan een Thailandreis van twee weken?', answer: 'Kies één plek die logisch aansluit op je bestaande noordelijke, oostelijke, Isaan- of zuidelijke route. Houd de hoofdaansluiting intact, verblijf lang genoeg om de transfer te rechtvaardigen en bewaar een alternatief in dezelfde regio.' },
  { question: 'Hoe controleer ik boten, wegen en parkopeningen?', answer: 'Gebruik vlak voor vertrek de actuele operator, vervoerder of parkmelding en leg de terugreis apart vast. Controleer daarnaast de weersverwachting. Een accommodatiebevestiging bewijst niet dat een boot, trail of parkzone open is.' },
  { question: 'Is “authentiek Thailand” een bruikbaar reislabel?', answer: 'Niet als ranglijst of belofte. Iedere bestemming is een echte leefomgeving, ook wanneer er bezoekers komen. Zoek liever naar een passend ritme, lokale ondernemingen, respectvolle omgang en een route die geen bewoners of kwetsbare plekken als toeristisch decor behandelt.' },
];

const sources = [
  { title: 'Trat en Koh Mak', creator: 'Tourism Authority of Thailand', url: 'https://www.tourismthailand.org/Destinations/Provinces/Trat/466', note: 'Officiële regionale context en waarschuwing dat zuidwestmoesson soms het zeevervoer beperkt.' },
  { title: 'Mae Hong Son', creator: 'Tourism Authority of Thailand', url: 'https://www.tourismthailand.org/Destinations/Provinces/Mae-Hong-Son/106', note: 'Officiële bestemmingscontext; onderstreept bergwegen, lange reis en drukte rond vakanties.' },
  { title: 'Bueng Kan', creator: 'Tourism Authority of Thailand', url: 'https://www.tourismthailand.org/Destinations/Provinces/Bueng%20Kan/590', note: 'Primaire context voor Mekong, bergen, watervallen en natuurgebieden.' },
  { title: 'Nakhon Phanom', creator: 'Tourism Authority of Thailand', url: 'https://www.tourismthailand.org/Destinations/Provinces/Nakhon-Phanom/579', note: 'Primaire context voor de Mekongstad, geschiedenis en regionale cultuur.' },
  { title: 'Chanthaburi', creator: 'Tourism Authority of Thailand', url: 'https://www.tourismthailand.org/Destinations/Provinces/Chanthaburi/463', note: 'Primaire context voor stad, erfgoed, markten en natuur.' },
  { title: 'Actuele Thailandverwachting', creator: 'Thailand Meteorological Department', url: 'https://www.tmd.go.th/en/forecast/daily', note: 'Officiële bron voor actuele weersverwachting; geen seizoensgemiddelde als daggarantie.' },
  { title: 'Reisadvies Thailand', creator: 'NederlandWereldwijd', url: 'https://www.nederlandwereldwijd.nl/reisadvies/thailand', note: 'Actuele Nederlandse veiligheidscontext, inclusief grensgebieden en afgelegen locaties.' },
];

function schemas() {
  return [
    { '@context': 'https://schema.org', '@type': 'Article', headline: 'Rustige plekken en verborgen parels in Thailand', description: 'Kies een minder toeristische plek in Thailand op bereikbaarheid, voorzieningen, actuele omstandigheden en een betrouwbare terugweg.', url: PAGE_URL, image: `https://go2-thailand.com${HERO}`, inLanguage: 'nl-NL', dateModified: '2026-07-31', author: { '@type': 'Organization', name: 'GO2 Thailand' }, publisher: { '@type': 'Organization', name: 'GO2 Thailand' } },
    { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Thailand', item: 'https://go2-thailand.com/nl/' }, { '@type': 'ListItem', position: 2, name: 'Reisgidsen', item: 'https://go2-thailand.com/nl/travel-guides/' }, { '@type': 'ListItem', position: 3, name: 'Rustige plekken', item: PAGE_URL }] },
    { '@context': 'https://schema.org', '@type': 'ItemList', name: 'Zes rustige Thailandprofielen', numberOfItems: destinations.length, itemListElement: destinations.map((item, index) => ({ '@type': 'ListItem', position: index + 1, name: item.title, url: `https://go2-thailand.com/nl${item.href}` })) },
    { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(item => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) },
  ];
}

export default function ThailandHiddenGemsGuideNl() {
  return (
    <div className="overflow-hidden bg-canvas text-charcoal" data-premium-template="hidden-gems-thailand-nl">
      <SEOHead title="Rustige plekken Thailand: 6 alternatieven buiten de massa" description="Vind minder toeristische plekken in Thailand en kies op bereikbaarheid, voorzieningen, actuele omstandigheden en een betrouwbare terugweg." ogImage={`https://go2-thailand.com${HERO}`}>
        {schemas().map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}
      </SEOHead>

      <EditorialHero image={HERO} imageAlt="Reiziger arriveert bij een rustig bewoond Thais rivierstadje in het ochtendlicht" breadcrumbs={[{ label: 'Thailand', href: '/' }, { label: 'Reisgidsen', href: '/travel-guides/' }, { label: 'Rustige plekken' }]} eyebrow="Rust is relatief · je terugweg niet" title={<>Minder bekend.<br /><span className="text-saffron-light">Beter voorbereid.</span></>} subtitle="Kies niet de geheimste plek. Kies de plek die bij je route past." description="Vergelijk zes rustige reisprofielen op bereikbaarheid, voorzieningen en flexibiliteit. Controleer daarna de echte dag: boot, weg, weer, park en terugverbinding." actions={[{ label: 'Vergelijk de zes plekken', href: '#plekken', kind: 'primary' }, { label: 'Doe de vier checks', href: '#checks', kind: 'secondary' }]} contentTone="light" gradientClassName="bg-[linear-gradient(90deg,rgba(3,27,22,.98)_0%,rgba(3,27,22,.91)_39%,rgba(3,27,22,.30)_68%,rgba(3,27,22,.04)_100%)]" imageClassName="object-cover object-[67%_center]" titleClassName="max-w-[780px] text-[4rem] leading-[.84] !text-white sm:text-[5rem] lg:text-[5.8rem]" subtitleClassName="max-w-[650px] text-[1.35rem] leading-[1.12] !text-white sm:text-[1.6rem]" descriptionClassName="mt-4 max-w-[620px] text-sm leading-7 !text-white/75" />
      <PageSectionNav items={[{ href: '#plekken', label: '6 reisprofielen', icon: MapPin }, { href: '#checks', label: '4 checks', icon: ShieldCheck }, { href: '#route', label: 'Route bouwen', icon: Route }, { href: '#vragen', label: 'Vragen', icon: Sparkles }]} />

      <section className="section-divider-bottom bg-jade py-5 text-white"><div className="container-custom grid gap-3 sm:grid-cols-3">{[
        { key: 'Rust', value: 'Nooit gegarandeerd', icon: Sparkles }, { key: 'Route', value: 'Heen én terug', icon: Route }, { key: 'Laatste check', value: 'Op de reisdag', icon: CalendarCheck },
      ].map(({ key, value, icon: Icon }) => <div key={key} className="flex min-h-20 items-center gap-4 rounded-xl border border-white/12 bg-white/7 px-5 py-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-saffron text-jade"><Icon size={20} aria-hidden="true" /></span><span><span className="block text-[9px] font-extrabold uppercase tracking-[.15em] text-white/55">{key}</span><strong className="font-display text-xl">{value}</strong></span></div>)}</div></section>

      <section id="plekken" className="section-divider-bottom scroll-mt-24 py-14 lg:py-20"><div className="container-custom"><SectionHeading eyebrow="Geen top 10, wel zes routeprofielen" title={<>Rustiger reizen.<br />Zes verschillende afwegingen.</>} description="Deze plekken zijn niet leeg of geheim. Ze hebben een ander tempo en vragen ieder om een andere toegangsketen. Open de destination-owner voor volledige lokale planning." />
        <div className="mt-9 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{destinations.map(({ title, region, href, icon: Icon, fit, tradeoff, verify }, index) => <article key={title} className="flex min-h-[390px] flex-col rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl border border-saffron/25 bg-saffron/8 text-jade"><Icon size={21} aria-hidden="true" /></span><span className="font-display text-4xl text-jade/12">0{index + 1}</span></div><p className="mt-7 text-[9px] font-extrabold uppercase tracking-[.15em] text-saffron-dark">{region}</p><h3 className="mt-2 font-display text-[1.8rem] font-semibold leading-none text-jade">{title}</h3><p className="mt-4 text-xs font-medium leading-6 text-charcoal/68"><strong className="text-jade">Past bij:</strong> {fit}</p><p className="mt-3 text-xs font-medium leading-6 text-charcoal/68"><strong className="text-jade">Trade-off:</strong> {tradeoff}</p><p className="mt-4 border-t border-jade/10 pt-4 text-[10px] font-semibold leading-5 text-charcoal/52">Live check: {verify}</p><Link href={href} className="mt-auto inline-flex min-h-11 items-center gap-2 pt-5 text-xs font-extrabold text-jade">Open {title} <ArrowRight size={15} className="text-saffron-dark" aria-hidden="true" /></Link></article>)}</div>
      </div></section>

      <section id="checks" className="section-divider-bottom scroll-mt-24 bg-tonal py-14 lg:py-20"><div className="container-custom grid gap-10 lg:grid-cols-[.66fr_1.34fr]"><div className="lg:sticky lg:top-28"><SectionHeading eyebrow="“Minder bekend” is geen kwaliteitslabel" title="Vier poorten vóór je boekt" description="Een plek gaat pas je route in wanneer toegang, basis, dagconditie en uitweg kloppen." /><div className="mt-7 rounded-2xl border border-saffron/25 bg-white p-5"><p className="text-[9px] font-extrabold uppercase tracking-[.15em] text-saffron-dark">Stopregel</p><p className="mt-3 text-xs font-medium leading-6 text-charcoal/68">Kun je de terugreis, essentiële voorziening of actuele toegang niet bevestigen? Kies een beter verbonden basis of bewaar deze plek voor een volgende reis.</p></div></div><ol className="grid gap-4 sm:grid-cols-2">{gates.map(({ step, title, question, copy, icon: Icon }) => <li key={step} className="min-h-[270px] rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-full bg-jade text-saffron"><Icon size={20} aria-hidden="true" /></span><span className="text-[10px] font-extrabold tracking-[.15em] text-saffron-dark">CHECK {step}</span></div><h3 className="mt-7 font-display text-[1.7rem] font-semibold leading-none text-jade">{title}</h3><p className="mt-2 text-xs font-extrabold text-charcoal/75">{question}</p><p className="mt-3 text-xs font-medium leading-6 text-charcoal/64">{copy}</p></li>)}</ol></div></section>

      <section id="route" className="section-divider-bottom scroll-mt-24 py-14 lg:py-20"><div className="container-custom"><SectionHeading eyebrow="Eén rustige stop is vaak genoeg" title="Bouw regionaal. Niet willekeurig." description="Koppel een alternatief aan je bestaande route in plaats van heel Thailand door te steken voor een label uit een lijstje." /><div className="mt-9 grid gap-4 lg:grid-cols-3">{[
        { title: 'Oostelijke lus', places: 'Bangkok → Chanthaburi → Trat of Koh Mak', copy: 'Kies stad óf eiland als hoofdaccent. Laat een bevestigde boot en terugtransfer leidend zijn.' },
        { title: 'Mekonglus', places: 'Nakhon Phanom → Bueng Kan', copy: 'Past alleen wanneer lange landtransfers, natuurdagen en je volgende aansluiting genoeg ruimte krijgen.' },
        { title: 'Zuidelijke lus', places: 'Trang-stad → één eilandbasis', copy: 'Bouw eerst de pier- en terugvaartketen. Houd Trang als landplan wanneer zee of parkstatus verandert.' },
      ].map(({ title, places, copy }, index) => <article key={title} className={`rounded-2xl p-7 ${index === 1 ? 'bg-jade text-white' : 'border border-jade/10 bg-white shadow-editorial-card'}`}><span className={`text-[9px] font-extrabold uppercase tracking-[.15em] ${index === 1 ? 'text-saffron-light' : 'text-saffron-dark'}`}>Route 0{index + 1}</span><h3 className={`mt-4 font-display text-3xl font-semibold ${index === 1 ? 'text-white' : 'text-jade'}`}>{title}</h3><p className={`mt-3 text-xs font-extrabold ${index === 1 ? 'text-white/85' : 'text-charcoal/75'}`}>{places}</p><p className={`mt-4 text-xs font-medium leading-6 ${index === 1 ? 'text-white/65' : 'text-charcoal/65'}`}>{copy}</p></article>)}</div><div className="mt-5 flex flex-col gap-4 rounded-2xl border border-saffron/25 bg-saffron/8 p-6 sm:flex-row sm:items-center"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-jade text-saffron"><Bus size={22} aria-hidden="true" /></span><p className="text-xs font-medium leading-6 text-charcoal/70"><strong className="text-jade">Controleer actuele tijden bij de vervoerder.</strong> Deze owner publiceert bewust geen vaste prijzen, vaartijden of vertrekschema's. Gebruik de <Link href="/transport/" className="font-extrabold text-jade underline decoration-saffron underline-offset-4">vervoerowner</Link> voor de modaliteitskeuze.</p></div></div></section>

      <section className="section-divider-bottom bg-jade py-14 text-white lg:py-20"><div className="container-custom grid gap-9 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="eyebrow !text-saffron-light">Een leefomgeving, geen decor</p><h2 className="font-display text-[3.3rem] font-semibold leading-[.88] tracking-[-.04em]">Laat de plek rustig achter</h2><p className="mt-5 max-w-xl text-sm font-medium leading-7 text-white/70">Deel geen privé- of kwetsbare locatie om een “secret spot” te bewijzen. Gebruik officiële routes en lokale ondernemingen, vraag vóór fotograferen en accepteer een sluiting zonder sluiproute.</p></div><ul className="grid gap-3 sm:grid-cols-2">{['Geen geotag voor kwetsbare of private plekken','Geen bewoner als achtergrond zonder toestemming','Geen gesloten trail of onofficiële toegang','Wel afval meenemen, geluid beperken en lokaal besteden'].map(item => <li key={item} className="flex min-h-20 items-center gap-3 rounded-xl border border-white/12 bg-white/7 p-4 text-xs font-semibold leading-5 text-white/75"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-saffron text-jade"><Check size={14} strokeWidth={3} aria-hidden="true" /></span>{item}</li>)}</ul></div></section>

      <div id="vragen"><FaqSplitSection eyebrow="Echte zoekvragen" title="Veelgestelde vragen over rustige plekken" description="Antwoorden zonder leegte, authenticiteit, veiligheid of bereikbaarheid te garanderen." items={faqs} /></div>
      <RelatedGuidesSection eyebrow="Maak de route uitvoerbaar" title="Verdiep de beslissingen achter je stop" readLabel="Open de gids" guides={[{ title: 'Vervoer in Thailand', description: 'Vergelijk trein, bus, vlucht, boot en lokale transfer als één keten.', href: '/transport/', image: '/images/redesign/transport-thailand-hero.webp', imageAlt: 'Vervoer en routeplanning in Thailand' }, { title: 'Weer & reistijd', description: 'Gebruik regio en reisprofiel; een maandgemiddelde is geen daggarantie.', href: '/weather/', image: '/images/redesign/best-time-thailand-hero-v2.webp', imageAlt: 'Weersomstandigheden tijdens een Thailandreis' }, { title: 'Thaise zinnen', description: 'Bewaar adres, Thai-schrift en een rustige terugvalroutine voor onderweg.', href: '/travel-guides/thai-phrases-language/', image: '/images/redesign/thai-phrases-language-hero-v2.webp', imageAlt: 'Reiziger gebruikt Thaise taalhulp' }]} />
      <SourceMethodSection eyebrow="Bronnen & methode" title="Rust is een momentopname" description="Bijgewerkt op 31 juli 2026 met zichtbare Nederlandse Google-resultaten, echte PAA-vragen, concurrentpatronen en primaire bronnen. De legacycopy met verzonnen bezoekerspercentages, vaste prijzen en tijden, stereotypes en absolute leegteclaims is volledig vervangen. Deze landelijke owner selecteert; lokale owners bezitten de details." sources={sources} />
    </div>
  );
}
