import Image from "next/image";
import Link from "next/link";
import {
  Anchor,
  ArrowRight,
  BadgeCheck,
  Check,
  CloudRain,
  ExternalLink,
  Fish,
  HeartPulse,
  LifeBuoy,
  MapPinned,
  ShieldCheck,
  Sparkles,
  UsersRound,
  Waves,
  Wind,
} from "lucide-react";
import SEOHead from "../SEOHead";
import { AffiliateDisclosure } from "../design/AffiliateDisclosure";
import { EditorialHero } from "../design/EditorialHero";
import { FaqSplitSection } from "../design/FaqSplitSection";
import { PageSectionNav } from "../design/PageSectionNav";
import { RelatedGuidesSection } from "../design/RelatedGuidesSection";
import { SectionHeading } from "../design/SectionHeading";
import { SourceMethodSection } from "../design/SourceMethodSection";
import { KLOOK_GENERIC, withPlacementSubId } from "../../lib/affiliates";
import { useSubId } from "../../lib/useSubId";

const activityProfiles = [
  { title: "Beschut snorkelen", tag: "Vanaf kant of ondiepe zone", copy: "Past alleen wanneer instap, uitstap, bodem, golfslag, stroming en toezicht duidelijk zijn. Zwemvaardigheid blijft één laag, geen totaalgarantie.", verify: "Lokale vlaggen, instap, buddy, terugweg en bootvrije zone", icon: Waves },
  { title: "Snorkelboottour", tag: "Bootketen eerst", copy: "Controleer vaargebied, stops, groepsgrootte, briefing, zwemhulp, in- en uitstap en hoe de operator bij veranderend weer beslist.", verify: "Boot, kapitein, gids, veiligheidsmiddelen, parktoegang en alternatief", icon: Anchor },
  { title: "Introductieduik", tag: "Begeleid, geen brevet", copy: "Een introductie-ervaring is geen volwaardige certificering. Vraag naar medische vragenlijst, instructeur, maximale voorwaarden en supervisie.", verify: "Opleidingsorganisatie, instructeur, briefing, ratio en vervolgstatus", icon: UsersRound },
  { title: "Gecertificeerde duik", tag: "Brevet én actuele fit", copy: "Een brevet zegt niet automatisch dat recente ervaring, gezondheid en de geplande omstandigheden passen. Bespreek refresher en grenzen eerlijk.", verify: "Brevet, logboek, recente activiteit, materiaal, buddy en noodplan", icon: BadgeCheck },
];

const goChecks = [
  { step: "01", title: "Past de activiteit bij jou?", copy: "Scheid snorkelen, introductieduik, opleiding en gecertificeerde fundive. Elk heeft andere vaardigheids-, medische en supervisiegrenzen.", icon: HeartPulse },
  { step: "02", title: "Is de zone echt open?", copy: "Controleer marien park, eiland, baai en concrete activiteit. Een geboekte boot of oude blog bewijst geen actuele toegang.", icon: MapPinned },
  { step: "03", title: "Wat doet de zee vandaag?", copy: "Vraag naar wind, golven, stroming, zicht, onweer en getij. Een zonnige ochtendfoto zegt niets over de volgende stop.", icon: Wind },
  { step: "04", title: "Kan de operator uitleggen?", copy: "Laat route, briefing, groepsgrootte, kwalificatie, materiaal, bootveiligheid, noodplan, inclusies en annulering concreet maken.", icon: ShieldCheck },
  { step: "05", title: "Is er een geloofwaardig plan B?", copy: "Een beschutte baai, andere activiteit of annulering is beter dan druk om toch te varen, te duiken of een gesloten zone te betreden.", icon: CloudRain },
];

const faqs = [
  { question: "Waar kun je het beste snorkelen in Thailand?", answer: "Koh Tao, de Surin- en Similanregio, delen rond Koh Lanta en verschillende Golf- en Andamanzones komen vaak terug. De beste keuze hangt echter af van je route, zwemvaardigheid, actuele parktoegang, wind, golven, stroming en operator. Kies daarom geen eiland uitsluitend op een top-10." },
  { question: "Welke kant van Thailand is beter voor duiken of snorkelen?", answer: "Golf en Andaman hebben andere weer- en zeepatronen, maar een vaste jaarkalender is geen daggarantie. Kies eerst een regio die bij je reisroute past en controleer daarna parkstatus, lokale voorspelling, zeeconditie en operatorbericht vlak voor vertrek." },
  { question: "Kun je in Thailand duiken zonder duikbrevet?", answer: "Een erkende operator kan een begeleide introductie-ervaring aanbieden die geen volledige certificering is. Voor zelfstandigere gecertificeerde duikactiviteiten gelden brevet-, ervarings- en gezondheidsvoorwaarden. Laat de operator precies uitleggen welk programma, welke supervisie en welke grenzen gelden." },
  { question: "Wat moet je controleren bij een duik- of snorkeltour?", answer: "Controleer operator en gids/instructeur, route, zeeconditie, boot, groepsgrootte, briefing, materiaal, zwemhulp, noodplan, parktoegang, vervoer, eten, verzekering, brevetvereiste en annulering. Vraag ook wat er gebeurt als de geplande zone niet verantwoord is." },
  { question: "Wanneer kun je het beste duiken in Thailand?", answer: "Dat verschilt per kust, eiland, duiklocatie en jaar. Parksluiting, wind, golven, stroming en zicht kunnen belangrijker zijn dan een gemiddelde maand. Gebruik regionale seizoenscontext voor je route, maar laat de actuele lokale go/no-go-beslissing leidend zijn." },
];

export default function ThailandDivingSnorkelingGuideNl() {
  const subId = useSubId();
  const klookHref = withPlacementSubId(KLOOK_GENERIC, subId, "diving-snorkeling-thailand-nl-water-day");
  const pageUrl = "https://go2-thailand.com/nl/travel-guides/diving-snorkeling-thailand/";
  const schemas = [
    { "@context":"https://schema.org", "@type":"Article", headline:"Duiken en snorkelen in Thailand: kies waterdag en operator", description:"Kies snorkelen, introductieduik of gecertificeerde duik en controleer vaardigheid, gezondheid, zee, parkstatus en operator.", image:"https://go2-thailand.com/images/redesign/thailand-diving-snorkeling-hero-v2.webp", url:pageUrl, inLanguage:"nl-NL", author:{"@type":"Organization",name:"GO2 Thailand"}, publisher:{"@type":"Organization",name:"GO2 Thailand"}, dateModified:"2026-07-31" },
    { "@context":"https://schema.org", "@type":"FAQPage", mainEntity:faqs.map(({question,answer})=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}})) },
    { "@context":"https://schema.org", "@type":"BreadcrumbList", itemListElement:[{"@type":"ListItem",position:1,name:"Thailand",item:"https://go2-thailand.com/nl/"},{"@type":"ListItem",position:2,name:"Reisgidsen",item:"https://go2-thailand.com/nl/travel-guides/"},{"@type":"ListItem",position:3,name:"Duiken en snorkelen",item:pageUrl}] },
  ];

  return <>
    <SEOHead title="Duiken en snorkelen Thailand: plekken en veilige checks" description="Kies snorkelen of duiken in Thailand op ervaring, regio en actuele zeecondities. Controleer parkstatus, brevet, operator, boot en voorwaarden." ogImage="https://go2-thailand.com/images/redesign/thailand-diving-snorkeling-hero-v2.webp">{schemas.map((schema,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} />)}</SEOHead>
    <div data-premium-template="diving-snorkeling-thailand-nl" className="overflow-hidden bg-canvas text-charcoal">
      <EditorialHero image="/images/redesign/thailand-diving-snorkeling-hero-v2.webp" imageAlt="Thaise watergids geeft twee reizigers een briefing op een boot in een kalme baai" breadcrumbs={[{label:"Thailand",href:"/"},{label:"Reisgidsen",href:"/travel-guides/"},{label:"Duiken & snorkelen"}]} eyebrow="Briefing vóór blauw water" title={<>Kijk onder water.<br/><span className="text-saffron-light">Beslis erboven.</span></>} subtitle="De beste waterdag begint met een geloofwaardige no-go." description="Kies eerst snorkelen, introductieduik of gecertificeerd duiken. Controleer daarna gezondheid, ervaring, parkstatus, zeeconditie, operator en alternatief—zonder sighting guarantee." actions={[{label:"Kies je waterdag",href:"#activiteiten",kind:"primary"},{label:"Open de go/no-go-check",href:"#checks",kind:"secondary"}]} contentTone="light" gradientClassName="bg-[linear-gradient(90deg,rgba(3,29,29,0.97)_0%,rgba(3,29,29,0.9)_43%,rgba(3,29,29,0.2)_69%,rgba(3,29,29,0.02)_100%)]" imageClassName="object-cover object-[62%_center]" titleClassName="max-w-[790px] text-[4rem] leading-[0.84] !text-white sm:text-[5rem] lg:text-[5.65rem]" subtitleClassName="max-w-[630px] text-[1.35rem] leading-[1.12] !text-white sm:text-[1.6rem]" descriptionClassName="mt-4 max-w-[620px] text-sm leading-7 !text-white/75" />
      <PageSectionNav items={[{href:"#activiteiten",label:"Waterdag kiezen",icon:Waves},{href:"#checks",label:"Go/no-go",icon:ShieldCheck},{href:"#operator",label:"Operator",icon:BadgeCheck},{href:"#vragen",label:"Vragen",icon:Sparkles}]} />

      <section className="section-divider-bottom bg-jade py-5 text-white"><div className="container-custom grid gap-3 sm:grid-cols-3">{[{k:"Vaardigheid",v:"Activiteit past echt",I:HeartPulse},{k:"Vandaag",v:"Zone en zee zijn akkoord",I:Wind},{k:"Operator",v:"Kan ook nee zeggen",I:ShieldCheck}].map(({k,v,I})=><div key={k} className="flex min-h-20 items-center gap-4 rounded-xl border border-white/12 bg-white/7 px-5 py-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-saffron text-jade"><I size={20}/></span><span><span className="block text-[9px] font-extrabold uppercase tracking-[.15em] text-white/55">{k}</span><strong className="font-display text-xl">{v}</strong></span></div>)}</div></section>

      <section id="activiteiten" className="section-divider-bottom scroll-mt-24 py-14 lg:py-20"><div className="container-custom"><SectionHeading eyebrow="Snorkelen is geen lichte versie van duiken" title={<>Vier waterdagen.<br/>Vier andere grenzen.</>} description="Kies op echte ervaring, gezondheid, supervisie en omgeving. De bestemming volgt pas daarna."/><div className="mt-9 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{activityProfiles.map(({title,tag,copy,verify,icon:Icon},index)=><article key={title} className="flex min-h-[375px] flex-col rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl border border-saffron/25 bg-saffron/8 text-jade"><Icon size={21}/></span><span className="font-display text-4xl text-jade/12">0{index+1}</span></div><p className="mt-7 text-[9px] font-extrabold uppercase tracking-[.15em] text-saffron-dark">{tag}</p><h3 className="mt-2 font-display text-[1.7rem] font-semibold leading-none text-jade">{title}</h3><p className="mt-4 text-xs font-medium leading-6 text-charcoal/68">{copy}</p><p className="mt-auto border-t border-jade/10 pt-4 text-[10px] font-semibold leading-5 text-charcoal/50">Verifieer: {verify}</p></article>)}</div></div></section>

      <section id="checks" className="section-divider-bottom scroll-mt-24 bg-tonal py-14 lg:py-20"><div className="container-custom grid gap-10 lg:grid-cols-[.66fr_1.34fr]"><div className="lg:sticky lg:top-28"><SectionHeading eyebrow="Geen kalender vervangt de zee" title="Vijf lagen voor groen licht" description="Golf en Andaman geven routecontext, maar de echte beslissing hoort bij de specifieke zone en dag."/><div className="mt-7 rounded-2xl border border-saffron/25 bg-white p-5"><p className="text-[9px] font-extrabold uppercase tracking-[.15em] text-saffron-dark">Medische grens</p><p className="mt-3 text-xs font-medium leading-6 text-charcoal/68">Een pagina of operator kan jouw geschiktheid om te duiken niet vaststellen. Beantwoord een medische vragenlijst eerlijk en bespreek relevante twijfel met een arts met kennis van duikgeneeskunde.</p></div></div><ol className="grid gap-4 sm:grid-cols-2">{goChecks.map(({step,title,copy,icon:Icon},index)=><li key={step} className={`min-h-[245px] rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card ${index===4?'sm:col-span-2':''}`}><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-full bg-jade text-saffron"><Icon size={20}/></span><span className="text-[10px] font-extrabold tracking-[.15em] text-saffron-dark">LAAG {step}</span></div><h3 className="mt-7 font-display text-[1.7rem] font-semibold leading-none text-jade">{title}</h3><p className="mt-4 max-w-2xl text-xs font-medium leading-6 text-charcoal/67">{copy}</p></li>)}</ol></div></section>

      <section id="operator" className="section-divider-bottom scroll-mt-24 py-14 lg:py-20"><div className="container-custom"><div className="grid overflow-hidden rounded-[1.7rem] bg-jade text-white shadow-editorial-card lg:grid-cols-[1.03fr_.97fr]"><div className="relative min-h-[430px]"><Image src="/images/redesign/koh-tao-dive-briefing.webp" alt="Duikbriefing met materiaalcontrole voor vertrek" fill sizes="(max-width:1024px) 100vw, 52vw" className="object-cover"/></div><div className="p-7 lg:p-10"><p className="eyebrow !text-saffron-light">Kijk verder dan het logo</p><h2 className="font-display text-[3.15rem] font-semibold leading-[.89] tracking-[-.04em]">Een operator moet uitleggen én afblazen</h2><ul className="mt-7 space-y-3">{["Wie begeleidt welke groep en onder welke opleidings- of brevetvoorwaarden?","Welke route, diepte of snorkelzone is gepland en wat verandert bij slecht weer?","Welke boot-, materiaal-, zuurstof-, communicatie- en noodprocedures zijn relevant?","Wat omvat de prijs precies en wat gebeurt bij sluiting, medische twijfel of no-go?"].map(item=><li key={item} className="flex gap-3 text-xs font-medium leading-5 text-white/72"><span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-saffron text-jade"><Check size={12} strokeWidth={3}/></span>{item}</li>)}</ul><a href={klookHref} target="_blank" rel="noopener noreferrer nofollow sponsored" className="btn-cream mt-7 min-h-12 px-6 text-saffron-dark">Bekijk actuele wateractiviteiten <ExternalLink size={15}/></a><AffiliateDisclosure className="mt-4 !text-white/52">Klook-affiliatelink: we kunnen commissie ontvangen zonder extra kosten voor jou. Controleer actuele operator, programma, prijs, voorwaarden, parktoegang en brevetvereisten zelf.</AffiliateDisclosure></div></div></div></section>

      <section className="section-divider-bottom bg-tonal py-14 lg:py-20"><div className="container-custom grid gap-9 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow">OneLink · twee waterdagtaken</p><h2 className="font-display text-[3.1rem] font-semibold leading-[.9] text-jade">Droog opbergen.<br/>Droog worden.</h2><p className="mt-5 text-sm font-medium leading-7 text-charcoal/65">Geen snorkelset, reddingsmiddel of medisch product: pasvorm en veiligheid horen bij de activiteit en operator.</p></div><div className="grid gap-4 sm:grid-cols-2">{[{title:"Dry bag voor droge spullen",copy:"Kan droge kleding of documenten van spatwater scheiden. Controleer maat, sluiting en actuele productspecificaties; geen waterdichtheidsgarantie voor elektronica.",slug:"earth-pak-dry-bag",I:Waves},{title:"Compacte reishanddoek",copy:"Een praktische droog- en omkleedtaak na boot of strand. Controleer formaat, materiaal, onderhoud en actuele verkoper.",slug:"rainleaf-travel-towel",I:LifeBuoy}].map(({title,copy,slug,I})=><article key={slug} className="flex min-h-[270px] flex-col rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card"><I className="text-jade"/><h3 className="mt-6 font-display text-[1.6rem] font-semibold text-jade">{title}</h3><p className="mt-4 flex-1 text-xs font-medium leading-6 text-charcoal/62">{copy}</p><a href={`/go/${slug}/`} target="_blank" rel="noopener noreferrer nofollow sponsored" className="mt-6 inline-flex items-center gap-2 text-[10px] font-extrabold text-saffron-dark">Bekijk actuele prijs bij Amazon <ExternalLink size={12}/></a></article>)}</div><AffiliateDisclosure className="lg:col-start-2">Als Amazon-partner verdienen wij aan in aanmerking komende aankopen, zonder extra kosten voor jou. OneLink kan naar een lokale Amazon-winkel sturen; product, verkoper, prijs, levering en beschikbaarheid verschillen.</AffiliateDisclosure></div></section>

      <section className="section-divider-bottom py-14 lg:py-20"><div className="container-custom grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="eyebrow">Kijken zonder claimen</p><h2 className="font-display text-[3.25rem] font-semibold leading-[.9] text-jade">Niets aanraken.<br/>Niets najagen.</h2><p className="mt-5 text-sm font-medium leading-7 text-charcoal/66">Raak koraal en zeeleven niet aan, voer niets, sta niet op rif en blokkeer geen dier voor beeld. Een haai, schildpad of ander dier is nooit inbegrepen.</p><Link href="/travel-guides/dangerous-animals-thailand/" className="mt-6 inline-flex items-center gap-2 text-xs font-extrabold text-jade">Open de dierenrisico-owner <ArrowRight size={14} className="text-saffron"/></Link></div><div className="relative min-h-[390px] overflow-hidden rounded-[1.7rem]"><Image src="/images/redesign/koh-tao-responsible-snorkeling.webp" alt="Snorkelaar blijft op afstand boven een rif zonder het aan te raken" fill sizes="(max-width:1024px) 100vw, 56vw" className="object-cover"/></div></div></section>

      <div id="vragen"><FaqSplitSection eyebrow="Echte zoekvragen" title="Veelgestelde vragen over duiken en snorkelen" description="Antwoorden zonder vaste helderwaterbelofte, wildlifegarantie of universele beste maand." items={faqs}/></div>
      <RelatedGuidesSection title="Plan de kust en zee samen" guides={[{title:"Koh Tao",description:"Verdiep de plaatsgebonden duik-, snorkel-, baai- en transferkeuzes.",href:"/islands/koh-tao/",image:"/images/redesign/koh-tao-diving-hero.webp"},{title:"Nationale parken",description:"Controleer mariene parkstatus, zone en seizoenssluiting vóór je boekt.",href:"/travel-guides/national-parks-thailand/",image:"/images/redesign/thailand-national-parks-hero-v2.webp"},{title:"Dierenrisico's",description:"Houd afstand en volg na contact de professionele handelingsroute.",href:"/travel-guides/dangerous-animals-thailand/",image:"/images/redesign/thailand-animal-risk-hero-v2.webp"}]}/>
      <SourceMethodSection title="Een waterdag blijft een momentopname" description="Nederlandse SERP en PAA zijn op 31 juli 2026 zichtbaar gecontroleerd. WHO onderbouwt waterveiligheidslagen, DAN de medische fit-to-dive-grens en DNP veranderlijke mariene parkstatus. Persoonlijke medische beoordeling en operatorbesluiten blijven buiten deze pagina." sources={[{title:"Drowning fact sheet",creator:"World Health Organization",url:"https://www.who.int/news-room/fact-sheets/detail/drowning",note:"Primaire context over zwemvaardigheid, waterveiligheid, toezicht en veilig watertransport."},{title:"Health status and return to diving",creator:"Divers Alert Network",url:"https://dan.org/safety-prevention/return-to-diving-safely/health-status/",note:"Duikmedische context na ziekte, inactiviteit of gezondheidsverandering."},{title:"Diving without certification",creator:"PADI",url:"https://blog.padi.com/can-you-scuba-dive-without-a-certification/",note:"Onderscheid tussen begeleide introductie-ervaring en volledige certificering."},{title:"Similan closure and reef recovery",creator:"Department of National Parks Thailand",url:"https://news.dnp.go.th/news/45690",note:"Primaire melding over seizoenssluiting en marien natuurherstel."}]}/>
    </div>
  </>;
}
