import Image from "next/image";
import Link from "next/link";
import { AlertTriangle, ArrowRight, BadgeCheck, Bike, Check, ClipboardCheck, ExternalLink, FileCheck2, Gauge, HardHat, KeyRound, MapPinned, PhoneCall, Route, SearchCheck, ShieldCheck, Sparkles, TramFront, WalletCards, X } from "lucide-react";
import SEOHead from "../SEOHead";
import { AffiliateDisclosure } from "../design/AffiliateDisclosure";
import { EditorialHero } from "../design/EditorialHero";
import { FaqSplitSection } from "../design/FaqSplitSection";
import { PageSectionNav } from "../design/PageSectionNav";
import { RelatedGuidesSection } from "../design/RelatedGuidesSection";
import { SectionHeading } from "../design/SectionHeading";
import { SourceMethodSection } from "../design/SourceMethodSection";
import { KLOOK_GENERIC, withPlacementSubId } from "../../lib/affiliates";
import { useSubId } from "../../lib/useSubId";

const faqs = [
  {question:"Heb je een rijbewijs nodig voor een scooter in Thailand?",answer:"Ja. De meeste voertuigen die als scooter worden verhuurd zijn voor de wet motorfietsen. Volgens ANWB heb je voor een scooter vanaf 50 cc een geldig motorrijbewijs én passend internationaal rijbewijs nodig. Neem ook je originele Nederlandse rijbewijs mee; het internationale document vervangt dit niet."},
  {question:"Kan ik met alleen rijbewijs B of AM scooter rijden in Thailand?",answer:"Voor de doorgaans verhuurde scooters boven 50 cc niet. Een verhuurder kan toch een sleutel afgeven, maar dat bewijst niet dat je bevoegd rijdt of dat een verzekering zal uitkeren. Controleer voertuigcategorie, rijbewijscategorie en IRB vóór vertrek uit Nederland."},
  {question:"Welk internationaal rijbewijs heb ik nodig voor Thailand?",answer:"ANWB meldt dat modellen 1949 en 1968 worden geaccepteerd en adviseert voor Nederlandse ingezetenen het actuele afgifteadvies te volgen. Het IRB moet passen bij je motorrijbewijscategorie en samen met het originele rijbewijs worden meegenomen. Controleer dit vlak voor vertrek bij ANWB."},
  {question:"Is scooter rijden in Thailand veilig?",answer:"Het blijft een activiteit met hoog risico. WHO en NederlandWereldwijd wijzen op veel en ernstige verkeers- en motorongevallen. Geen motorervaring, links verkeer, regen, hellingen, nacht, passagier of alcohol zijn duidelijke redenen om een alternatief te kiezen."},
  {question:"Is een huurscooter automatisch verzekerd?",answer:"Nee. NederlandWereldwijd waarschuwt dat veel huurscooters niet verzekerd zijn. Vraag schriftelijk naar wettelijke aansprakelijkheid, voertuigschade en eigen risico en controleer je eigen reis-/zorgpolis op rijbewijs, cilinderinhoud, helm, alcohol, passagier en activiteit. Marketingtekst is geen polisbewijs."},
  {question:"Mag een verhuurder mijn paspoort als borg houden?",answer:"NederlandWereldwijd adviseert nooit je originele paspoort of rijbewijs af te geven. Bied een kopie of geldborg aan en kies een andere verhuurder wanneer het origineel verplicht wordt gesteld. Leg contract, borg en bestaande schade vóór vertrek vast."},
  {question:"Wat controleer ik vóór ik wegrijd?",answer:"Film alle zijden en bestaande schade en controleer remmen, banden, stuur, verlichting, richtingaanwijzers, spiegels, claxon, brandstof, kenteken/registratie, helmfit en noodnummer. Test alleen op een rustige veilige plek en vertrek niet bij twijfel."},
];

const decision = [
  {title:"Rijbevoegd",copy:"Motorrijbewijs voor de voertuigcategorie, passend IRB én origineel rijbewijs.",yes:"Alle documenten kloppen",no:"Alleen B/AM, ontbrekend IRB of twijfel",icon:FileCheck2},
  {title:"Motorervaring",copy:"Recente ervaring met vergelijkbaar gewicht, vermogen, remmen en passagier—niet alleen fietsen of autorijden.",yes:"Zelfstandig en recent",no:"Eerste rijles op vakantie",icon:Gauge},
  {title:"Routefit",copy:"Links verkeer, wegdek, hellingen, regen, donkerte, honden, zand en lokaal verkeersgedrag passen bij je niveau.",yes:"Korte bekende dagroute",no:"Nacht, storm of bergpas",icon:Route},
  {title:"Schriftelijke dekking",copy:"Verhuurder én eigen polis zijn gecontroleerd op aansprakelijkheid, schade, activiteit en voorwaarden.",yes:"Bewijs opgeslagen",no:"‘Zal wel gedekt zijn’",icon:ShieldCheck},
];

export default function ThailandScooterRentalGuideNl(){
  const subId=useSubId();
  const transferHref=withPlacementSubId(KLOOK_GENERIC,subId,"scooter-thailand-nl-transfer-alternative");
  const pageUrl="https://go2-thailand.com/nl/travel-guides/scooter-rental-thailand/";
  const schemas=[
    {"@context":"https://schema.org","@type":"Article",headline:"Scooter huren in Thailand: rijbewijs, verzekering en voertuigcheck",description:"Beslis of je bevoegd, ervaren en gedekt bent en controleer verhuurder, borg, motorfiets, helm, route en alternatief.",image:"https://go2-thailand.com/images/redesign/thailand-scooter-rental-hero-v2.webp",url:pageUrl,inLanguage:"nl-NL",author:{"@type":"Organization",name:"GO2 Thailand"},publisher:{"@type":"Organization",name:"GO2 Thailand"},dateModified:"2026-07-31"},
    {"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(({question,answer})=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))},
    {"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Thailand",item:"https://go2-thailand.com/nl/"},{"@type":"ListItem",position:2,name:"Reisgidsen",item:"https://go2-thailand.com/nl/travel-guides/"},{"@type":"ListItem",position:3,name:"Scooter huren",item:pageUrl}]},
  ];
  return <>
    <SEOHead title="Scooter huren Thailand: rijbewijs, verzekering en check" description="Scooter huren in Thailand? Check eerst motorrijbewijs, IRB, ervaring, verzekering, borg, voertuig, helm, route en veilige alternatieven." ogImage="https://go2-thailand.com/images/redesign/thailand-scooter-rental-hero-v2.webp">{schemas.map((schema,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>)}</SEOHead>
    <div data-premium-template="scooter-rental-thailand-nl" className="overflow-hidden bg-canvas text-charcoal">
      <EditorialHero image="/images/redesign/thailand-scooter-rental-hero-v2.webp" imageAlt="Reiziger en Thaise verhuurder inspecteren samen een stilstaande motorfiets en huurchecklist" breadcrumbs={[{label:"Thailand",href:"/"},{label:"Reisgidsen",href:"/travel-guides/"},{label:"Scooter huren"}]} eyebrow="De sleutel is niet de toestemming" title={<>Eerst bevoegd.<br/><span className="text-saffron-light">Dan pas rijden.</span></>} subtitle="Een Thaise huurscooter is meestal een motorfiets." description="Controleer rijbewijscategorie, internationaal rijbewijs, ervaring, polis, verhuurder en voertuig. Als één schakel niet klopt, is ander vervoer de betere route." actions={[{label:"Doe de rijcheck",href:"#beslissen",kind:"primary"},{label:"Inspecteer het voertuig",href:"#inspectie",kind:"secondary"}]} contentTone="light" gradientClassName="bg-[linear-gradient(90deg,rgba(2,24,21,.99)_0%,rgba(2,24,21,.91)_45%,rgba(2,24,21,.18)_72%,rgba(2,24,21,.02)_100%)]" imageClassName="object-cover object-center" titleClassName="max-w-[820px] text-[3.8rem] leading-[.86] !text-white sm:text-[4.9rem] lg:text-[5.8rem]" subtitleClassName="max-w-[640px] text-[1.3rem] !text-white sm:text-[1.55rem]" descriptionClassName="mt-4 max-w-[600px] text-sm leading-7 !text-white/75"/>
      <PageSectionNav items={[{href:"#beslissen",label:"Mag en kan ik?",icon:BadgeCheck},{href:"#documenten",label:"Documenten",icon:FileCheck2},{href:"#inspectie",label:"Inspectie",icon:SearchCheck},{href:"#alternatief",label:"Alternatief",icon:TramFront},{href:"#vragen",label:"Vragen",icon:Sparkles}]}/>
      <section className="section-divider-bottom bg-jade py-5 text-white"><div className="container-custom grid gap-3 sm:grid-cols-3">{[{k:"Sleutel",v:"Geen bewijs van bevoegdheid",I:KeyRound},{k:"Contract",v:"Geen polis zonder voorwaarden",I:ClipboardCheck},{k:"Helm",v:"Risicoreductie, geen vrijbrief",I:HardHat}].map(({k,v,I})=><div key={k} className="flex min-h-20 items-center gap-4 rounded-xl border border-white/12 bg-white/7 px-5 py-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-saffron text-jade"><I size={19}/></span><span><span className="block text-[9px] font-extrabold uppercase tracking-[.15em] text-white/55">{k}</span><strong className="font-display text-xl">{v}</strong></span></div>)}</div></section>
      <section id="beslissen" className="section-divider-bottom scroll-mt-24 py-14 lg:py-20"><div className="container-custom"><SectionHeading eyebrow="Vier poorten · alle vier groen" title={<>Mag je rijden?<br/>Wil je hier rijden?</>} description="‘Ik kan er één huren’ is niet dezelfde vraag. Stop zodra rijbevoegdheid, ervaring, routefit of schriftelijke dekking ontbreekt."/><div className="mt-9 grid gap-4 lg:grid-cols-2">{decision.map(({title,copy,yes,no,icon:Icon},index)=><article key={title} className="rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-jade text-saffron"><Icon size={21}/></span><span className="font-display text-4xl text-jade/12">0{index+1}</span></div><h3 className="mt-6 font-display text-[1.7rem] font-semibold text-jade">{title}</h3><p className="mt-3 text-xs font-medium leading-6 text-charcoal/65">{copy}</p><div className="mt-5 grid gap-2 sm:grid-cols-2"><p className="flex gap-2 rounded-xl bg-jade/6 p-3 text-[10px] font-bold text-jade"><Check size={15} className="shrink-0 text-saffron-dark"/>{yes}</p><p className="flex gap-2 rounded-xl bg-red-50 p-3 text-[10px] font-bold text-red-800"><X size={15} className="shrink-0"/>{no}</p></div></article>)}</div></div></section>
      <section id="documenten" className="section-divider-bottom scroll-mt-24 bg-tonal py-14 lg:py-20"><div className="container-custom grid gap-10 lg:grid-cols-[.68fr_1.32fr]"><div><SectionHeading eyebrow="Voor vertrek uit Nederland" title="Drie documenten. Eén passende categorie." description="Het IRB is een vertaling/erkenningsdocument, geen upgrade van rijbewijs B of AM naar motorcategorie A."/><div className="mt-7 rounded-2xl border border-saffron/25 bg-white p-5"><AlertTriangle className="text-saffron-dark"/><p className="mt-3 text-xs font-semibold leading-6 text-charcoal/68">ANWB meldt dat doorgaans verhuurde scooters boven 50 cc een motorrijbewijs plus IRB vragen. Controleer het actuele model- en afgifteadvies vóór vertrek.</p><a href="https://www.anwb.nl/vakantie/thailand/reisvoorbereiding/reisdocumenten" target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex items-center gap-2 text-[10px] font-extrabold text-saffron-dark">Open ANWB-informatie <ExternalLink size={12}/></a></div></div><div className="relative grid gap-4 sm:grid-cols-3 before:absolute before:left-[10%] before:right-[10%] before:top-8 before:hidden before:border-t-2 before:border-dotted before:border-saffron sm:before:block">{[
        ["01","Origineel Nederlands rijbewijs","Met de juiste motorcategorie voor het voertuig.",WalletCards],
        ["02","Passend internationaal rijbewijs","Niet los geldig en geen vervanging van je origineel.",FileCheck2],
        ["03","Polisvoorwaarden opgeslagen","Medisch, aansprakelijkheid, voertuig, cilinderinhoud en eigen risico.",ShieldCheck],
      ].map(([n,title,copy,Icon]:any)=><article key={n} className="relative rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card"><span className="relative z-10 grid h-16 w-16 place-items-center rounded-full border-4 border-tonal bg-jade text-saffron"><Icon size={23}/></span><p className="mt-5 text-[9px] font-extrabold tracking-[.15em] text-saffron-dark">CHECK {n}</p><h3 className="mt-2 font-display text-2xl font-semibold text-jade">{title}</h3><p className="mt-3 text-xs font-medium leading-6 text-charcoal/62">{copy}</p></article>)}</div></div></section>
      <section id="inspectie" className="section-divider-bottom scroll-mt-24 py-14 lg:py-20"><div className="container-custom"><div className="grid overflow-hidden rounded-[1.7rem] bg-jade text-white shadow-editorial-card lg:grid-cols-[1.05fr_.95fr]"><div className="relative min-h-[460px]"><Image src="/images/redesign/thailand-scooter-rental-hero-v2.webp" alt="Stilstaande huurmotorfiets met helm tijdens gezamenlijke voertuigcontrole" fill sizes="(max-width:1024px) 100vw, 52vw" className="object-cover object-right"/></div><div className="p-7 lg:p-10"><p className="eyebrow !text-saffron-light">Film vóór je tekent</p><h2 className="font-display text-[3.1rem] font-semibold leading-[.89]">Van borg tot remhendel</h2><ul className="mt-7 space-y-3">{["Geef nooit je originele paspoort of rijbewijs als borg; bied kopie of geldborg aan","Lees voertuig, periode, totaalprijs, borg, eigen risico, schadeprocedure en noodnummer","Film kuip, velgen, banden, zadel, onderzijde, spiegels en iedere bestaande kras","Test voor- en achterrem, bandenprofiel/-druk, stuur, verlichting, richtingaanwijzers en claxon","Pas een veilige helm met werkende sluiting; alleen ‘er is een helm’ is onvoldoende","Bewaar contract, verhuurder, voertuiggegevens, foto’s en contactkanaal offline"].map(item=><li key={item} className="flex gap-3 text-xs font-medium leading-5 text-white/72"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-saffron text-jade"><Check size={12} strokeWidth={3}/></span>{item}</li>)}</ul></div></div></div></section>
      <section className="section-divider-bottom bg-tonal py-14 lg:py-20"><div className="container-custom grid gap-8 lg:grid-cols-[.68fr_1.32fr]"><div><SectionHeading eyebrow="Onderweg" title="Een omkeerregel is onderdeel van je route" description="Regen, donkerte, vermoeidheid, alcohol, slechte remmen of een onrustig gevoel zijn redenen om niet te vertrekken of direct veilig te stoppen."/></div><div className="grid gap-4 sm:grid-cols-2">{[
        ["Regen & zand","Remweg en grip veranderen. Wacht, verkort de route of neem ander vervoer.",AlertTriangle],
        ["Donker & onbekend","Geen eerste rit, bergpas of verre strandroute na zonsondergang.",Route],
        ["Alcohol & middelen","Nooit zelf rijden; regel de motorfiets en terugrit vóór de avond.",ShieldCheck],
        ["Pech of ongeval","Ga uit de rijlijn, bel hulp/verhuurder, documenteer en zoek medische hulp bij letsel.",PhoneCall],
      ].map(([title,copy,Icon]:any)=><article key={title} className="rounded-2xl border border-jade/10 bg-white p-6"><Icon className="text-saffron-dark"/><h3 className="mt-5 font-display text-2xl font-semibold text-jade">{title}</h3><p className="mt-3 text-xs font-medium leading-6 text-charcoal/62">{copy}</p></article>)}</div></div></section>
      <section id="alternatief" className="section-divider-bottom scroll-mt-24 py-14 lg:py-20"><div className="container-custom grid gap-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><SectionHeading eyebrow="Niet rijden is óók een reisbesluit" title="Koop mobiliteit, geen risico" description="Verblijf dichter bij wat je wilt doen of kies trein, lokale taxi, ride-hailing, songthaew, boot, transfer of chauffeur. Vergelijk totale route en terugweg, niet alleen één ritprijs."/><div className="mt-6 flex flex-wrap gap-3">{["Loopbare basis","Rail + taxi","Gedeelde transfer","Privéchauffeur","Georganiseerde dagtour"].map(x=><span key={x} className="rounded-full border border-jade/12 bg-white px-4 py-2 text-[10px] font-bold text-jade">{x}</span>)}</div><AffiliateDisclosure className="mt-6">Klook-affiliatelink: we kunnen commissie ontvangen zonder extra kosten voor jou. Controleer actuele prijs, voertuig, ophaalpunt, bagage, duur, inclusies en annuleringsvoorwaarden zelf.</AffiliateDisclosure></div><div className="rounded-2xl bg-jade p-7 text-white"><TramFront className="text-saffron"/><h3 className="mt-5 font-display text-3xl font-semibold">Transfers en vervoer vergelijken</h3><p className="mt-3 text-xs font-medium leading-6 text-white/65">Gebruik dit als alternatief wanneer documenten, ervaring, route of dekking niet volledig kloppen—niet als scooterhuur-CTA.</p><a href={transferHref} target="_blank" rel="noopener noreferrer nofollow sponsored" className="btn-cream mt-6 min-h-12 px-6 text-saffron-dark">Bekijk actuele vervoersopties <ExternalLink size={15}/></a><p className="mt-5 text-[10px] font-semibold leading-5 text-white/50">Geen Amazonproducten: helmkeuring, pasvorm en lokale motorcategorie vragen specialistische controle; een gadget maakt onervaren rijden niet veiliger.</p></div></div></section>
      <div id="vragen"><FaqSplitSection eyebrow="Echte zoekvragen" title="Veelgestelde vragen over scooterhuur in Thailand" description="Antwoorden die verhuur, rijbevoegdheid, verzekering en veilige rijbeslissing uit elkaar houden." items={faqs}/></div>
      <RelatedGuidesSection title="Regel de rest van de keten" guides={[{title:"Reisverzekering",description:"Lees polisvoorwaarden rond motorrijden, medische kosten en aansprakelijkheid.",href:"/travel-insurance/",image:"/images/redesign/thailand-health-hospitals-hero-v2.webp"},{title:"Vervoer in Thailand",description:"Vergelijk trein, bus, boot, taxi en transfer als volwaardige alternatieven.",href:"/transport/",image:"/images/redesign/transport-thailand-hero.webp"},{title:"Veiligheid & scams",description:"Herken borg-, schade- en documentrisico’s naast andere reissituaties.",href:"/practical-info/scams-safety/",image:"/images/redesign/thailand-safety-hero.webp"}]}/>
      <SourceMethodSection title="Een sleutel zegt alleen dat de motor beschikbaar is" description="Zichtbare Nederlandse SERP/PAA zijn op 31 juli 2026 gecontroleerd. ANWB, NederlandWereldwijd, Thai DLT en WHO dragen de rijbewijs-, verhuur- en veiligheidsgrenzen. Geen vaste huurprijzen, boetes, ziekenhuisbedragen, wisselkoers of onbewezen verhuurderslijst." sources={[{title:"Reisdocumenten en rijbewijs Thailand",creator:"ANWB",url:"https://www.anwb.nl/vakantie/thailand/reisvoorbereiding/reisdocumenten",note:"Nederlandse rijbewijs-/IRB-context en voertuigcategorie voor Nederlandse ingezetenen."},{title:"Reisadvies Thailand",creator:"NederlandWereldwijd",url:"https://www.nederlandwereldwijd.nl/reisadvies/thailand",note:"Actuele verkeers-, scooterverhuur-, borg-, document- en verzekeringswaarschuwingen."},{title:"Recognised driving permits",creator:"Thai Department of Land Transport",url:"https://fvp.dlt.go.th/Manual2",note:"Officiële Thaise context voor erkende internationale rijbewijsmodellen."},{title:"Road safety in Thailand",creator:"World Health Organization",url:"https://www.who.int/thailand/our-work/road-safety",note:"Verkeerssterfte, motorfietsrisico en preventieprioriteiten."},{title:"Helmets manual",creator:"World Health Organization",url:"https://www.who.int/publications/i/item/9789240069824",note:"Effect van veilige kwaliteitshelmen zonder helm als vrijbrief te behandelen."}]}/>
    </div>
  </>;
}
