import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Banknote, Check, ExternalLink, MapPinned, PackageCheck, ReceiptText, Route, SearchCheck, ShieldCheck, ShoppingBag, Sparkles, Store, Tags } from "lucide-react";
import SEOHead from "../SEOHead";
import { AffiliateDisclosure } from "../design/AffiliateDisclosure";
import { EditorialHero } from "../design/EditorialHero";
import { FaqSplitSection } from "../design/FaqSplitSection";
import { PageSectionNav } from "../design/PageSectionNav";
import { RelatedGuidesSection } from "../design/RelatedGuidesSection";
import { SectionHeading } from "../design/SectionHeading";
import { SourceMethodSection } from "../design/SourceMethodSection";
import { KLOOK_GENERIC, withPlacementSubId } from "../../lib/affiliates";
import { useSubId } from "../../lib/useSubId";

const profiles = [
  { title:"Weekend- & makersmarkt", tag:"Ambacht, vintage, ontwerp", copy:"Goed als je wilt dwalen en makers wilt vergelijken. De kwaliteit, herkomst en opening verschillen per kraam en editie.", check:"Open dag, zone, maker en materiaal", icon:Store },
  { title:"Avondmarkt", tag:"Sfeer, eten, kleine aankopen", copy:"Past bij een avondroute, maar een populaire naam garandeert geen vaste locatie of hetzelfde aanbod.", check:"Locatie van vandaag en terugreis", icon:Sparkles },
  { title:"Dag- & versmarkt", tag:"Lokaal ritme", copy:"Sterk voor dagelijks leven, ingrediënten en snacks. Niet ieder product is geschikt om mee naar huis te nemen.", check:"Hygiëne, verpakking en invoerregels", icon:ShoppingBag },
  { title:"Drijvende markt", tag:"Waterroute", copy:"Kies bewust tussen een functionele lokale markt en een bezoekerservaring. Check vertrekpunt, vaartijd en inclusies.", check:"Exacte pier, boot en totale duur", icon:Route },
  { title:"Mall & designhub", tag:"Merken, airco, vaste kassa", copy:"Handig voor bonnen, pasvorm en formele winkels. Controleer ook hier verkoper, retourvoorwaarden en authenticiteitsclaims.", check:"Winkel, bon, garantie en retour", icon:ReceiptText },
  { title:"Specialistenmarkt", tag:"Textiel, keramiek, edelstenen", copy:"Interessant als je gericht zoekt. Vraag naar materiaal en herkomst, maar behandel een verkoopverhaal nooit als bewijs.", check:"Specificatie, expertise en transport", icon:BadgeCheck },
];

const faqs = [
  {question:"Wat kun je kopen op een Thaise markt?",answer:"Dat verschilt per marktprofiel: eten en dagelijkse producten op versmarkten, kleding en accessoires op weekend- en avondmarkten, en vaker ambacht of ontwerp op makersmarkten. Controleer materiaal, maat, staat, verpakking en invoerregels voordat je koopt."},
  {question:"Wat kan ik kopen op Chatuchak Market?",answer:"Chatuchak heeft veel zones en een breed wisselend aanbod, waaronder kleding, woonartikelen, kunst, planten, accessoires en eten. Kies vooraf een productcategorie, controleer de actuele opening en gebruik een lokale Chatuchak-gids voor ingang en route."},
  {question:"Wat is de grootste markt in Thailand?",answer:"Superlatieven hangen af van de gekozen maatstaf, zoals terrein, aantal kramen of bezoekers. Chatuchak wordt vaak als zeer groot omschreven, maar ‘de grootste’ is geen bruikbaar koopadvies. Kies op aanbod, openingsmoment en bereikbaarheid."},
  {question:"Is kleding goedkoper in Thailand?",answer:"Soms, maar niet automatisch. Prijs hangt af van materiaal, afwerking, merk, verkoper en locatie. Vergelijk vergelijkbare producten, pas kleding en beoordeel naden, ritsen en stof in plaats van alleen de omgerekende prijs."},
  {question:"Kun je afdingen op markten in Thailand?",answer:"Op sommige informele markten is vriendelijk onderhandelen mogelijk; bij vaste prijzen, winkels en eten vaak niet. Vraag rustig naar de prijs, doe een redelijk bod en accepteer zonder druk als de verkoper niet meegaat. Een vast kortingspercentage bestaat niet."},
  {question:"Kan ik btw terugvragen en alles meenemen naar Nederland?",answer:"Nee. Een Thaise VAT-refund geldt alleen onder voorwaarden bij deelnemende winkels en staat los van Nederlandse invoerregels. Bewaar bonnen, controleer de actuele Thaise procedure en kijk vóór aankoop bij de Nederlandse Douane of het product en de waarde zijn toegestaan."},
];

export default function ThailandShoppingMarketsGuideNl(){
  const subId=useSubId();
  const klookHref=withPlacementSubId(KLOOK_GENERIC,subId,"shopping-markets-thailand-nl-guided");
  const pageUrl="https://go2-thailand.com/nl/travel-guides/shopping-markets-thailand/";
  const schemas=[
    {"@context":"https://schema.org","@type":"Article",headline:"Markten in Thailand: kiezen, kopen en meenemen",description:"Kies het juiste marktprofiel en controleer opening, productkwaliteit, afdingen, VAT-refund en Nederlandse invoerregels.",image:"https://go2-thailand.com/images/redesign/thailand-shopping-markets-hero-v2.webp",url:pageUrl,inLanguage:"nl-NL",author:{"@type":"Organization",name:"GO2 Thailand"},publisher:{"@type":"Organization",name:"GO2 Thailand"},dateModified:"2026-07-31"},
    {"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(({question,answer})=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))},
    {"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Thailand",item:"https://go2-thailand.com/nl/"},{"@type":"ListItem",position:2,name:"Reisgidsen",item:"https://go2-thailand.com/nl/travel-guides/"},{"@type":"ListItem",position:3,name:"Markten en shoppen",item:pageUrl}]},
  ];
  return <>
    <SEOHead title="Markten Thailand: slim shoppen, afdingen en douane" description="Vind een markt in Thailand die bij je past. Controleer opening, kwaliteit, afdingen, bonnen, VAT-refund en Nederlandse invoerregels." ogImage="https://go2-thailand.com/images/redesign/thailand-shopping-markets-hero-v2.webp">{schemas.map((schema,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>)}</SEOHead>
    <div data-premium-template="shopping-markets-thailand-nl" className="overflow-hidden bg-canvas text-charcoal">
      <EditorialHero image="/images/redesign/thailand-shopping-markets-hero-v2.webp" imageAlt="Lokale maker toont handgemaakt vlechtwerk aan reizigers op een Thaise avondmarkt" breadcrumbs={[{label:"Thailand",href:"/"},{label:"Reisgidsen",href:"/travel-guides/"},{label:"Markten"}]} eyebrow="Kijk verder dan het prijskaartje" title={<>Thailand verkoopt.<br/><span className="text-saffron-light">Jij kiest bewust.</span></>} subtitle="Een marktnaam is nog geen koopadvies." description="Kies eerst het marktprofiel. Check daarna de opening van vandaag, het product in je hand en of je aankoop ook echt mee naar huis mag." actions={[{label:"Kies je markt",href:"#marktprofielen",kind:"primary"},{label:"Volg de kooproute",href:"#kooproute",kind:"secondary"}]} contentTone="light" gradientClassName="bg-[linear-gradient(90deg,rgba(2,24,21,.98)_0%,rgba(2,24,21,.9)_43%,rgba(2,24,21,.18)_70%,rgba(2,24,21,.03)_100%)]" imageClassName="object-cover object-center" titleClassName="max-w-[820px] text-[3.7rem] leading-[.86] !text-white sm:text-[4.8rem] lg:text-[5.7rem]" subtitleClassName="max-w-[620px] text-[1.3rem] !text-white sm:text-[1.55rem]" descriptionClassName="mt-4 max-w-[580px] text-sm leading-7 !text-white/75"/>
      <PageSectionNav items={[{href:"#marktprofielen",label:"Markt kiezen",icon:Store},{href:"#kooproute",label:"Slim kopen",icon:SearchCheck},{href:"#meenemen",label:"Meenemen",icon:PackageCheck},{href:"#vragen",label:"Vragen",icon:Sparkles}]}/>
      <section className="section-divider-bottom bg-canvas py-5"><div className="container-custom grid gap-3 sm:grid-cols-3">{[{k:"Kies",v:"Profiel boven populariteit",I:Store},{k:"Check",v:"Vandaag, ingang en verkoper",I:SearchCheck},{k:"Neem mee",v:"Bon, verpakking en regels",I:PackageCheck}].map(({k,v,I})=><div key={k} className="flex min-h-20 items-center gap-4 rounded-xl border border-jade/10 bg-tonal px-5 py-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-jade text-saffron"><I size={19}/></span><span><span className="block text-[9px] font-extrabold uppercase tracking-[.15em] text-saffron-dark">{k}</span><strong className="font-display text-xl text-jade">{v}</strong></span></div>)}</div></section>
      <section id="marktprofielen" className="section-divider-bottom scroll-mt-24 py-14 lg:py-20"><div className="container-custom"><SectionHeading eyebrow="Niet iedere markt doet hetzelfde" title={<>Zes marktprofielen.<br/>Eén die bij vandaag past.</>} description="Begin bij wat je wilt ervaren of kopen. Controleer daarna pas de actuele marktnaam, dag en locatie."/><div className="mt-9 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{profiles.map(({title,tag,copy,check,icon:Icon},index)=><article key={title} className="flex min-h-[330px] flex-col rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl border border-saffron/25 bg-saffron/8 text-jade"><Icon size={21}/></span><span className="font-display text-4xl text-jade/12">0{index+1}</span></div><p className="mt-6 text-[9px] font-extrabold uppercase tracking-[.15em] text-saffron-dark">{tag}</p><h3 className="mt-2 font-display text-[1.65rem] font-semibold leading-none text-jade">{title}</h3><p className="mt-4 text-xs font-medium leading-6 text-charcoal/66">{copy}</p><p className="mt-auto border-t border-jade/10 pt-4 text-[10px] font-semibold text-charcoal/50">Check: {check}</p></article>)}</div></div></section>
      <section id="kooproute" className="section-divider-bottom scroll-mt-24 bg-tonal py-14 lg:py-20"><div className="container-custom grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><SectionHeading eyebrow="Van kraam naar keuze" title="Vijf checks vóór je betaalt" description="Een vriendelijk verkoopverhaal kan nuttig zijn, maar materiaal, maat, staat en voorwaarden moeten zelf controleerbaar blijven."/><div className="mt-7 rounded-2xl bg-jade p-6 text-white"><Tags className="text-saffron"/><h3 className="mt-4 font-display text-2xl font-semibold">Afdingen zonder toneel</h3><p className="mt-3 text-xs font-medium leading-6 text-white/68">Vraag rustig, bied redelijk en loop vriendelijk door als het niet past. Geen vast percentage en geen druk op een maker voor wie tijd en materiaal echte kosten zijn.</p></div></div><div className="space-y-4">{[
        ["01","Controleer de markt van vandaag","Officiële pagina of recente lokale bron, juiste dag, locatie, ingang en sluitingstijd.",MapPinned],
        ["02","Bekijk het echte product","Materiaal, naden, ritsen, maat, beschadiging, inhoud en verpakking—niet alleen het voorbeeld.",SearchCheck],
        ["03","Vraag wat een claim betekent","‘Handgemaakt’, ‘zilver’ of ‘lokaal’ is pas bruikbaar als de verkoper het concreet kan toelichten.",BadgeCheck],
        ["04","Spreek prijs en betaling af","Controleer valuta, totaalbedrag, betaalmethode en eventuele kaarttoeslag vóór betaling.",Banknote],
        ["05","Bewaar bewijs en vertrekplan","Vraag waar relevant een bon, maak een foto van winkel/verkoper en regel transport zonder de doorgang te blokkeren.",ReceiptText],
      ].map(([n,title,copy,Icon]:any)=><article key={n} className="grid gap-4 rounded-2xl border border-jade/10 bg-white p-5 shadow-editorial-card sm:grid-cols-[auto_1fr_auto] sm:items-center"><span className="font-display text-3xl text-saffron-dark">{n}</span><span><h3 className="font-display text-xl font-semibold text-jade">{title}</h3><p className="mt-2 text-xs font-medium leading-5 text-charcoal/62">{copy}</p></span><Icon className="text-jade" size={23}/></article>)}</div></div></section>
      <section id="meenemen" className="section-divider-bottom scroll-mt-24 py-14 lg:py-20"><div className="container-custom"><div className="grid overflow-hidden rounded-[1.7rem] bg-jade text-white shadow-editorial-card lg:grid-cols-[1fr_1fr]"><div className="relative min-h-[420px]"><Image src="/images/redesign/chatuchak-market-kit.webp" alt="Textiel, accessoires en kleine aankopen voorbereid voor controle en vervoer" fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/></div><div className="p-7 lg:p-10"><p className="eyebrow !text-saffron-light">Van kraam naar koffer</p><h2 className="font-display text-[3.1rem] font-semibold leading-[.9]">Mag het mee?<br/>Kun je het dragen?</h2><ul className="mt-7 space-y-3">{["Controleer vóór aankoop Nederlandse verboden, beperkingen en waardedrempels","Hout, planten, voeding, dierlijke producten en namaak vragen extra aandacht","Een Thaise VAT-refund en Nederlandse invoerheffing zijn twee verschillende controles","Bewaar aankoopbewijs en voorgeschreven VAT-documenten; luchthavenprocedures kosten tijd","Laat grote, breekbare of twijfelachtige aankopen staan als transport en invoer niet helder zijn"].map(item=><li key={item} className="flex gap-3 text-xs font-medium leading-5 text-white/72"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-saffron text-jade"><Check size={12} strokeWidth={3}/></span>{item}</li>)}</ul></div></div></div></section>
      <section className="section-divider-bottom bg-tonal py-14 lg:py-20"><div className="container-custom grid gap-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><SectionHeading eyebrow="Een markt bezoeken is vaak gratis" title="Boek alleen als begeleiding iets toevoegt" description="Een tour kan helpen met route, context of proeven. Hij maakt een vrije markt niet ineens ticketplichtig en vervangt de actuele openingscheck niet."/><AffiliateDisclosure className="mt-5">Klook-affiliatelink: we kunnen commissie ontvangen zonder extra kosten voor jou. Controleer datum, ontmoetingspunt, duur, inclusies, actuele prijs en annuleringsvoorwaarden zelf.</AffiliateDisclosure><p className="mt-4 text-xs font-medium leading-6 text-charcoal/55">Geen Amazon-producten op deze pagina: een aankoopgids hoort niet zelf een willekeurig extra productprobleem te creëren.</p></div><div className="rounded-2xl bg-jade p-7 text-white"><MapPinned className="text-saffron"/><h3 className="mt-5 font-display text-3xl font-semibold">Markt- en shoppingtours vergelijken</h3><p className="mt-3 text-xs font-medium leading-6 text-white/65">Kies alleen als gids, vervoer, proeven of lokale uitleg jouw bezoek aantoonbaar makkelijker maken.</p><a href={klookHref} target="_blank" rel="noopener noreferrer nofollow sponsored" className="btn-cream mt-6 min-h-12 px-6 text-saffron-dark">Bekijk actuele opties <ExternalLink size={15}/></a></div></div></section>
      <div id="vragen"><FaqSplitSection eyebrow="Echte zoekvragen" title="Veelgestelde vragen over markten in Thailand" description="Praktische antwoorden zonder vaste kortingspercentages, prijsbeloften of superlatieven als koopadvies." items={faqs}/></div>
      <RelatedGuidesSection title="Zoom in op Bangkokse markten" guides={[{title:"Chatuchak Market",description:"Kies zones, ingang en een haalbare looproute voor de actuele marktdag.",href:"/blog/chatuchak-market-bangkok-guide/",image:"/images/redesign/chatuchak-food-hero.webp"},{title:"Eten op Chatuchak",description:"Scheid een foodroute van de bredere shoppingmarkt.",href:"/blog/chatuchak-weekend-market-food-guide/",image:"/images/redesign/chatuchak-food-route.webp"},{title:"Jodd Fairs",description:"Controleer de actuele locatie en plan een compacte avondroute.",href:"/blog/jodd-fairs-bangkok-night-market-guide/",image:"/images/redesign/jodd-fairs-ratchada-hero.webp"}]}/>
      <SourceMethodSection title="De markt beweegt; je controle blijft" description="Nederlandse PAA en zichtbare zoekresultaten zijn op 31 juli 2026 gecontroleerd. Officiële toerisme-, douane- en VAT-bronnen bepalen de grenzen; lokale marktowners blijven verantwoordelijk voor actuele opening en route." sources={[{title:"Shopping in Thailand",creator:"Tourism Authority of Thailand",url:"https://www.tourismthailand.org/Experiences/Details/shopping/33",note:"Officiële context voor winkel- en marktprofielen."},{title:"Bangkok",creator:"Tourism Authority of Thailand",url:"https://www.tourismthailand.org/Destinations/Provinces/bangkok/219",note:"Bestemmingscontext voor markten, winkelgebieden en bereikbaarheid."},{title:"VAT Refund for Tourists",creator:"Thai Customs",url:"https://dmk.customs.go.th/cont_strc_simple.php?ini_content=Vat_Refund&ini_menu=menu_passenger_declaration&lang=th&left_menu=Vat_Refund",note:"Officiële procedure en voorwaarden; controleer de nieuwste instructies vóór vertrek."},{title:"Douane voor particulieren",creator:"Belastingdienst / Douane",url:"https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/douane/",note:"Nederlandse invoerregels, verboden en beperkingen bij terugkeer."}]}/>
    </div>
  </>;
}
