import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, CalendarRange, Compass, ExternalLink, FileCheck2, Map, Route, ShieldCheck, WalletCards, Waves } from 'lucide-react';
import SEOHead from '../SEOHead';
import { AffiliateDisclosure } from '../design/AffiliateDisclosure';
import { EditorialHero } from '../design/EditorialHero';
import { FaqSplitSection } from '../design/FaqSplitSection';
import { PageSectionNav } from '../design/PageSectionNav';
import { RelatedGuidesSection } from '../design/RelatedGuidesSection';
import { SectionHeading } from '../design/SectionHeading';
import { SourceMethodSection } from '../design/SourceMethodSection';
import { KLOOK_GENERIC, TRIP_GENERIC, TWELVEGO_GENERIC, withPlacementSubId } from '../../lib/affiliates';
import { useSubId } from '../../lib/useSubId';

const decisions = [
  { number: '01', title: 'Kies je reisvenster', eyebrow: 'Seizoen vóór strandnaam', description: 'Vergelijk maand, regio en kust. De Golf en Andaman hebben niet hetzelfde ritme en een landelijke weerbelofte is te grof.', href: '/weather/', label: 'Vergelijk weer per regio', icon: CalendarRange },
  { number: '02', title: 'Bouw een rustige route', eyebrow: 'Hotelbases vóór dagtrips', description: 'Kies een beperkt aantal bases en tel elke lange verplaatsing als reisdag. Voeg pas daarna eilanden, parken en excursies toe.', href: '/itineraries/', label: 'Vergelijk reisroutes', icon: Route },
  { number: '03', title: 'Regel toegang en risico', eyebrow: 'Officiële status vóór aannames', description: 'Controleer paspoort, TDAC, reisadvies, verzekering en voorwaarden voor scooter, boot of natuuractiviteit.', href: '/visa/', label: 'Open de toegangsgids', icon: FileCheck2 },
  { number: '04', title: 'Toets het echte totaal', eyebrow: 'Actuele quotes vóór dagbudget', description: 'Open je concrete data voor hotel, lange trajecten en grote activiteiten. Een redactionele bandbreedte is geen live prijs.', href: '/thailand-index/budget/', label: 'Gebruik de budgetplanner', icon: WalletCards },
];

const travelShapes = [
  { title: 'Stad + noorden', tag: 'Cultuur en eten', copy: 'Bangkok en één noordelijke basis. Voeg alleen een kust toe wanneer je genoeg nachten én een logisch reisvenster hebt.', image: '/images/redesign/northern-thailand-region-hero-nl.webp', href: '/region/northern/' },
  { title: 'Stad + Andaman', tag: 'Kalksteen en eilanden', copy: 'Bangkok plus één kustcluster rond Krabi, Phuket, Khao Lak of de bijpassende eilanden—niet allemaal in één korte reis.', image: '/images/redesign/thailand-island-hopping-hero-v2.webp', href: '/region/southern/' },
  { title: 'Stad + Golf', tag: 'Eigen weerbeslissing', copy: 'Combineer Bangkok met Samui, Phangan of Tao wanneer het maandprofiel, de zeeverbinding en je tempo daarbij passen.', image: '/images/redesign/koh-samui-destination-hero.webp', href: '/city/koh-samui/' },
];

const faqs = [
  { question: 'Wat is de beste reisgids voor Thailand?', answer: 'De beste gids past bij je manier van plannen. Gebruik een actuele digitale gids voor veranderlijke toegang, vervoer en weer; een goede papieren gids kan prettig zijn voor context en offline oriëntatie. Controleer tijdgevoelige informatie altijd bij de primaire bron.' },
  { question: 'Hoeveel geld heb je nodig voor 3 weken Thailand?', answer: 'Dat hangt vooral af van reisdata, hotelniveau, aantal binnenlandse verplaatsingen en betaalde activiteiten. Maak eerst je route, open daarna actuele totaalprijzen en gebruik de budgetplanner voor een persoonlijke bandbreedte in plaats van één universeel bedrag.' },
  { question: 'Wat moet je vermijden in Thailand?', answer: 'Vermijd een overvolle route, onofficiële grens- of visuminformatie, rijden zonder passende documenten en verzekering, het negeren van rode vlaggen of parkstatus en activiteiten met onverantwoord diercontact. Volg lokale instructies en het actuele reisadvies.' },
  { question: 'Welke maand kun je het beste naar Thailand?', answer: 'Er bestaat geen beste maand voor iedere route. November tot februari is voor veel eerste reizen een bruikbaar startpunt, maar kust, regen, hitte, luchtkwaliteit, drukte en prijs kunnen de afweging veranderen. Vergelijk daarom je exacte regio’s.' },
];

export default function ThailandTravelGuideNl() {
  const subId = useSubId();
  const pageUrl = 'https://go2-thailand.com/nl/thailand-travel-guide/';
  const tripHref = withPlacementSubId(TRIP_GENERIC, subId, 'thailand-travel-guide-nl-hotels');
  const transportHref = withPlacementSubId(TWELVEGO_GENERIC, subId, 'thailand-travel-guide-nl-transport');
  const klookHref = withPlacementSubId(KLOOK_GENERIC, subId, 'thailand-travel-guide-nl-activities');
  const schemas = [
    { '@context': 'https://schema.org', '@type': 'Article', headline: 'Thailand reisgids: van eerste keuze tot uitvoerbare reis', description: 'Plan Thailand in de juiste volgorde: reisvenster, route, toegang, budget en actuele boekingschecks.', image: 'https://go2-thailand.com/images/redesign/thailand-travel-guide-hero-v2.webp', url: pageUrl, inLanguage: 'nl-NL', author: { '@type': 'Organization', name: 'GO2 Thailand' }, publisher: { '@type': 'Organization', name: 'GO2 Thailand' } },
    { '@context': 'https://schema.org', '@type': 'ItemList', name: 'Thailand plannen in vier beslissingen', numberOfItems: decisions.length, itemListElement: decisions.map((item, index) => ({ '@type': 'ListItem', position: index + 1, name: item.title, url: `https://go2-thailand.com/nl${item.href}` })) },
    { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(({ question, answer }) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) },
    { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Thailand', item: 'https://go2-thailand.com/nl/' }, { '@type': 'ListItem', position: 2, name: 'Thailand reisgids', item: pageUrl }] },
  ];

  return <>
    <SEOHead title="Thailand reisgids: plan je reis in de juiste volgorde" description="Plan Thailand stap voor stap: kies reisvenster, route, toegang, budget en controleer daarna actuele hotels, vervoer en activiteiten." ogImage="https://go2-thailand.com/images/redesign/thailand-travel-guide-hero-v2.webp">
      {schemas.map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}
    </SEOHead>
    <div data-premium-template="thailand-travel-guide-nl" className="overflow-hidden bg-canvas text-charcoal">
      <EditorialHero image="/images/redesign/thailand-travel-guide-hero-v2.webp" imageAlt="Reiziger met kaart kijkt over een gelaagd Thailandlandschap van rivierstad tot bergen en kust" breadcrumbs={[{ label: 'Thailand', href: '/' }, { label: 'Reisgids' }]} eyebrow="Een digitale reisgids die keuzes ordent" title={<>Thailand.<br /><span className="text-saffron">Begin bij het plan.</span></>} subtitle="Niet bij een eindeloze checklist." description="Kies eerst wanneer, waar en in welk tempo je reist. Regel daarna toegang, budget en pas als laatste de actuele boekingen." actions={[{ label: 'Start met vier keuzes', href: '#start', kind: 'primary' }, { label: 'Voor het eerst?', href: '/thailand-for-first-timers/', kind: 'secondary' }]} titleClassName="!text-white" subtitleClassName="!text-white" descriptionClassName="!text-white/75" contentClassName="[&_nav]:!text-white/60 [&_nav_span]:!text-white/75" imageClassName="object-cover object-[66%_center]" gradientClassName="bg-[linear-gradient(90deg,rgba(4,42,34,.98)_0%,rgba(4,42,34,.86)_38%,rgba(4,42,34,.16)_70%,rgba(4,42,34,.04)_100%)]" />
      <PageSectionNav items={[{ href: '#start', label: 'Beginnen', icon: Compass }, { href: '#route', label: 'Routevorm', icon: Map }, { href: '#boeken', label: 'Actueel boeken', icon: ShieldCheck }, { href: '#vragen', label: 'Vragen', icon: Waves }]} />

      <section id="start" className="section-divider-bottom scroll-mt-24 py-16 lg:py-24"><div className="container-custom"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><SectionHeading eyebrow="De volgorde voorkomt herstelwerk" title="Vier beslissingen vóór je gaat boeken." description="Wie eerst losse hotels en highlights verzamelt, krijgt vaak extra transfers en verkeerde kustdata. Deze vier owners houden elk één veranderlijke beslissing bij." /><p className="max-w-2xl text-sm font-medium leading-7 text-charcoal/62">Deze pagina is de landkaart van de website. Details blijven bij hun eigen owner, zodat weer, toegang, kosten en routes niet op meerdere pagina’s uit elkaar gaan lopen.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2">{decisions.map(({ number, title, eyebrow, description, href, label, icon: Icon }) => <Link key={title} href={href} className="group grid gap-5 rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card sm:grid-cols-[auto_1fr_auto] sm:items-center"><span className="grid h-12 w-12 place-items-center rounded-xl bg-jade text-saffron"><Icon size={21} /></span><div><p className="text-[9px] font-extrabold uppercase tracking-[.14em] text-saffron-dark">{number} · {eyebrow}</p><h2 className="mt-2 font-display text-[1.8rem] font-semibold leading-none text-jade">{title}</h2><p className="mt-3 text-xs font-medium leading-6 text-charcoal/64">{description}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-extrabold text-jade">{label} <ArrowRight size={13} className="text-saffron-dark transition group-hover:translate-x-1" /></span></div><span className="hidden h-9 w-9 place-items-center rounded-full border border-jade/12 text-jade sm:grid"><ArrowRight size={15} /></span></Link>)}</div></div></section>

      <section id="route" className="section-divider-bottom scroll-mt-24 bg-tonal py-16 lg:py-24"><div className="container-custom"><div className="grid gap-8 lg:grid-cols-[.65fr_1.35fr] lg:items-end"><SectionHeading eyebrow="Drie routevormen" title="Kies één logisch reisnetwerk." description="Een eerste reis hoeft niet heel Thailand te bewijzen. Een sterke route gebruikt weinig hotelbases en laat ruimte voor weer, herstel en een onverwacht goede plek." /><Link href="/itineraries/" className="inline-flex items-center gap-2 text-sm font-extrabold text-jade lg:justify-self-end">Vergelijk alle reisroutes <ArrowRight size={15} className="text-saffron-dark" /></Link></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{travelShapes.map((shape) => <Link key={shape.title} href={shape.href} className="group overflow-hidden rounded-2xl border border-jade/10 bg-white shadow-editorial-card"><div className="relative h-60 overflow-hidden"><Image src={shape.image} alt="" fill sizes="(max-width:1024px) 100vw, 33vw" className="object-cover transition duration-500 group-hover:scale-[1.035]" /><div className="absolute inset-0 bg-gradient-to-t from-jade/80 via-transparent to-transparent" /><span className="absolute bottom-4 left-4 text-[9px] font-extrabold uppercase tracking-[.14em] text-saffron">{shape.tag}</span></div><div className="p-6"><h2 className="font-display text-[2rem] font-semibold leading-none text-jade">{shape.title}</h2><p className="mt-4 text-xs font-medium leading-6 text-charcoal/64">{shape.copy}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-extrabold text-jade">Open het netwerk <ArrowRight size={13} className="text-saffron-dark" /></span></div></Link>)}</div></div></section>

      <section id="boeken" className="section-divider-bottom scroll-mt-24 py-16 lg:py-24"><div className="container-custom"><div className="overflow-hidden rounded-[28px] bg-jade text-white lg:grid lg:grid-cols-[.8fr_1.2fr]"><div className="p-7 lg:p-10"><p className="eyebrow !text-saffron">Pas als de route klopt</p><h2 className="font-display text-[3rem] font-semibold leading-[.9]">Vervang aannames door actuele quotes.</h2><p className="mt-5 text-sm font-medium leading-7 text-white/65">Gebruik dezelfde data, plaats en voorwaarden wanneer je vergelijkt. De externe pagina—not onze tekst—is eigenaar van de actuele prijs en beschikbaarheid.</p><AffiliateDisclosure className="mt-5 !text-white/55">De drie knoppen zijn gesponsorde affiliate-links. Go2Thailand kan commissie ontvangen zonder dat jouw prijs stijgt.</AffiliateDisclosure></div><div className="grid gap-px bg-white/10 sm:grid-cols-3">{[
          { label: 'Hotels', title: 'Trip.com', copy: 'Buurt, kamertype en annulering.', href: tripHref },
          { label: 'Lange trajecten', title: '12Go', copy: 'Terminal, bagage en overstap.', href: transportHref },
          { label: 'Activiteiten', title: 'Klook', copy: 'Pickup, inclusies en conditie.', href: klookHref },
        ].map((item) => <article key={item.title} className="flex flex-col bg-jade p-7"><p className="text-[9px] font-extrabold uppercase tracking-[.14em] text-saffron">{item.label}</p><h3 className="mt-4 font-display text-3xl font-semibold">{item.title}</h3><p className="mt-3 text-xs font-medium leading-5 text-white/60">{item.copy}</p><a href={item.href} target="_blank" rel="noopener noreferrer nofollow sponsored" className="mt-auto inline-flex min-h-11 items-center gap-2 pt-6 text-xs font-extrabold text-white">Bekijk actuele opties <ExternalLink size={13} className="text-saffron" /></a></article>)}</div></div></div></section>

      <FaqSplitSection id="vragen" eyebrow="Echte Nederlandse zoekvragen" title="Veelgestelde vragen over een Thailand-reisgids" description="De vragen zijn op 31 juli 2026 zichtbaar gecontroleerd in Google Nederland. Veranderlijke prijzen, regels en weersituaties krijgen bewust geen schijnexact antwoord." items={faqs} />
      <RelatedGuidesSection eyebrow="Kies je volgende owner" title="Van landgids naar concrete reis" guides={[{ title: 'Eerste keer Thailand', description: 'Regel aankomst, documenten, geld en connectiviteit in een rustige volgorde.', href: '/thailand-for-first-timers/', image: '/images/redesign/first-time-thailand-hero.webp', imageAlt: 'Eerste reis naar Thailand voorbereiden' }, { title: 'Thailand-reisroutes', description: 'Vergelijk hotelbases, duur en aantal overgangen.', href: '/itineraries/', image: '/images/redesign/thailand-route-hero.webp', imageAlt: 'Route door Thailand' }, { title: 'Wat te doen', description: 'Kies activiteiten op regio, tempo en actuele conditie.', href: '/things-to-do-in-thailand/', image: '/images/redesign/thailand-excursions-hero.webp', imageAlt: 'Activiteiten in Thailand' }]} />
      <SourceMethodSection eyebrow="Bronnen & researchmethode" title="Actueel waar het moet, redactioneel waar het kan" description="De owner combineert opgeslagen Nederlandse DFS-signalen met een zichtbare Google Nederland-SERP, vier echte PAA-vragen en primaire bronnen. Hij verkoopt geen universele beste maand, route, reisgids of dagprijs." sources={[{ title: 'Bestemmingen in Thailand', creator: 'Tourism Authority of Thailand', url: 'https://www.tourismthailand.org/Destinations', note: 'Officiële bestemming- en regiocontext.' }, { title: 'Weer en waarschuwingen', creator: 'Thai Meteorological Department', url: 'https://www.tmd.go.th/en', note: 'Primaire bron voor actuele meteorologische informatie.' }, { title: 'Reisadvies Thailand', creator: 'NederlandWereldwijd', url: 'https://www.nederlandwereldwijd.nl/reisadvies/thailand', note: 'Actuele veiligheids- en toegangscontext voor Nederlandse reizigers.' }, { title: 'Thailand Digital Arrival Card', creator: 'Thai Immigration Bureau', url: 'https://tdac.immigration.go.th/', note: 'Officieel portaal voor de actuele digitale aankomstregistratie.' }]} />
    </div>
  </>;
}
