import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Compass, ExternalLink, Landmark, MapPinned, Mountain, ShieldCheck, Sparkles, Utensils, Waves } from 'lucide-react';
import SEOHead from '../SEOHead';
import { AffiliateDisclosure } from '../design/AffiliateDisclosure';
import { EditorialHero } from '../design/EditorialHero';
import { FaqSplitSection } from '../design/FaqSplitSection';
import { PageSectionNav } from '../design/PageSectionNav';
import { RelatedGuidesSection } from '../design/RelatedGuidesSection';
import { SectionHeading } from '../design/SectionHeading';
import { SourceMethodSection } from '../design/SourceMethodSection';
import { KLOOK_GENERIC, withPlacementSubId } from '../../lib/affiliates';
import { useSubId } from '../../lib/useSubId';

const activityChoices = [
  { title: 'Stad & rivier', kicker: 'Bangkok en stadsassen', description: 'Cluster tempels, buurt, markt en rivier per stadsdeel. Niet iedere bekende plek ligt logisch op dezelfde dag.', href: '/city/bangkok/attractions/', image: '/images/redesign/bangkok-first-time-hero.webp', imageAlt: 'Rivier en tempeldaken in Bangkok', icon: Landmark },
  { title: 'Erfgoed', kicker: 'Ayutthaya en Sukhothai', description: 'Geef ruïnes context, hittepauzes en een haalbare route. Een erfgoedpark is meer dan een fotostop.', href: '/city/ayutthaya/attractions/', image: '/images/redesign/ayutthaya-destination-hero.webp', imageAlt: 'Historische tempelruïnes in Ayutthaya', icon: Sparkles },
  { title: 'Bergen & noorden', kicker: 'Stad plus conditionele buitendag', description: 'Kies één noordbasis en laat luchtkwaliteit, regen, wegconditie en eigen ervaring de bergdag bepalen.', href: '/region/northern/', image: '/images/redesign/northern-thailand-region-hero-nl.webp', imageAlt: 'Bewoonde bergvallei in Noord-Thailand', icon: Mountain },
  { title: 'Kust & eilanden', kicker: 'Eén kustnetwerk', description: 'Kies Andaman, Golf of Trat en controleer zee, pier, parkstatus en operator voordat je een bootdag vastzet.', href: '/islands/', image: '/images/redesign/thailand-island-hopping-hero-v2.webp', imageAlt: 'Boot bij een groene Thaise eilandkust', icon: Waves },
  { title: 'Natuurparken', kicker: 'Toegang bepaalt de dag', description: 'Open parkstatus, route, gidsvereiste en weer eerst. Wildlife blijft wild en waarnemingen zijn nooit gegarandeerd.', href: '/travel-guides/national-parks-thailand/', image: '/images/redesign/khao-sok-attractions-hero.webp', imageAlt: 'Regenwoud en kalksteenlandschap bij Khao Sok', icon: MapPinned },
  { title: 'Eten & maken', kicker: 'Van markt naar keuken', description: 'Gebruik een markt-, streetfood- of kooklesowner om allergenen, hygiëne, gerecht en locatie bewust te kiezen.', href: '/food/', image: '/images/redesign/thailand-food-hub-hero.webp', imageAlt: 'Thaise gerechten en ingrediënten op tafel', icon: Utensils },
];

const dayPatterns = [
  { label: 'Eén stad', title: 'Twee buurten, één rustpunt', copy: 'Plan ochtend en late middag in nabijgelegen clusters. Gebruik de heetste uren voor lunch, museum of herstel.' },
  { label: 'Eén natuurdag', title: 'Hoofdplan plus landalternatief', copy: 'Boek pas wanneer park, gids, weg en weer kloppen. Bewaar een lokale activiteit binnen dezelfde hotelbasis.' },
  { label: 'Eén zeedag', title: 'Pier, zee en operator', copy: 'Controleer pickupzone, echte pier, parktoegang, annuleringsvoorwaarden en een alternatief zonder boot.' },
];

const faqs = [
  { question: 'Wat moet je echt gedaan hebben in Thailand?', answer: 'Er is geen verplichte universele lijst. Kies minimaal één stads- of erfgoedervaring, één lokale eetcontext en—als je route en conditie passen—één natuur- of kustervaring. De combinatie moet uitvoerbaar blijven vanuit je hotelbases.' },
  { question: 'Wat moet je zeker niet doen in Thailand?', answer: 'Negeer geen tempelregels, parkafsluitingen, rode vlaggen, rijbewijs- en verzekeringseisen of lokale instructies. Boek geen dierenactiviteit met aanraken, voeren, shows of een waarnemingsgarantie.' },
  { question: 'Wat is een budget voor 4 weken Thailand?', answer: 'Dat hangt sterk af van actuele hotels, vervoer, route en activiteiten. Gebruik de afzonderlijke budgetcalculator en vergelijk daarna de actuele totaalprijs per aanbieder; deze inspiratieowner publiceert bewust geen vast maandbedrag.' },
  { question: 'Wat zijn de 10 mooiste plekken in Thailand?', answer: '“Mooiste” is subjectief en een top-10 mengt vaak onhaalbare afstanden. Kies eerst een regio of kustnetwerk en open daarna de bestemmingowners voor Bangkok, Noord-Thailand, Centraal-Thailand, Zuid-Thailand en Isaan.' },
];

export default function ThailandThingsToDoGuideNl() {
  const subId = useSubId();
  const klookHref = withPlacementSubId(KLOOK_GENERIC, subId, 'things-to-do-thailand-nl-activity-check');
  const pageUrl = 'https://go2-thailand.com/nl/things-to-do-in-thailand/';
  const schemas = [
    { '@context': 'https://schema.org', '@type': 'Article', headline: 'Wat te doen in Thailand: kies activiteiten per regio', description: 'Kies wat je in Thailand wilt doen op regio, reistempo en actuele conditie. Van steden en erfgoed tot natuur, eilanden en eten.', image: 'https://go2-thailand.com/images/redesign/thailand-excursions-hero.webp', url: pageUrl, inLanguage: 'nl-NL', author: { '@type': 'Organization', name: 'GO2 Thailand' }, publisher: { '@type': 'Organization', name: 'GO2 Thailand' } },
    { '@context': 'https://schema.org', '@type': 'ItemList', name: 'Activiteiten in Thailand per reisprofiel', numberOfItems: activityChoices.length, itemListElement: activityChoices.map((item, index) => ({ '@type': 'ListItem', position: index + 1, name: item.title, url: `https://go2-thailand.com/nl${item.href}` })) },
    { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(({ question, answer }) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) },
    { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Thailand', item: 'https://go2-thailand.com/nl/' }, { '@type': 'ListItem', position: 2, name: 'Wat te doen', item: pageUrl }] },
  ];

  return <>
    <SEOHead title="Wat te doen in Thailand: activiteiten per regio" description="Kies wat je in Thailand wilt doen op regio, reistempo en actuele conditie. Van steden en erfgoed tot natuur, eilanden en eten." ogImage="https://go2-thailand.com/images/redesign/thailand-excursions-hero.webp">
      {schemas.map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}
    </SEOHead>
    <div data-premium-template="things-to-do-thailand-nl" className="overflow-hidden bg-canvas text-charcoal">
      <EditorialHero image="/images/redesign/thailand-excursions-hero.webp" imageAlt="Reiziger kijkt uit over een groene baai en kalksteenlandschap in Thailand" breadcrumbs={[{ label: 'Thailand', href: '/' }, { label: 'Wat te doen' }]} eyebrow="Van inspiratie naar een uitvoerbare dag" title={<>Wat te doen in<br /><span className="text-saffron-dark">Thailand?</span></>} subtitle="Kies geen top-10. Kies een reisritme." description="Stad, erfgoed, bergen, eilanden, natuur of eten: de beste activiteit is degene die bij je regio, hotelbasis en actuele conditie past." actions={[{ label: 'Kies je activiteitstype', href: '#kiezen', kind: 'primary' }, { label: 'Bekijk boekbare uitjes', href: '/activities/', kind: 'secondary' }]} imageClassName="object-cover object-[68%_center]" />
      <PageSectionNav items={[{ href: '#kiezen', label: 'Kiezen', icon: Compass }, { href: '#ritme', label: 'Dagritme', icon: Sparkles }, { href: '#boeken', label: 'Controleren', icon: ShieldCheck }, { href: '#vragen', label: 'Vragen', icon: MapPinned }]} />

      <section id="kiezen" className="section-divider-bottom scroll-mt-24 py-16 lg:py-24"><div className="container-custom"><div className="grid gap-8 lg:grid-cols-[.68fr_1.32fr] lg:items-end"><SectionHeading eyebrow="Zes reisprofielen" title="Begin bij de omgeving, niet bij de ranglijst." description="Een landelijke top-10 verbergt afstanden, weer en drukte. Kies het profiel dat binnen je route past en open daarna de specifieke plaatsowner." /><p className="max-w-2xl text-sm font-medium leading-7 text-charcoal/62">Dezelfde activiteit kan per regio een andere logistiek, dresscode, toegangsregel of conditie hebben. Daarom linken de kaarten door naar de eigenaar die die lokale beslissing werkelijk kan uitleggen.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{activityChoices.map(({ title, kicker, description, href, image, imageAlt, icon: Icon }) => <Link key={title} href={href} className="group flex flex-col overflow-hidden rounded-2xl border border-jade/10 bg-white shadow-editorial-card"><div className="relative h-52 overflow-hidden"><Image src={image} alt={imageAlt} fill sizes="(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 33vw" className="object-cover transition duration-500 group-hover:scale-[1.035]" /><div className="absolute inset-0 bg-gradient-to-t from-jade/72 via-transparent to-transparent" /><span className="absolute bottom-4 left-4 grid h-10 w-10 place-items-center rounded-xl bg-ivory/92 text-jade"><Icon size={19} /></span></div><div className="flex flex-1 flex-col p-6"><p className="text-[9px] font-extrabold uppercase tracking-[.14em] text-saffron-dark">{kicker}</p><h2 className="mt-2 font-display text-[2rem] font-semibold leading-none text-jade">{title}</h2><p className="mt-4 text-xs font-medium leading-6 text-charcoal/65">{description}</p><span className="mt-auto inline-flex items-center gap-2 pt-6 text-xs font-extrabold text-jade">Open de keuzehulp <ArrowRight size={14} className="text-saffron-dark transition group-hover:translate-x-1" /></span></div></Link>)}</div></div></section>

      <section id="ritme" className="section-divider-bottom scroll-mt-24 bg-tonal py-16 lg:py-24"><div className="container-custom grid gap-10 lg:grid-cols-[.66fr_1.34fr]"><SectionHeading eyebrow="Een haalbare dag" title="Eén hoofdactiviteit is vaak genoeg." description="Reken pickup, wachttijd, toegang, hitte, eten en terugkeer mee. Een activiteit duurt zelden alleen de tijd die op de productkaart staat." /><div className="grid gap-4">{dayPatterns.map((pattern, index) => <article key={pattern.label} className="grid gap-4 rounded-2xl border border-jade/10 bg-white p-6 shadow-editorial-card sm:grid-cols-[auto_.75fr_1.25fr] sm:items-center"><span className="grid h-10 w-10 place-items-center rounded-full bg-jade text-xs font-black text-saffron">0{index + 1}</span><div><p className="text-[9px] font-extrabold uppercase tracking-[.13em] text-saffron-dark">{pattern.label}</p><h3 className="mt-2 font-display text-[1.55rem] font-semibold leading-none text-jade">{pattern.title}</h3></div><p className="text-xs font-medium leading-6 text-charcoal/64">{pattern.copy}</p></article>)}</div></div></section>

      <section id="boeken" className="section-divider-bottom scroll-mt-24 py-16 lg:py-24"><div className="container-custom overflow-hidden rounded-[28px] bg-jade text-white lg:grid lg:grid-cols-[.9fr_1.1fr]"><div className="p-7 lg:p-10"><p className="eyebrow !text-saffron">Pas na de keuze</p><h2 className="font-display text-[3rem] font-semibold leading-[.9]">Controleer het exacte product.</h2><p className="mt-5 text-sm font-medium leading-7 text-white/65">Controleer titel, bestemming, pickupzone, datum, inbegrepen toegang, fysieke vereisten, annuleringsvoorwaarden en actuele weers- of parkconditie. Go2Thailand voert de activiteit niet uit.</p><a href={klookHref} target="_blank" rel="noopener noreferrer nofollow sponsored" className="btn-cream mt-7 text-saffron-dark">Bekijk actuele activiteiten <ExternalLink size={14} /></a><AffiliateDisclosure className="mt-3 max-w-lg !text-white/55">Gesponsorde Klook-link. Beschikbaarheid, prijs, uitvoerder en voorwaarden kunnen wijzigen; controleer altijd de specifieke productpagina.</AffiliateDisclosure></div><div className="grid gap-px bg-white/10 sm:grid-cols-2"><div className="bg-jade p-7"><ShieldCheck className="text-saffron" /><h3 className="mt-5 font-display text-2xl font-semibold">Goede signalen</h3><ul className="mt-4 space-y-3 text-xs font-medium leading-5 text-white/64"><li>Exacte locatie en pickupzone</li><li>Heldere inclusies en uitsluitingen</li><li>Annulering en conditiebeleid</li><li>Geen diercontact of garantie</li></ul></div><div className="bg-jade p-7"><Compass className="text-saffron" /><h3 className="mt-5 font-display text-2xl font-semibold">Zelf controleren</h3><ul className="mt-4 space-y-3 text-xs font-medium leading-5 text-white/64"><li>Park- of tempeltoegang</li><li>Weer, zee en wegconditie</li><li>Kleding en fysieke belasting</li><li>Terugkeer naar je hotelbasis</li></ul></div></div></div></section>

      <FaqSplitSection id="vragen" eyebrow="Echte zoekvragen" title="Veelgestelde vragen over wat te doen in Thailand" description="De vier vragen zijn zichtbaar gecontroleerd in Google Nederland op 31 juli 2026. Subjectieve top-lijsten en veranderlijke prijzen krijgen bewust geen schijnexact antwoord." items={faqs} />
      <RelatedGuidesSection eyebrow="Van inspiratie naar planning" title="Maak de dag onderdeel van je reis" guides={[{ title: 'Boekbare excursies', description: 'Vergelijk categorieën en productchecks wanneer je daadwerkelijk wilt reserveren.', href: '/activities/', image: '/images/redesign/thailand-excursions-hero.webp', imageAlt: 'Excursies en activiteiten in Thailand' }, { title: 'Thailand-reisroutes', description: 'Kies eerst hotelbases en vrije dagen voordat je activiteiten vastzet.', href: '/itineraries/', image: '/images/redesign/thailand-route-hero.webp', imageAlt: 'Route door Thailand' }, { title: 'Regio’s vergelijken', description: 'Kies het grotere netwerk achter stad, natuur of kust.', href: '/region/', image: '/images/redesign/thailand-route-rhythm.webp', imageAlt: 'Reisnetwerken van Thailand' }]} />
      <SourceMethodSection title="Inspiratie met een controlemoment" description="De owner combineert lokaal beschikbare DFS-signalen, een zichtbare Nederlandse SERP met vier echte PAA-vragen en primaire bronnen. We rangschikken geen venue of operator als universeel beste en publiceren geen vaste productprijs." sources={[{ title: 'Bestemmingen en activiteiten', creator: 'Tourism Authority of Thailand', url: 'https://www.tourismthailand.org/Destinations', note: 'Officiële bestemming- en regiocontext.' }, { title: 'Parkstatus en natuurregels', creator: 'Department of National Parks Thailand', url: 'https://www.dnp.go.th/', note: 'Primaire startbron voor nationale parken en beschermde gebieden.' }, { title: 'Weer en waarschuwingen', creator: 'Thai Meteorological Department', url: 'https://www.tmd.go.th/en', note: 'Actuele weer-, wind- en kustcondities.' }, { title: 'Reisadvies Thailand', creator: 'NederlandWereldwijd', url: 'https://www.nederlandwereldwijd.nl/reisadvies/thailand', note: 'Actuele veiligheids- en regiocontext voor Nederlandse reizigers.' }]} />
    </div>
  </>;
}
