import { useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {
  ArrowRight,
  Baby,
  CalendarDays,
  Camera,
  CloudRain,
  Coins,
  Compass,
  ExternalLink,
  Heart,
  Hotel,
  PartyPopper,
  Route,
  Ship,
  Sparkles,
  Sun,
  Users,
  Waves,
  Wind,
} from 'lucide-react';
import SEOHead from '../SEOHead';
import { AffiliateDisclosure } from '../design/AffiliateDisclosure';
import { EditorialHero } from '../design/EditorialHero';
import { FaqSplitSection } from '../design/FaqSplitSection';
import { PageSectionNav } from '../design/PageSectionNav';
import { RelatedGuidesSection } from '../design/RelatedGuidesSection';
import { SectionHeading } from '../design/SectionHeading';
import { SourceMethodSection } from '../design/SourceMethodSection';
import { KLOOK_GENERIC, TRIP_GENERIC, TWELVEGO_GENERIC, withPlacementSubId } from '../../lib/affiliates';

const PAGE_URL = 'https://go2-thailand.com/blog/best-time-to-visit-thailand/';
const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] as const;
const monthSlugs = months.map((month) => month.toLowerCase());

const priorities = [
  { key: 'first', label: 'First trip', icon: Compass, answer: 'Start with November to February', title: 'Choose one broad route, then inspect its coast.', copy: 'This window often balances Bangkok, the north and the Andaman side. It is also popular, so availability and cancellation terms matter. A Gulf-heavy route still needs its own month check.', route: 'Bangkok · north · one coast', link: '/thailand-travel-guide/', linkLabel: 'Build a first Thailand route' },
  { key: 'beach', label: 'Beaches', icon: Waves, answer: 'Choose the coast before the month', title: 'Andaman and Gulf reward different windows.', copy: 'Use December to March as a broad Andaman starting point and January to September as a broad Gulf starting point. Current sea conditions and the exact island remain decisive.', route: 'Andaman or Gulf · not both by default', link: '/blog/thailand-island-hopping-guide/', linkLabel: 'Choose an island-hopping coast' },
  { key: 'quiet', label: 'Fewer crowds', icon: Users, answer: 'Trade certainty for breathing room', title: 'Transition and green months can feel less compressed.', copy: 'Lower demand is not guaranteed nationwide, but avoiding the broad peak window can widen room choice and make famous places feel less rushed. Build weather margin into the route.', route: 'Fewer bases · flexible outdoor days', link: '/weather/', linkLabel: 'Check the regional weather pattern' },
  { key: 'festival', label: 'Festivals', icon: PartyPopper, answer: 'Let the current programme choose the date', title: 'April and the lunar calendar create different trips.', copy: 'Songkran makes mid-April highly distinctive; Loy Krathong, Yi Peng and regional festivals follow annual programmes. Confirm the current official date, location and access before booking around one event.', route: 'One anchor event · flexible days around it', link: 'https://www.tourismthailand.org/Events-and-Festivals', linkLabel: 'Open the official event calendar', external: true },
  { key: 'family', label: 'Family', icon: Baby, answer: 'Comfort comes from fewer handoffs', title: 'A simple route beats the theoretical perfect month.', copy: 'January and February can be strong broad windows, but school dates and demand can tighten options. One southern base and protected arrival/departure days reduce weather and transfer stress.', route: 'City + one family base + buffer', link: '/itineraries/', linkLabel: 'Compare coherent itineraries' },
  { key: 'honeymoon', label: 'Honeymoon', icon: Heart, answer: 'Match privacy, coast and cancellation terms', title: 'The right hotel zone matters as much as the season.', copy: 'Choose the coast and daily rhythm first, then compare the same dates and room conditions. A beautiful resort on the wrong side of an island can create more travel than romance.', route: 'One city chapter · one slow coast', link: '/blog/thailand-honeymoon-guide-romantic-destinations/', linkLabel: 'Open the Thailand honeymoon guide' },
] as const;

const faqs = [
  { question: 'What are the best and worst months to visit Thailand?', answer: 'November to February is often the strongest broad window for a first route through Bangkok, the north and the Andaman coast. There is no universal worst month: April brings heat, the green season brings more rain and flexibility, and the Gulf has a later wet pattern. The wrong month is the one that conflicts with your coast, activity and tolerance for crowds or disruption.' },
  { question: 'What is the cheapest time to visit Thailand?', answer: 'Lower-demand green-season months can produce more room and flight choice, but there is no permanent cheapest month or guaranteed discount. School holidays, events, route, booking terms and live inventory change the total. Compare the same dates and conditions after choosing a region that still fits the weather trade-off.' },
  { question: 'What months are high season in Thailand?', answer: 'November to February is the broad national peak-season shorthand, especially for first trips and many Andaman routes. Individual islands, events and domestic holiday periods can create a different local peak, so use live accommodation and transport availability for the exact destination.' },
  { question: 'What is low season in Thailand?', answer: 'Low season usually refers to wetter, lower-demand months, often from around May into October for many mainland and Andaman destinations. It is a commercial label rather than one official nationwide season. The Gulf coast can follow a different weather and demand rhythm.' },
  { question: 'What month does Thailand get less tourists?', answer: 'There is no reliable country-wide least-busy month. Some destinations feel quieter during wetter months, but school holidays, festivals, domestic travel and coast-specific weather can move demand. Compare your exact destination and dates rather than choosing from a national crowd claim.' },
  { question: 'What month is best for Thailand beaches?', answer: 'For the Andaman side, December to March is a useful broad starting window. For Koh Samui and nearby Gulf islands, January to September can be a different starting range. Neither is a guarantee: check current marine warnings, park access and ferry operations close to the trip.' },
  { question: 'Which months should I not visit Thailand?', answer: 'Do not reject a whole month nationally. Instead, avoid route conflicts: exposed Andaman boat plans during unstable southwest-monsoon conditions, a Gulf beach assumption late in the year, or a northern outdoor trip without checking heat and air quality. Thailand remains route-dependent year-round.' },
  { question: 'Where to go in Thailand to avoid crowds?', answer: 'Choose a less compressed route rather than hunting for a permanently empty destination. Secondary cities such as Trang, Nakhon Si Thammarat or Chanthaburi can offer more local depth, while quieter zones on major islands can reduce daily transfers. Weekday timing and fewer one-night stops also help.' },
  { question: 'Which is the biggest festival in Thailand?', answer: 'Songkran, Thai New Year in mid-April, is the most visibly nationwide visitor event. Loy Krathong is also celebrated widely, while Yi Peng and regional festivals have more location-specific programmes. Confirm the current official schedule and local rules before making non-refundable bookings.' },
  { question: 'Which part of Thailand is best to visit with family?', answer: 'The best fit depends on children’s ages and the desired pace. Bangkok plus one northern or coastal base keeps transfers manageable; Hua Hin, Koh Samui and selected Phuket or Krabi zones can work when the hotel, beach access and transport fit the family. Compare the neighbourhood and full transfer, not only the destination name.' },
];

const navItems = [
  { href: '#match' as const, label: 'Your match', icon: Compass },
  { href: '#seasons' as const, label: 'Seasons', icon: Sun },
  { href: '#demand' as const, label: 'Demand', icon: Users },
  { href: '#events' as const, label: 'Events', icon: PartyPopper },
  { href: '#months' as const, label: 'Months', icon: CalendarDays },
  { href: '#book' as const, label: 'Book', icon: Hotel },
];

export function BestTimeThailandGuideEn() {
  const [activePriority, setActivePriority] = useState(0);
  const selected = priorities[activePriority];
  const tripHref = withPlacementSubId(TRIP_GENERIC, 'en-best-time-thailand', 'window-hotels');
  const klookHref = withPlacementSubId(KLOOK_GENERIC, 'en-best-time-thailand', 'window-activities');
  const transportHref = withPlacementSubId(TWELVEGO_GENERIC, 'en-best-time-thailand', 'window-transport');
  const schemas = [
    { '@context': 'https://schema.org', '@type': 'Article', headline: 'Best time to visit Thailand: choose by travel style', description: 'Choose the best time to visit Thailand by coast, crowds, festivals, family fit and route style—not one universal weather rule.', url: PAGE_URL, image: 'https://go2-thailand.com/images/redesign/best-time-thailand-hero-v2.webp', inLanguage: 'en-GB', dateModified: '2026-07-27', author: { '@type': 'Organization', name: 'Go2Thailand' }, publisher: { '@type': 'Organization', name: 'Go2Thailand' } },
    { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) },
    { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://go2-thailand.com/' }, { '@type': 'ListItem', position: 2, name: 'Travel guide', item: 'https://go2-thailand.com/thailand-travel-guide/' }, { '@type': 'ListItem', position: 3, name: 'Best time to visit Thailand', item: PAGE_URL }] },
    { '@context': 'https://schema.org', '@type': 'ItemList', name: 'Thailand travel months', itemListElement: months.map((month, index) => ({ '@type': 'ListItem', position: index + 1, name: month, url: `https://go2-thailand.com/thailand-in/${monthSlugs[index]}/` })) },
  ];

  return <>
    <SEOHead title="Best Time to Visit Thailand: Choose Your Window" description="Find the best time to visit Thailand for your route: compare coasts, crowds, high and low season, festivals, family trips and live booking pressure." ogImage="https://go2-thailand.com/images/redesign/best-time-thailand-hero-v2.webp">
      {schemas.map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}
    </SEOHead>
    <div className="bg-canvas text-charcoal" data-premium-template="best-time-thailand-en">
      <EditorialHero image="/images/redesign/best-time-thailand-hero-v2.webp" imageAlt="Thailand bay moving from golden clear weather into a passing tropical shower" breadcrumbs={[{ label: 'Thailand', href: '/' }, { label: 'Travel guide', href: '/thailand-travel-guide/' }, { label: 'Best time to visit' }]} eyebrow="Choose the benefit—not one perfect month" title={<>Best time to visit<br /><span className="text-saffron">Thailand?</span></>} subtitle="Your route changes the answer." description="November to February is the strongest broad starting point for many first trips. But beaches, crowds, festivals, family pace and the Gulf–Andaman split can make a different window better for you." actions={[{ label: 'Find your travel window', href: '#match', kind: 'primary' }, { label: 'Compare climate data', href: '/weather/', kind: 'secondary' }]} minHeightClassName="min-h-[740px] lg:min-h-[720px]" titleClassName="max-w-[900px] text-[3.75rem] leading-[0.86] !text-white sm:text-[5.2rem] lg:text-[6rem]" subtitleClassName="max-w-[610px] !text-white" descriptionClassName="mt-4 max-w-[620px] text-sm leading-7 !text-white/80" imageClassName="object-cover object-[58%_center] lg:object-center" gradientClassName="bg-[linear-gradient(180deg,rgba(5,39,33,0.18)_0%,rgba(5,39,33,0.48)_48%,rgba(5,39,33,0.96)_100%)] lg:bg-[linear-gradient(90deg,rgba(4,42,34,0.99)_0%,rgba(4,42,34,0.93)_40%,rgba(4,42,34,0.16)_67%,rgba(4,42,34,0.03)_100%)]" contentClassName="max-w-[900px] [&_nav]:!text-white/60 [&_nav_span]:!text-white/75" sideCard={<div className="absolute bottom-8 right-[max(2rem,calc((100vw-1280px)/2))] z-10 hidden w-[315px] rounded-2xl border border-white/22 bg-jade/80 p-5 text-white shadow-editorial-card backdrop-blur-lg xl:block"><p className="text-[9px] font-extrabold uppercase tracking-[0.15em] text-saffron-light">The useful distinction</p><strong className="mt-3 block font-display text-3xl font-semibold">Climate chooses the coast.<br />You choose the trade-off.</strong><p className="mt-3 text-[10px] font-semibold leading-5 text-white/58">There is no permanent cheapest, quietest or driest month for every route.</p></div>} />
      <PageSectionNav items={navItems} />

      <section className="section-divider-bottom py-14 lg:py-20"><div className="container-custom grid gap-10 lg:grid-cols-[0.72fr_1.28fr] lg:items-center"><SectionHeading eyebrow="The 60-second answer" title="Begin with November–February. Then challenge it." description="That broad window often suits Bangkok, the north and Andaman. It also brings stronger demand, and it does not erase the Gulf’s later wet pattern or northern air-quality decisions." /><div className="grid gap-4 sm:grid-cols-3">{[
        { icon: Sun, label: 'Broad first trip', value: 'Nov – Feb', copy: 'Useful for a classic city, north and Andaman route.' },
        { icon: Users, label: 'More breathing room', value: 'Transition', copy: 'Trade some weather certainty for a less compressed trip.' },
        { icon: Waves, label: 'Beach-led trip', value: 'Choose coast', copy: 'The correct sea matters before a nationwide month label.' },
      ].map((item, index) => { const Icon = item.icon; return <article key={item.label} className={`rounded-2xl border p-6 ${index === 2 ? 'border-saffron/35 bg-jade text-white shadow-editorial-lift' : 'border-jade/10 bg-white shadow-editorial-card'}`}><Icon className={index === 2 ? 'text-saffron-light' : 'text-jade'} /><p className={`mt-6 text-[9px] font-extrabold uppercase tracking-[.14em] ${index === 2 ? 'text-saffron-light' : 'text-saffron-dark'}`}>{item.label}</p><strong className="mt-2 block font-display text-3xl font-semibold">{item.value}</strong><p className={`mt-3 text-xs font-medium leading-5 ${index === 2 ? 'text-white/62' : 'text-charcoal/60'}`}>{item.copy}</p></article>; })}</div></div></section>

      <section id="match" className="section-divider-bottom scroll-mt-24 bg-tonal py-16 lg:py-24"><div className="container-custom"><SectionHeading eyebrow="Your trip changes the answer" title="What matters most this time?" description="Choose a priority. The result gives you a starting window and, more importantly, the next specialist owner to open." />
        <div className="mt-9 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6" role="group" aria-label="Choose your main travel priority">{priorities.map((item, index) => { const Icon = item.icon; return <button key={item.key} type="button" aria-pressed={activePriority === index} onClick={() => setActivePriority(index)} className={`flex min-h-24 flex-col items-center justify-center gap-3 rounded-2xl border px-3 text-[10px] font-extrabold transition ${activePriority === index ? 'border-jade bg-jade text-white shadow-editorial-card' : 'border-jade/10 bg-white text-jade hover:border-saffron/40'}`}><Icon size={20} className={activePriority === index ? 'text-saffron-light' : 'text-saffron-dark'} />{item.label}</button>; })}</div>
        <div className="mt-5 overflow-hidden rounded-[28px] border border-jade/10 bg-white shadow-editorial-lift"><div className="grid lg:grid-cols-[0.78fr_1.22fr]"><div className="bg-jade p-8 text-white sm:p-11" aria-live="polite"><p className="eyebrow !text-saffron-light">{selected.answer}</p><h2 className="font-display text-[3.4rem] font-semibold leading-[.88]">{selected.title}</h2><p className="mt-5 text-sm font-medium leading-7 text-white/65">{selected.copy}</p><div className="mt-7 rounded-2xl border border-white/12 bg-white/[.06] p-5"><p className="text-[9px] font-extrabold uppercase tracking-[.14em] text-white/40">Route shape</p><p className="mt-2 font-display text-2xl font-semibold text-white">{selected.route}</p></div>{'external' in selected && selected.external ? <a href={selected.link} target="_blank" rel="noopener noreferrer" className="btn-cream mt-7">{selected.linkLabel} <ExternalLink size={14} /></a> : <Link href={selected.link} className="btn-cream mt-7">{selected.linkLabel} <ArrowRight size={14} /></Link>}</div><div className="relative min-h-[430px]"><Image src={activePriority === 3 ? '/images/redesign/ubon-ratchathani-candle-festival.webp' : activePriority === 5 ? '/images/redesign/stay-island-hideaway.webp' : activePriority === 1 ? '/images/redesign/thailand-route-coast-fork.webp' : '/images/redesign/thailand-route-rhythm.webp'} alt="Thailand route matched to the selected travel priority" fill sizes="(max-width:1024px) 100vw, 55vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-jade/35 to-transparent" /></div></div></div>
      </div></section>

      <section id="seasons" className="section-divider-bottom scroll-mt-24 py-16 lg:py-24"><div className="container-custom"><SectionHeading eyebrow="Three commercial labels, regional reality" title="Every season gives something—and asks something." description="Use these as decision frames. For rainfall, temperature and station-level month data, move to the weather owner." /><div className="mt-10 grid gap-5 lg:grid-cols-3">{[
        { icon: Wind, months: 'Nov – Feb', title: 'Cooler · broad peak', gain: 'Comfortable city and northern days; many Andaman routes enter a stronger window.', cost: 'More demand, tighter inventory and less room for spontaneous changes.', href: '/weather/' },
        { icon: Sun, months: 'Mar – May', title: 'Hot · transition', gain: 'Songkran, Gulf possibilities and a shift away from the broad winter peak.', cost: 'Heat changes the daily rhythm; northern air quality requires a current check.', href: '/blog/songkran-festival-2026-guide/' },
        { icon: CloudRain, months: 'May – Oct', title: 'Green · lower demand', gain: 'Lush landscapes and potentially wider current choice in some destinations.', cost: 'More disruption margin, coast selection and live weather checks.', href: '/weather/' },
      ].map((item, index) => { const Icon = item.icon; return <article key={item.title} className={`overflow-hidden rounded-[26px] border ${index === 1 ? 'border-saffron/30 bg-jade text-white shadow-editorial-lift' : 'border-jade/10 bg-white shadow-editorial-card'}`}><div className="p-7 sm:p-8"><div className="flex items-center justify-between"><span className={`grid h-12 w-12 place-items-center rounded-xl border ${index === 1 ? 'border-white/15 text-saffron-light' : 'border-saffron/28 bg-canvas text-jade'}`}><Icon size={21} /></span><span className={`text-[9px] font-extrabold uppercase tracking-[.14em] ${index === 1 ? 'text-saffron-light' : 'text-saffron-dark'}`}>{item.months}</span></div><h2 className="mt-7 font-display text-3xl font-semibold">{item.title}</h2><div className={`mt-6 border-t pt-5 ${index === 1 ? 'border-white/12' : 'border-jade/8'}`}><p className="text-[9px] font-extrabold uppercase tracking-[.13em] opacity-45">What you gain</p><p className="mt-2 text-xs font-medium leading-6 opacity-70">{item.gain}</p><p className="mt-5 text-[9px] font-extrabold uppercase tracking-[.13em] opacity-45">What it asks</p><p className="mt-2 text-xs font-medium leading-6 opacity-70">{item.cost}</p></div><Link href={item.href} className={`mt-6 inline-flex items-center gap-2 text-xs font-extrabold ${index === 1 ? 'text-saffron-light' : 'text-jade'}`}>Open the specialist guide <ArrowRight size={14} /></Link></div></article>; })}</div></div></section>

      <section className="section-divider-bottom bg-mist py-16 lg:py-24"><div className="container-custom"><div className="relative min-h-[520px] overflow-hidden rounded-[30px] shadow-editorial-lift"><Image src="/images/redesign/thailand-route-coast-fork.webp" alt="Thailand route splitting between the Andaman and Gulf coasts" fill sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-jade via-jade/78 to-jade/14" /><div className="relative flex min-h-[520px] max-w-[650px] flex-col justify-center p-8 text-white sm:p-12"><p className="eyebrow !text-saffron-light">The coast switch</p><h2 className="font-display text-[3.9rem] font-semibold leading-[.86]">Do not ask for the best beach month nationally.</h2><p className="mt-6 text-sm font-medium leading-7 text-white/68">Choose Andaman or Gulf, then compare the month, sea conditions and exact island. Combining both coasts can consume a real transfer day.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/weather/" className="btn-cream">Compare climate data <ArrowRight size={14} /></Link><Link href="/blog/thailand-island-hopping-guide/" className="btn-outline-light">Plan the island route <ArrowRight size={14} /></Link></div></div></div></div></section>

      <section id="demand" className="section-divider-bottom scroll-mt-24 py-16 lg:py-24"><div className="container-custom grid gap-10 lg:grid-cols-[.68fr_1.32fr]"><SectionHeading eyebrow="Price follows demand—not a fixed calendar" title="High, shoulder and low season are live market conditions." description="Season labels can help, but they do not prove a discount. Compare the same room, transport and terms for your dates after the route is fixed." /><div className="grid gap-4">{[
        { icon: Sparkles, label: 'Broad peak', title: 'More certainty · less slack', copy: 'Popular winter windows can tighten rooms, transport and event availability. Book the route-critical pieces first.' },
        { icon: Route, label: 'Transition', title: 'The useful compromise', copy: 'A transition month can trade some weather certainty for wider choice. The exact coast and activity decide whether that trade is sensible.' },
        { icon: Coins, label: 'Lower demand', title: 'Potential value · no promise', copy: 'Some dates offer wider live choice, but a festival, school holiday or local event can reverse the pattern. Compare actual totals and cancellation terms.' },
      ].map(({ icon: Icon, label, title, copy }, index) => <article key={label} className={`grid gap-5 rounded-2xl border p-6 sm:grid-cols-[auto_1fr] ${index === 1 ? 'border-saffron/30 bg-tonal shadow-editorial-card' : 'border-jade/10 bg-white'}`}><span className="grid h-12 w-12 place-items-center rounded-xl border border-saffron/28 bg-canvas text-jade"><Icon size={21} /></span><div><p className="text-[9px] font-extrabold uppercase tracking-[.14em] text-saffron-dark">{label}</p><h3 className="mt-2 font-display text-3xl font-semibold text-jade">{title}</h3><p className="mt-3 text-xs font-medium leading-6 text-charcoal/62">{copy}</p></div></article>)}</div></div></section>

      <section id="events" className="section-divider-bottom scroll-mt-24 bg-tonal py-16 lg:py-24"><div className="container-custom"><SectionHeading eyebrow="Let one event anchor the route" title="Festival travel needs a current programme." description="Annual and lunar events can move, split across locations or change access rules. Use these as trip ideas, then verify the official programme before paying." /><div className="mt-10 grid gap-5 md:grid-cols-3">{[
        { image: '/images/blog/songkran-festival-2026-guide.webp', eyebrow: 'Mid-April', title: 'Songkran', copy: 'Nationwide Thai New Year with major local programmes. Heat, domestic movement and wet public spaces change logistics.', href: '/blog/songkran-festival-2026-guide/' },
        { image: '/images/blog/night-markets-food-lovers-bangkok-chiang-mai-phuket.webp', eyebrow: 'Lunar calendar', title: 'Loy Krathong · Yi Peng', copy: 'Related but distinct experiences. Confirm the current dates, venue, ticketing and local rules rather than copying last year.', href: '/city/chiang-mai/' },
        { image: '/images/redesign/ubon-ratchathani-candle-festival.webp', eyebrow: 'Regional programme', title: 'Candle Festival', copy: 'A strong reason to build an Isaan route around Ubon Ratchathani—after the annual official programme is live.', href: '/city/ubon-ratchathani/' },
      ].map((item) => <Link key={item.title} href={item.href} className="group overflow-hidden rounded-2xl border border-jade/10 bg-white shadow-editorial-card"><div className="relative h-52 overflow-hidden"><Image src={item.image} alt={`${item.title} travel in Thailand`} fill sizes="(max-width:768px) 100vw, 33vw" className="object-cover transition duration-500 group-hover:scale-[1.035]" /></div><div className="p-6"><p className="text-[9px] font-extrabold uppercase tracking-[.14em] text-saffron-dark">{item.eyebrow}</p><h3 className="mt-2 font-display text-3xl font-semibold text-jade">{item.title}</h3><p className="mt-3 text-xs font-medium leading-6 text-charcoal/62">{item.copy}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-extrabold text-jade">Open guide <ArrowRight size={14} className="text-saffron" /></span></div></Link>)}</div></div></section>

      <section id="months" className="section-divider-bottom scroll-mt-24 py-16 lg:py-24"><div className="container-custom"><SectionHeading eyebrow="Already have dates?" title="Open the month owner—not another generic table." description="Each month page can hold the specific route and event context. The weather hub remains the place for station-level climate comparison." /><div className="mt-9 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{months.map((month, index) => <Link key={month} href={`/thailand-in/${monthSlugs[index]}/`} className="group rounded-2xl border border-jade/10 bg-white p-5 shadow-editorial-card transition hover:-translate-y-0.5 hover:border-saffron/35"><div className="flex items-center justify-between"><span className="text-[9px] font-extrabold uppercase tracking-[.14em] text-saffron-dark">{String(index + 1).padStart(2, '0')}</span><CalendarDays size={15} className="text-jade/35" /></div><strong className="mt-6 block font-display text-2xl font-semibold text-jade">{month}</strong><span className="mt-3 inline-flex items-center gap-2 text-[10px] font-extrabold text-charcoal/48">Open month <ArrowRight size={12} className="text-saffron" /></span></Link>)}</div></div></section>

      <section id="book" className="section-divider-bottom scroll-mt-24 bg-jade py-16 text-white lg:py-24"><div className="container-custom"><div className="grid gap-8 lg:grid-cols-[.68fr_1.32fr] lg:items-end"><div><p className="eyebrow !text-saffron-light">After choosing the window</p><h2 className="font-display text-[3.5rem] font-semibold leading-[.9] text-white">Check what is actually available.</h2><p className="mt-5 max-w-[540px] text-sm font-medium leading-7 text-white/68">No frozen room rate, ferry fare or tour price belongs in a timing guide. Open the same dates, compare complete terms and keep weather-sensitive pieces flexible.</p></div><div className="grid gap-3 sm:grid-cols-3"><span className="rounded-xl border border-white/12 bg-white/[.06] px-4 py-3 text-[10px] font-bold">1 · choose the window</span><span className="rounded-xl border border-white/12 bg-white/[.06] px-4 py-3 text-[10px] font-bold">2 · protect the route</span><span className="rounded-xl border border-white/12 bg-white/[.06] px-4 py-3 text-[10px] font-bold">3 · compare live terms</span></div></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[
        { icon: Hotel, title: 'Accommodation', copy: 'Compare the exact district, dates, room conditions and cancellation terms.', href: tripHref, label: 'Check current hotel options' },
        { icon: Camera, title: 'Experiences', copy: 'Add activities only after the route and recovery margin are visible.', href: klookHref, label: 'Check current activities' },
        { icon: Ship, title: 'Transport', copy: 'Compare live operators, complete transfer chains, luggage and change conditions.', href: transportHref, label: 'Check current transport' },
      ].map(({ icon: Icon, title, copy, href, label }) => <article key={title} className="flex min-h-[280px] flex-col rounded-2xl border border-white/12 bg-white/[.06] p-7 backdrop-blur"><Icon className="text-saffron-light" /><h3 className="mt-7 font-display text-3xl font-semibold">{title}</h3><p className="mt-4 flex-1 text-xs font-medium leading-6 text-white/62">{copy}</p><a href={href} target="_blank" rel="noopener noreferrer nofollow sponsored" className="mt-6 inline-flex items-center gap-2 text-xs font-extrabold text-white">{label} <ExternalLink size={13} className="text-saffron-light" /></a></article>)}</div><AffiliateDisclosure className="mt-4 !text-white/62">Trip.com, Klook and 12Go links are affiliate links. Go2Thailand may earn a commission without increasing your price. Providers control current price, availability and terms.</AffiliateDisclosure></div></section>

      <FaqSplitSection eyebrow="Real UK search questions" title="Best time to visit Thailand FAQs" description="These questions appeared verbatim across twelve live UK Google SERPs captured through DataForSEO on 27 July 2026. Answers preserve the route, coast and live-market qualifiers that generic snippets often omit." items={faqs} />
      <RelatedGuidesSection eyebrow="Turn timing into a route" title="Your next planning decision" guides={[{ title: 'Thailand weather', description: 'Compare climate normals, rainy season and the Andaman–Gulf split by month.', href: '/weather/', image: '/images/redesign/thailand-weather-hub-hero.webp', imageAlt: 'Thailand weather across regions' }, { title: 'How long in Thailand?', description: 'Match nights, bases and transfer cost before adding another destination.', href: '/blog/how-long-spend-thailand/', image: '/images/redesign/how-long-thailand-trip-planner-hero-v2.webp', imageAlt: 'Thailand route planned by trip length' }, { title: 'Thailand island hopping', description: 'Choose one coast and build a realistic ferry sequence around it.', href: '/blog/thailand-island-hopping-guide/', image: '/images/redesign/thailand-island-hopping-hero-v2.webp', imageAlt: 'Thailand island-hopping route' }]} sideLink={{ label: 'Browse all Thailand destinations', href: '/city/' }} readLabel="Open the owner" />
      <SourceMethodSection eyebrow="Sources & method" title="The best time is a decision—not a recycled calendar." description="Seven DataForSEO clusters produced 381 raw records and 281 unique keyword strings. Twelve live UK-English SERPs returned 99 organic results and 65 PAA records. Three full competitor parses, exact ranking/backlink checks and primary Thai weather, park and event sources informed the owner split. Climate detail stays on `/weather/`; this page owns travel-style, demand and route trade-offs." sources={[{ title: 'Current forecasts and warnings', creator: 'Thai Meteorological Department', url: 'https://www.tmd.go.th/en/', note: 'Primary live weather source; season guidance never replaces a local forecast.' }, { title: 'Events and festivals', creator: 'Tourism Authority of Thailand', url: 'https://www.tourismthailand.org/Events-and-Festivals', note: 'Primary current programme handoff for festival-led travel.' }, { title: 'National park information', creator: 'Department of National Parks, Wildlife and Plant Conservation', url: 'https://portal.dnp.go.th/', note: 'Primary source to verify current park and seasonal access.' }, { title: 'When is the best time to visit Thailand?', creator: 'Fan Club Thailand', url: 'https://fanclubthailand.co.uk/when-is-the-best-time-to-visit-thailand/', note: 'UK SERP competitor benchmark for season and month structure.' }, { title: 'The best time to visit Thailand', creator: 'Condé Nast Traveller', url: 'https://www.cntraveler.com/story/best-time-to-visit-thailand', note: 'UK SERP competitor benchmark for demand and regional decisions.' }, { title: 'Best Thai islands by month', creator: 'I Am Koh Chang', url: 'https://iamkohchang.com/blog/best-islands-to-visit-monthly-weather.html', note: 'Competitor benchmark for coast-specific island timing.' }]} />
    </div>
  </>;
}
